GAME_NAME: "pong"
ALE_ENV_ID: "ALE/Pong-v5"
GXM_ENV_ID: "Pong-v5"
ENVPOOL_ENV_ID: "Pong-v5"
GXM_ENV_TYPE: "envpool"
GXM_PLATFORMS: ["gpu"]
BENCHMARK_BACKENDS: ["jaxatari"] #["jaxatari", "ale", "gxm", "envpool_xla", "envpool_async", "envpool_sync"]
ALE_TIMEOUT_S: 3600
GXM_TIMEOUT_S: 3600
ENVPOOL_TIMEOUT_S: 3600

JAXATARI_MODES: ["oc", "pixel"]
JAXATARI_PIXEL_OPTIONS: ["resized", "grayscale", "native"]
JAXATARI_PIXEL_TRY_ALL_COMBINATIONS: false
JAXATARI_PIXEL_OPTION_COMBINATIONS:
  - ["resized", "grayscale", "native"]
JAXATARI_PLATFORMS: ["gpu", "cpu"]
ATARI_FRAME_SKIP: 4
PIXEL_RESIZE_SHAPE: [84, 84]

SAVE_RESULTS_CSV: true
RESULTS_CSV_PATH: "./scripts/benchmarks/outputs/throughput_results.csv"

SEED: 0

ENV_COUNTS: [1, 4, 8, 16, 32, 64, 128, 512, 1024, 2048]
NUM_STEPS: 100000

GIVEN_ACTION: 0

WANDB_MODE: "online"
ENTITY: ""
PROJECT: "jaxatari-throughput"
RUN_NAME: "throughput_analysis"
TAGS: ["benchmark", "throughput", "jaxatari"]
NOTES: ""
