_wandb:
    value:
        cli_version: 0.24.1
        e:
            sv29la0ib6il5bmtifp2ul5h3upzczbe:
                args:
                    - +alg=ppo_jaxatari_object
                codePath: scripts/benchmarks/ppo_agent.py
                codePathLocal: scripts/benchmarks/ppo_agent.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "2009650196480"
                        used: "687374159872"
                email: bestnaomiiiii@gmail.com
                executable: /home/adrian/yuhang/praktikum-ki/git/JAXAtari/.venv/bin/python
                git:
                    commit: 558affd4fb2750daaa7e5e647d70b4df8386f114
                host: nobara-pc
                memory:
                    total: "32708849664"
                os: Linux-6.18.7-200.nobara.fc43.x86_64-x86_64-with-glibc2.42
                program: /home/adrian/yuhang/praktikum-ki/git/JAXAtari/scripts/benchmarks/ppo_agent.py
                python: CPython 3.12.12
                root: /home/adrian/yuhang/praktikum-ki/git/JAXAtari
                startedAt: "2026-02-25T17:10:56.350520Z"
                writerId: sv29la0ib6il5bmtifp2ul5h3upzczbe
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 12
                - 45
                - 50
            "2":
                - 12
                - 45
                - 50
            "3":
                - 13
                - 15
                - 16
            "4": 3.12.12
            "5": 0.24.1
            "12": 0.24.1
            "13": linux-x86_64
ACTIVATION:
    value: tanh
ALG_NAME:
    value: ppo
ANNEAL_LR:
    value: true
CLIP_EPS:
    value: 0.2
ENT_COEF:
    value: 0.01
ENTITY:
    value: ""
ENV_NAME:
    value: gopher
GAE_LAMBDA:
    value: 0.95
GAMMA:
    value: 0.99
HYP_TUNE:
    value: false
LR:
    value: 0.00025
MAX_GRAD_NORM:
    value: 0.5
MOD_NAME:
    value: None
NAME_INITIALS:
    value: RE
NUM_ENVS:
    value: 1024
NUM_MINIBATCHES:
    value: 128
NUM_SEEDS:
    value: 1
NUM_STEPS:
    value: 128
OBJECT_CENTRIC:
    value: true
PROJECT:
    value: ""
RECORD_VIDEO:
    value: true
SAVE_PATH:
    value: ./models
SEED:
    value: 0
TEST_NUM_ENVS:
    value: 1024
TEST_NUM_STEPS:
    value: 10000
TOTAL_TIMESTEPS:
    value: 5e+07
TOTAL_TIMESTEPS_DECAY:
    value: 5e+07
UPDATE_EPOCHS:
    value: 4
VF_COEF:
    value: 0.5
WANDB_LOG_ALL_SEEDS:
    value: false
WANDB_MODE:
    value: online
alg:
    value:
        ACTIVATION: tanh
        ALG_NAME: ppo
        ANNEAL_LR: true
        CLIP_EPS: 0.2
        ENT_COEF: 0.01
        ENV_NAME: gopher
        GAE_LAMBDA: 0.95
        GAMMA: 0.99
        LR: 0.00025
        MAX_GRAD_NORM: 0.5
        MOD_NAME: None
        NAME_INITIALS: RE
        NUM_ENVS: 1024
        NUM_MINIBATCHES: 128
        NUM_STEPS: 128
        OBJECT_CENTRIC: true
        RECORD_VIDEO: true
        TEST_NUM_ENVS: 1024
        TEST_NUM_STEPS: 10000
        TOTAL_TIMESTEPS: 5e+07
        TOTAL_TIMESTEPS_DECAY: 5e+07
        UPDATE_EPOCHS: 4
        VF_COEF: 0.5
        WANDB_LOG_ALL_SEEDS: false
