NUM_SEEDS: 1
SEED: 0
HYP_TUNE: false
WANDB_MODE: online
ENTITY: ''
PROJECT: ''
alg:
  WANDB_LOG_ALL_SEEDS: false
  NAME_INITIALS: RE
  ALG_NAME: ppo
  TOTAL_TIMESTEPS: 50000000.0
  TOTAL_TIMESTEPS_DECAY: 50000000.0
  NUM_ENVS: 1024
  NUM_STEPS: 128
  UPDATE_EPOCHS: 4
  NUM_MINIBATCHES: 128
  LR: 0.00025
  MAX_GRAD_NORM: 0.5
  ANNEAL_LR: true
  GAMMA: 0.99
  GAE_LAMBDA: 0.95
  CLIP_EPS: 0.2
  ENT_COEF: 0.01
  VF_COEF: 0.5
  ACTIVATION: tanh
  ENV_NAME: gopher
  ENV_KWARGS: {}
  OBJECT_CENTRIC: true
  MOD_NAME: None
  TEST_NUM_ENVS: 1024
  TEST_NUM_STEPS: 10000
  RECORD_VIDEO: true
SAVE_PATH: ./models
WANDB_LOG_ALL_SEEDS: false
NAME_INITIALS: RE
ALG_NAME: ppo
TOTAL_TIMESTEPS: 50000000.0
TOTAL_TIMESTEPS_DECAY: 50000000.0
NUM_ENVS: 1024
NUM_STEPS: 128
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 128
LR: 0.00025
MAX_GRAD_NORM: 0.5
ANNEAL_LR: true
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
ACTIVATION: tanh
ENV_NAME: gopher
ENV_KWARGS: {}
OBJECT_CENTRIC: true
MOD_NAME: None
TEST_NUM_ENVS: 1024
TEST_NUM_STEPS: 10000
RECORD_VIDEO: true
NUM_UPDATES: 381.0
MINIBATCH_SIZE: 1024
