# PPO object-centric config for MsPacman
NAME_INITIALS: "RE"
ALG_NAME: "ppo"
TOTAL_TIMESTEPS: 5e7
TOTAL_TIMESTEPS_DECAY: 5e7
NUM_ENVS: 1024
NUM_STEPS: 128
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 128
LR: 2.5e-4
MAX_GRAD_NORM: 0.5
ANNEAL_LR: True
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
ACTIVATION: "tanh"

# env specific
ENV_NAME: "MsPacman"
ENV_KWARGS: {}
OBJECT_CENTRIC: True
MOD_NAME: null

# Testing
TEST_NUM_ENVS: 1024
TEST_NUM_STEPS: 10000
RECORD_VIDEO: True
