EXP_NAME: ppo
TRACK: true
CAPTURE_VIDEO: true

EVAL_DURING_TRAIN: false
EVAL_EVERY: 1000

PIXEL_BASED: true
NATIVE_DOWNSCALING: true
SMOOTH_IMAGE: false

SAVE_MODEL: false
UPLOAD_MODEL: false
HF_ENTITY: ""

ENV_ID: pong
TRAIN_MODS: []
EVAL_MODS: []

TOTAL_TIMESTEPS: 10000000
LEARNING_RATE: 0.00025
NUM_ENVS: 8
NUM_STEPS: 128
ANNEAL_LR: true
GAMMA: 0.99
GAE_LAMBDA: 0.95
NUM_MINIBATCHES: 4
UPDATE_EPOCHS: 4
NORM_ADV: true
CLIP_COEF: 0.1
CLIP_VLOSS: false
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
TARGET_KL: null
