"""Level 16, against the corrected ROM reference.

The block in hero_levels.py was generated by walking the level through the
game's own room-transition code, capturing each room off the real ROM and
refusing to emit anything unless the capture agreed with the reference cell
for cell. These tests re-check that agreement from the committed data alone
(no ale-py), and check the engine draws it.

What came out of level 16:

  * THE WALK REACHES ALL SIXTEEN ROOMS. The reference had eight, and rooms
    2-7 of those were read off the playthrough: eleven of their bands were
    wrong (rock where the ROM draws magma, `?` cells, and room 7's corridor
    was room 8's). The reference now holds the ROM walk for all sixteen.
  * THE OLD BLOCK WAS BUILT ON THE SUPERSEDED REFERENCE: four creatures, one
    lantern, no magma, no water, the miner at x 129. Every table is new.
  * ROOMS 7 AND 9 BREATHE MAGMA (HL.MAGMA_MOUTHS), like level 14 room 5 and
    level 15 room 9: the eight air cells 14-21 between their magma walls close
    one cell per side every 8 frames and open again, 64-frame cycle from room
    entry, measured frame by frame with the hero alive above the picture.
    This level draws its corridor magma on rows 62-98 (rows 60-61 black), so
    the watch's box for the closing magma is 37 rows from row 62.
  * TWO RAFTS (HL.RAFTS), in rooms 11 and 13, both waiting at the LEFT end
    (x 28): the level descends right, so the hero comes in from the left. The
    ROM keeps ONE raft x for them (RAM 40) and puts it back at the entry end
    whenever either room is entered; the engine carries one raft per ROOM
    (RAFT_IN) and one raft position, the same way.
  * ITS CREATURES RUN AT LEVEL 10'S SPEED: nine bats sweep 22 px on 92
    frames, everything that bobs bobs 7 px on 32; bats hold a wing pose 4
    frames, spiders 8. The seven hanging spiders are still. One wall snake
    stretches a pixel every 2 frames (32-frame cycle).
  * THE LIQUID IS GREEN, #328432, as the reference says - rows 136-141 of
    rooms 10-15 and nowhere else.
  * The old census had one entity (room 1's lantern), which the
    capture confirms; the capture has 34.

The shape of the level, room by room:

    rooms 0-9   GREY, magma in every corridor.
    room 1      a solid floor: left through its open RIGHT edge into room 2.
    rooms 7, 9  the breathing mouths, over a floor open from cell 2 (7) or 6
                (9) to cell 33 / 29.
    rooms 10-15 water from here to the end, entered sideways under a solid
                ceiling; the level descends RIGHT, every left edge leading
                back up.
    rooms 11, 13  a sixteen- and a twenty-cell magma wall over the water,
                crossed on the raft.
    room 15     the miner's room, the miner at x 128.
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

L = 16

# What the ROM draws, cell for cell, in descent order, verified against the
# reference before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "%%...........%%...................%%%%",
     "C": "####..##########....##########..######"},
    {"A": "####..##########....##########..######",
     "B": "%%............%%%%%%%%................",
     "C": "######################################"},
    {"A": "######################################",
     "B": "...............%%%%%%...............%%",
     "C": "######........................########"},
    {"A": "######........................########",
     "B": "%%%%%%%%%%%%............%%%%%%%%%%%%%%",
     "C": "##########................############"},
    {"A": "##########................############",
     "B": "%%....%%........%%%%..............%%%%",
     "C": "###..##########################..#####"},
    {"A": "###..##########################..#####",
     "B": "%%......%%.....%%%%%%.............%%%%",
     "C": "###########..............#############"},
    {"A": "###########..............#############",
     "B": "%%%%%%%%%%%%..%%%%%%%%..%%%%%%%%%%%%%%",
     "C": "##................................####"},
    {"A": "##................................####",
     "B": "%%%%%%%%%%%%%%........%%%%%%%%%%%%%%%%",
     "C": "##................................####"},
    {"A": "##................................####",
     "B": "%%%%%%%%%%..%%%%%..%%%%%..%%%%%%%%%%%%",
     "C": "##................................####"},
    {"A": "##................................####",
     "B": "%%%%%%%%%%%%%%........%%%%%%%%%%%%%%%%",
     "C": "######........................########"},
    {"A": "######........................########",
     "B": "%%..............%%%%..................",
     "C": "####~~~~~~~~~~~~~~~~~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": "..........%%%%%%%%%%%%%%%%............",
     "C": "####~~~~~~~~~~~~~~~~~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": ".................%%...................",
     "C": "#####~~~~~~~~~~~####~~~~~~~~~~~#######"},
    {"A": "######################################",
     "B": "........%%%%%%%%%%%%%%%%%%%%.....%%...",
     "C": "####~~~~~~~~~~~~~~~~~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": ".................%%...................",
     "C": "######~~~~~~~~~######~~~~~~~~~########"},
    {"A": "######################################",
     "B": "................%%%%................%%",
     "C": "##########~~~~~~~~~~~~~~~~############"},
]

# The live-hero ROM capture (the data hero_levels.py ships), as
# (room, what, x, y) with x the LEFT edge of the drawn box - for a bat, of
# its sweep. Every row.
CHARACTERS_MD = [
    (1, "lantern", 27, 35), (1, "spider_free", 136, 65),
    (2, "bat", 36, 64), (2, "bat", 48, 103),
    (3, "lantern", 123, 35), (3, "spider", 76, 110), (3, "spider", 84, 71),
    (4, "lantern", 107, 35), (4, "spider_free", 44, 65), (4, "snake", 132, 111),
    (5, "lantern", 23, 35), (5, "bat", 52, 103), (5, "spider_free", 56, 65),
    (6, "lantern", 103, 35), (6, "bat", 64, 103),
    (7, "lantern", 139, 35), (7, "spider", 96, 110),
    (8, "lantern", 139, 35), (8, "spider_free", 96, 105),
    (9, "lantern", 139, 35), (9, "spider_free", 96, 105),
    (10, "lantern", 123, 35), (10, "spider_free", 76, 105), (10, "bat", 108, 65),
    (11, "spider", 32, 72), (11, "spider", 92, 111),
    (12, "bat", 28, 103), (12, "bat", 108, 64),
    (13, "spider_free", 32, 65), (13, "spider", 76, 109),
    (14, "bat", 44, 64), (14, "bat", 92, 103),
    (15, "spider", 56, 70), (15, "miner", 128, 86),
]

KIND_NAME = {0: "spider", 1: "bat", 3: "snake", 4: "spider_free"}
WATER_ROOMS = set(range(10, 16))
LIQUID = "#328432"
MOUTH_ROOMS = (7, 9)
RAFT_ROOMS = (11, 13)

# The mouths, measured on the ROM frame by frame from arrival: cells of the
# 8-cell gap OPEN, e frames after the room was entered (e = 0 is the
# transition frame; the first frame recorded, e = 1, draws 4). The same
# sequence as level 14 room 5's and level 15 room 9's, in both rooms.
ROM_OPEN = "4" * 8 + "2" * 8 + "0" * 8 + "2" * 8 + "4" * 8 + "6" * 8 + "8" * 8 + "6" * 8


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


def shipped():
    """{(room, what, left x, top y)} for every creature SPIDERS carries."""
    return {(r, KIND_NAME[k], x - half, y)
            for r, x, y, half, k in HL.SPIDERS[L - 1]}


def of_kind(k):
    return [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == k]


def _state(env, room, **kw):
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    fields = dict(level=jnp.int32(L - 1), room=jnp.int32(room),
                  room_timer=jnp.int32(0), has_moved=jnp.bool_(True),
                  banner_timer=jnp.int32(0),
                  spider_alive=env.consts.SPIDER_VALID[L - 1])
    fields.update(kw)
    return state.replace(**fields)


# --- geometry ---------------------------------------------------------------
def test_level_16_is_sixteen_grey_rooms():
    common.check_shape(L, "grey", rooms=16)
    assert len(HL.BG_RLE_L16) == 16


def test_all_sixteen_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_the_level_is_complete_and_nothing_is_missing():
    """The old reference listed level 16 as 4-8 of 16 rooms. The walk reached
    all sixteen on 2026-09-25."""
    assert len(BANDS) == 16
    assert len({(b["A"], b["B"], b["C"]) for b in BANDS}) == 16, \
        "no ROOM is a copy of another"
    assert BANDS[7]["B"] == BANDS[9]["B"], "the two mouth rooms share a corridor"


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_where_the_level_goes_down_through_holes():
    """Room N's ceiling is drawn identically to room N-1's floor when N is
    entered through a hole: rooms 1 and 3-10. Rooms 2 and 11-15 are entered
    SIDEWAYS, under a ceiling that is solid across the whole screen."""
    for i in range(1, 16):
        if i == 2 or i >= 11:
            assert BANDS[i]["A"] == "#" * 38, f"room {i}"
        else:
            assert BANDS[i]["A"] == BANDS[i - 1]["C"].replace("~", "#"), \
                f"chain breaks between rooms {i - 1} and {i}"


def test_no_cell_was_left_uncalled():
    for i, room in enumerate(BANDS):
        for band, s in room.items():
            assert "?" not in s, f"room {i} band {band} has an uncalled cell"
            assert set(s) <= set("#%.~"), f"room {i} band {band} has a stray value"


# --- the water --------------------------------------------------------------
def test_the_liquid_cells_are_in_the_water_rooms_only():
    with_liquid = {i for i, r in enumerate(BANDS) if "~" in r["C"]}
    assert with_liquid == WATER_ROOMS


def test_no_room_from_10_on_has_a_hole_to_fall_through():
    for room in range(10, 16):
        assert "." not in BANDS[room]["C"], f"room {room} floor has a real hole"


def test_a_liquid_cell_is_solid_only_on_the_rows_it_is_drawn_on():
    y0, y1 = common.LIQUID_ROWS
    for room in WATER_ROOMS:
        liquid_x = {8 + 4 * i for i, c in enumerate(BANDS[room]["C"]) if c == "~"}
        for x, y, w, h in HL.WALL_RECTS_L16[room]:
            if x in liquid_x and y >= 99:
                assert (y, h) == (y0, y1 - y0 + 1), (
                    f"room {room}: the liquid rect at x {x} is {h} px tall "
                    f"from row {y}; it must be rows {y0}-{y1}")


def test_the_deadly_rects_are_the_water_line():
    assert HL.DEADLY[L - 1] == [(room, 8, 136, 152, 6) for room in sorted(WATER_ROOMS)]


def test_the_liquid_is_the_json_green():
    """The reference says #328432 and the ROM agrees: (50, 132, 50) on the
    water rows of rooms 10-15 and nowhere else."""
    palette, rooms = common.level_data(L)
    assert common.rgb(LIQUID) in palette
    for i, img in enumerate(rooms):
        ys, _xs = np.nonzero((img == np.array(common.rgb(LIQUID))).all(axis=-1))
        if i >= 10:
            assert ys.size and ys.min() >= 136, f"room {i}"
        else:
            assert not ys.size, f"room {i} paints the liquid colour"


def test_no_rotor_yellow_is_painted_into_the_cave():
    """The yellow bars on the water of rooms 11 and 13 are the RAFTS, drawn by
    the engine where they currently are; they are not in any background."""
    _palette, rooms = common.level_data(L)
    rotor = np.array(common.rgb("#e8e84a"))
    for i, img in enumerate(rooms):
        ys, xs = np.nonzero((img == rotor).all(axis=-1))
        assert not ys.size, f"room {i} paints rotor yellow at {xs[0]},{ys[0]}"


# --- the two rafts ----------------------------------------------------------
def test_rooms_11_and_13_are_crossed_on_a_raft():
    """A magma wall under a solid ceiling, over water, in each. Both rafts
    wait at the LEFT end: the level descends right, so he comes in from the
    left."""
    assert HL.RAFTS[L - 1] == [(11, 28), (13, 28)]
    assert (10, 25) in runs_of(BANDS[11]["B"], "%")
    assert (8, 27) in runs_of(BANDS[13]["B"], "%")
    for room in RAFT_ROOMS:
        assert BANDS[room]["A"] == "#" * 38
        assert BANDS[room]["C"][4:32] == "~" * 28


def test_the_engine_floats_a_raft_in_both_rooms_and_nowhere_else(env):
    rafts = np.asarray(env.consts.RAFT_IN[L - 1])
    assert set(np.nonzero(rafts)[0]) == set(RAFT_ROOMS)


@pytest.mark.parametrize("room", RAFT_ROOMS)
def test_each_raft_carries_him_right(env, room):
    """Measured on the ROM (2026-09-25) in both rooms: he lands at x 29 on
    the raft at x 28 and it carries him 1 px a frame to the right."""
    import jax.numpy as jnp
    c = env.consts
    s = _state(env, room, raft_x=jnp.int32(28), raft_dir=jnp.int32(1),
               player_x=jnp.int32(28 + c.raft_ride_dx),
               player_y=jnp.int32(c.raft_y - c.player_height - 6),
               spider_alive=jnp.zeros_like(env.consts.SPIDER_VALID[L - 1]))
    for _ in range(10):
        _obs, s, *_ = env.step(s, 0)
    assert int(s.player_y) == c.raft_y - c.player_height
    x0 = int(s.raft_x)
    for k in range(1, 31):
        _obs, s, *_ = env.step(s, 0)
        assert int(s.raft_x) == x0 + k
        assert int(s.player_x) == int(s.raft_x) + c.raft_ride_dx
    assert int(s.lives) == c.starting_lives


def test_entering_room_13_puts_the_raft_back_at_its_left_end(env):
    """The ROM's one raft x (RAM 40) is reset on entry to a raft room: poked
    to 76 in room 12, it read 28 on arrival in room 13. The engine's one
    raft_x left mid-way by room 11 is reset the same way."""
    import jax.numpy as jnp
    c = env.consts
    x = c.screen_width - 8 - c.player_width
    s = _state(env, 12, raft_x=jnp.int32(76), raft_dir=jnp.int32(-1),
               player_x=jnp.int32(x), player_y=jnp.int32(70),
               spider_alive=jnp.zeros_like(env.consts.SPIDER_VALID[L - 1]))
    _obs, s, *_ = env.step(s, 3)                      # RIGHT, off the right edge
    assert int(s.room) == 13
    assert int(s.raft_x) == 28 and int(s.raft_dir) == 1


def test_the_raft_is_drawn_in_its_rooms_only(env):
    import jax.numpy as jnp
    yellow = np.array(HL.RAFT_COLOUR)
    for room in (10, 11, 12, 13, 14):
        s = _state(env, room, raft_x=jnp.int32(28), player_y=jnp.int32(-40))
        frame = np.asarray(env.render(s))
        bar = (frame[136:138, 28:36] == yellow).all(axis=-1)
        assert bar.all() == (room in RAFT_ROOMS), f"room {room}"


# --- magma ------------------------------------------------------------------
def test_every_room_has_magma_and_no_corridor_rock():
    """Magma is a property of the ROOM: in a magma room every solid corridor
    cell is magma. Every room of level 16 is a magma room."""
    for i, room in enumerate(BANDS):
        assert "%" in room["B"], f"room {i}"
        assert "#" not in room["B"], f"room {i}: a rock cell in a magma corridor"


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


def test_magma_never_leaves_the_corridor_band():
    for _room, _x, y, _w, h in HL.MAGMA[L - 1]:
        assert (y, h) == (60, 39), "magma is a corridor register, not a band"


def test_no_magma_is_carried_as_a_creature():
    assert not any(row[4] == 2 for row in HL.SPIDERS[L - 1])


def test_nothing_flares():
    assert HL.FLARES[L - 1] == []


# --- the magma mouths -------------------------------------------------------
def test_rooms_7_and_9_are_the_levels_mouths():
    """The eight air cells 14-21 between their two magma walls. Room 6's
    eight-cell magma block at cells 14-21 and every other gap stand still on
    the ROM."""
    assert HL.MAGMA_MOUTHS[L - 1] == [(7, 64, 32, 8, 16), (9, 64, 32, 8, 16)]
    for room in MOUTH_ROOMS:
        band = BANDS[room]["B"]
        assert runs_of(band, ".") == [(14, 21)]
        assert band[13] == band[22] == "%"
        assert "." in BANDS[room]["C"][14:22], "the way down is under it"
    assert cells(14, 21) == (64, 32)


def test_the_mouth_cycle_is_the_roms():
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _mouth_closed
    c = JaxHero().consts
    for m in range(2):
        got = ""
        for e in range(128):
            closed = int(_mouth_closed(c, jnp.int32(L - 1), jnp.int32(e))[m])
            got += str(8 - 2 * closed)
        assert got == ROM_OPEN * 2, f"mouth {m}"


def _corridor(frame):
    row = np.asarray(frame)[80]
    magma = {(167, 26, 26), (184, 50, 50)}
    return "".join("%" if tuple(int(v) for v in row[9 + 4 * i]) in magma
                   else ("#" if row[9 + 4 * i].sum() else ".") for i in range(38))


@pytest.mark.parametrize("room", MOUTH_ROOMS)
def test_the_engine_draws_the_mouth_in_magma(env, room):
    import jax.numpy as jnp
    state = _state(env, room, player_x=jnp.int32(30), player_y=jnp.int32(0))
    for e in range(0, 64, 4):
        band = _corridor(env.render(state.replace(room_timer=jnp.int32(e))))
        gap = band[14:22]
        n = int(ROM_OPEN[e])
        closed = (8 - n) // 2
        assert gap == "%" * closed + "." * n + "%" * closed, f"e {e}: {gap}"
        assert band[:14] == "%" * 14 and band[22:] == "%" * 16
    shut = env.render(state.replace(room_timer=jnp.int32(16), mouth_open=jnp.bool_(True)))
    assert _corridor(shut)[14:22] == "." * 8


def test_the_mouth_burns_and_then_stays_open_for_the_visit(env):
    import jax.numpy as jnp
    state = _state(env, 9, player_x=jnp.int32(77), player_y=jnp.int32(70))
    lives = int(state.lives)
    for _ in range(40):
        state = state.replace(player_x=jnp.int32(77), player_y=jnp.int32(70),
                              player_vy=jnp.float32(0))
        _obs, state, *_ = env.step(state, 0)
        if int(state.lives) < lives:
            break
    assert int(state.lives) == lives - 1 and int(state.room_timer) == 16
    assert int(state.room) == 9 and bool(state.mouth_open)


@pytest.mark.parametrize("room", MOUTH_ROOMS)
def test_a_mouth_room_is_passed_by_waiting_above_it(env, room):
    """Falling straight in puts him in the gap as it shuts; hovering in the
    open ceiling until it begins to open and then dropping takes him through
    the floor into the next room."""
    import jax.numpy as jnp
    assert BANDS[room]["A"][14:22] == "." * 8

    def attempt(hover_until):
        state = _state(env, room, player_x=jnp.int32(77), player_y=jnp.int32(2),
                       player_vy=jnp.float32(2.0))
        lives = int(state.lives)
        for _ in range(200):
            waiting = int(state.room_timer) < hover_until
            act = (2 if int(state.player_y) > 20 else 0) if waiting else 5
            _obs, state, *_ = env.step(state, act)
            if int(state.lives) < lives:
                return "died"
            if int(state.room) == room + 1:
                return "through"
        return "stuck"

    assert attempt(0) == "died"
    assert attempt(24) == "through"


# --- dynamite ---------------------------------------------------------------
def test_the_blastable_pillars_are_the_two_cell_ones():
    """Only a run of exactly two cells breaks, never one that reaches the side
    of the screen - magma the same as rock."""
    want = []
    for i, room in enumerate(BANDS):
        for first, last in runs_of(room["B"], "#") + runs_of(room["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            want.append((i, first, last))
    got = {(r, (x - 8) // 4, (x - 8) // 4 + w // 4 - 1)
           for r, x, _y, w, _h, _n in HL.DESTRUCTIBLE[L - 1]}
    assert got == set(want)
    assert len(want) == 6


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    for room, x, y, _w, h, _n in HL.DESTRUCTIBLE[L - 1]:
        first = (x - 8) // 4
        same = (first, first + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if same else (60, 39)), f"room {room} at x {x}"
        assert same == (room == 0)


def test_the_shared_wall_table_is_empty():
    common.check_shared_walls(L)


# --- the way down -----------------------------------------------------------
def test_the_side_exits_are_the_open_corridor_edges():
    want = set()
    for i, room in enumerate(BANDS):
        if room["B"][0] == ".":
            want.add((i, -1))
        if room["B"][37] == ".":
            want.add((i, 1))
    assert {(r, s) for r, s, _d in HL.SIDE_EXITS[L - 1]} == want


def test_level_16_descends_right_through_room_1_and_from_room_10():
    """A side exit's direction is DATA. Room 1's floor is solid: its RIGHT
    edge goes down into room 2, whose left edge leads back up. From room 10
    the level goes on through RIGHT edges, every left edge leading back."""
    by_room = {}
    for room, side, delta in HL.SIDE_EXITS[L - 1]:
        by_room.setdefault(room, {})[side] = delta
    assert set(by_room) == {1, 2} | set(range(10, 16))
    assert by_room[1] == {1: 1} and by_room[2] == {-1: -1}
    assert by_room[10] == {1: 1}
    for room in range(11, 15):
        assert by_room[room] == {-1: -1, 1: 1}, f"room {room}"
    assert by_room[15] == {-1: -1}, "the last room leads nowhere but back"


def test_every_room_but_the_last_has_a_way_on():
    for i, room in enumerate(BANDS[:-1]):
        down = "." in room["C"]
        side = any(r == i and d == 1 for r, _s, d in HL.SIDE_EXITS[L - 1])
        assert down or side, f"room {i} has no way on"


# --- entities ---------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)


def test_every_entity_in_the_live_capture_is_present():
    """Every lantern, every creature at its kind, x and y, and the miner -
    and not one creature more."""
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    want_lanterns = {(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "lantern"}
    assert lanterns == want_lanterns
    want = {(r, w, x, y) for r, w, x, y in CHARACTERS_MD if w not in ("lantern", "miner")}
    assert shipped() == want
    assert len(HL.SPIDERS[L - 1]) == 24
    (miner,) = [(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "miner"]
    assert HL.MINER_POS[L - 1] == miner


def test_the_census_lantern_is_where_it_said():
    """The old census had one row for level 16: room 1's lantern
    at (27, 35)."""
    assert (1, 27, 35) in HL.LANTERNS[L - 1]


def test_nothing_was_invented_in_room_0():
    assert not any(r == 0 for r, *_ in HL.SPIDERS[L - 1])
    assert not any(r == 0 for r, *_ in HL.LANTERNS[L - 1])


def test_the_lanterns_hang_in_the_ceiling_band_on_row_35():
    """Rooms 1 and 3-10; room 2 and the sideways rooms 11-15 have none."""
    assert len(HL.LANTERNS[L - 1]) == 9
    assert {r for r, *_ in HL.LANTERNS[L - 1]} == {1} | set(range(3, 11))
    for room, x, y in HL.LANTERNS[L - 1]:
        assert y == 35, "every lantern in the game hangs on row 35"
        assert BANDS[room]["A"][(x - 8) // 4] == ".", f"room {room}: in air"


def test_the_miner_is_in_the_last_room():
    common.check_miner(L, BANDS)
    assert HL.MINER_POS[L - 1] == (15, 128, 86)


def test_the_nine_bats_patrol_22_px_on_92_frames_and_hold_a_pose_4():
    bats = of_kind(1)
    assert [c[0] for _i, c in bats] == [2, 2, 5, 6, 10, 12, 12, 14, 14]
    for slot, (_room, _x, _y, half, _k) in bats:
        assert 2 * half == 22
        assert 2 * HL.CREATURE_PATROL[(L, slot)] == 92
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 32, 4)


def test_the_untethered_spiders_bob_7_px_on_32_frames():
    free = of_kind(4)
    assert [c[0] for _i, c in free] == [1, 4, 5, 8, 9, 10, 13]
    for slot, (_room, _x, _y, half, _k) in free:
        assert half == 0, "it bobs; it does not patrol"
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 32, 8)


def test_the_hanging_spiders_are_still():
    """Whether a creature moves is a property of the room. Level 16's seven
    hanging spiders are all still: no patrol, no bob, two poses on an 8-frame
    hold."""
    hanging = of_kind(0)
    assert [(c[0], c[1], c[2]) for _i, c in hanging] == [
        (3, 76, 110), (3, 84, 71), (7, 96, 110), (11, 32, 72), (11, 92, 111),
        (13, 76, 109), (15, 56, 70)]
    for slot, (_room, _x, _y, half, _k) in hanging:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 8)
        assert (L, slot) not in HL.CREATURE_SPRITES, "both poses are drawn"


def test_the_snake_grows_out_of_the_rock():
    """Room 4's floor snake, anchored in the rock cell on its left, stretches
    a pixel every 2 frames (timed on the ROM: 0,0,1,1,...,7,7,7,7,...,0,0)."""
    snakes = of_kind(3)
    assert [(c[0], c[1], c[2]) for _i, c in snakes] == [(4, 132, 111)]
    for slot, (room, x, y, half, _k) in snakes:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 2), "a pixel every 2 frames"
        band = BANDS[room]["C"]
        assert band[(x - 8) // 4 - 1] == "#" and band[(x - 8) // 4] == "."


def test_the_engine_reads_the_fast_snake_rate(env):
    c = env.consts
    for slot, _row in of_kind(3):
        assert int(c.SPIDER_HOLD[L - 1, slot]) == 2


def test_exactly_the_bats_and_the_untethered_spiders_move():
    movers = {i for i, c in enumerate(HL.SPIDERS[L - 1])
              if c[3] or HL.CREATURE_MOTION[(L, i)][0]}
    assert movers == {i for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] in (1, 4)}
    assert len(movers) == 16


def test_the_engine_draws_the_bats_on_the_rom_clock(env):
    """The engine's creature positions over 184 frames sweep 22 px and repeat
    every 92 frames, and the bob repeats every 32 - room 2's corridor bat."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((2, 47, 64, 11, 1))
    xs, ys = [], []
    for t in range(0, 184):
        x, y = _creature_pos(c, jnp.int32(L - 1), jnp.int32(t))
        xs.append(int(x[slot])); ys.append(int(y[slot]))
    assert max(xs) - min(xs) == 22 and max(ys) - min(ys) == 7
    assert xs[:92] == xs[92:184], "the sweep is a 92-frame cycle"
    assert ys[:32] == ys[32:64] == ys[64:96], "the bob is a 32-frame cycle"


# --- rendering --------------------------------------------------------------
def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black."""
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    state = state.replace(level=jnp.int32(L - 1), room=jnp.int32(9))
    frame = np.asarray(env.render(state))
    assert frame[189:210].max() == 0, "something is drawn where the logo was"


def test_room_0_paints_the_levels_own_grey():
    """Room 0 is recoloured from the ROM's brown boot palette to the level's
    grey ramp."""
    _palette, rooms = common.level_data(L)
    for role in ("dark", "mid", "light"):
        r, g, b = common.rgb(HL.SHADES[L][role])
        assert (rooms[0] == np.array([r, g, b])).all(axis=-1).any(), (
            f"room 0 never paints its {role}")
    brown = common.rgb(HL.SHADES[1]["mid"])
    assert not (rooms[0] == np.array(brown)).all(axis=-1).any()
