"""Level 18, against the corrected ROM reference.

The block in hero_levels.py was generated by walking the level through the
game's own room-transition code, capturing each room off the real ROM and
refusing to emit anything unless the capture agreed with the reference cell
for cell. These tests re-check that agreement from the committed data alone
(no ale-py), and check the engine draws it.

What came out of level 18:

  * THE WALK REACHES ALL SIXTEEN ROOMS. The reference had seven, and room 6
    of those was read off the playthrough and was wrong in two bands: its
    corridor is open at the LEFT edge with MAGMA at the right (the file had
    rock on the left and a '?'), and its floor has a pillar at cells 15-20
    (the file had one long hole). The reference now holds the ROM walk for
    all sixteen.
  * THE OLD BLOCK WAS A PLACEHOLDER copy of level 14. Every table is new.
  * ITS CREATURES RUN TWICE AS FAST AS LEVEL 17'S: eleven bats sweep 22 px on
    46 frames and bob 7 px on 16; the five untethered spiders bob 7 px on 16.
    Bats hold a wing pose 4 frames, spiders 8 - so an untethered spider's
    pose is LOCKED to its direction (legs gathered all the way down, legs up
    all the way back; measured on the ROM 2026-09-26). The six hanging
    spiders are still.
  * TWO WALL SNAKES STRETCH A PIXEL EVERY FRAME, a 16-frame cycle (level 14's
    ran 32, level 4's 64): 0 0 1 2 3 4 5 6 7 7 6 5 4 3 2 1, measured.
  * ROOM 11 HAS THE GAME'S SECOND WATER TENTACLE (kind 5), pursuit range
    29-121 over the liquid at x 28-131, chased to both clamps on the ROM.
  * ROOM 8 BREATHES MAGMA (HL.MAGMA_MOUTHS), the eight air cells 14-21, the
    same cycle as every other mouth.
  * ONE RAFT (HL.RAFTS), room 12, at the LEFT end (x 28): the level descends
    RIGHT, so the hero comes in from the left.
  * THE LIQUID IS MAGENTA, #a8308f, as the reference says - on the water
    rows of rooms 11-15, and on the bottom trim rows 139-141 of room 10,
    under a floor that is solid across the whole screen (unreachable).
  * EIGHT CREATURES WERE 1-2 ROWS LOW in the first capture (rooms 2, 3, 5,
    12 and 14), read with the hero parked above the picture, where the ROM
    draws them lower. The generator now re-reads every bat, hanging spider and
    snake with the hero in the room: room 12's
    floor spider hangs from row 109, not 111 (measured 2026-09-26).
  * The old census had 7 entities in 6 rooms; the capture has 35 (25
    creatures, 9 lanterns, the miner). Its two "still bats" at y 110 are
    untethered spiders seen at the bottom of their bob.

The shape of the level, room by room:

    rooms 0-10  GREEN; magma in every corridor.
    room 5      a solid floor: left through its open RIGHT edge into room 6,
                whose left edge leads back up.
    room 8      the breathing mouth over the way down.
    room 10     a solid floor: left through its open RIGHT edge.
    rooms 11-15 water from here to the end; the level descends RIGHT, every
                left edge leading back up.
    room 11     the tentacle, under a rock wall and a rock pillar.
    room 12     a sixteen-cell magma wall over the water, crossed on the raft.
    room 14     no wall at all in the corridor.
    room 15     the miner's room, the miner at x 128.
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

L = 18

# What the ROM draws, cell for cell, in descent order, verified against the
# reference before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "%%...........%%...................%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%....................%%..........%%%%",
     "C": "####..##..################..##..######"},
    {"A": "####..##..################..##..######",
     "B": "%%.....%%%%%%%%%%%%%%%%%%%%%%.....%%%%",
     "C": "#####.....################.....#######"},
    {"A": "#####.....################.....#######",
     "B": "%%....................%%..........%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%......................%%........%%%%",
     "C": "####..########################..######"},
    {"A": "####..########################..######",
     "B": "%%....................................",
     "C": "######################################"},
    {"A": "######################################",
     "B": "....................................%%",
     "C": "######.........######.........########"},
    {"A": "######.........######.........########",
     "B": "%%%%%%%%%%................%%%%%%%%%%%%",
     "C": "#################..###################"},
    {"A": "#################..###################",
     "B": "%%%%%%%%%%%%%%........%%%%%%%%%%%%%%%%",
     "C": "#################..###################"},
    {"A": "#################..###################",
     "B": "%%..........%%%......%%%..........%%%%",
     "C": "###..#####..#####..#####..#####..#####"},
    {"A": "###..#####..#####..#####..#####..#####",
     "B": "%%....%%%..................%%%........",
     "C": "######################################"},
    {"A": "######################################",
     "B": "..........################......##....",
     "C": "#####~~~~~~~~~~~~~~~~~~~~~~~~~~#######"},
    {"A": "######################################",
     "B": "..........%%%%%%%%%%%%%%%%............",
     "C": "####~~~~~~~~~~~~~~~~~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": ".................%%...................",
     "C": "#####~~~~~~~~~~~####~~~~~~~~~~~#######"},
    {"A": "######################################",
     "B": "......................................",
     "C": "##########~~~~~~~~~~~~~~~~############"},
    {"A": "######################################",
     "B": "................%%%%................%%",
     "C": "########~~~~~~~~~~~~~~~~~~~~##########"},
]

# The live-hero ROM capture (the data hero_levels.py ships), as
# (room, what, x, y) with x the LEFT edge of the drawn box - for a bat, of
# its sweep; for the tentacle, of its pursuit range. Every row.
CHARACTERS_MD = [
    (1, "lantern", 83, 35), (1, "spider_free", 24, 104), (1, "bat", 48, 64),
    (2, "lantern", 131, 35), (2, "snake", 112, 111), (2, "spider", 136, 70),
    (3, "lantern", 127, 35), (3, "bat", 44, 64), (3, "spider_free", 80, 105),
    (4, "lantern", 83, 35), (4, "snake", 24, 111), (4, "bat", 44, 64),
    (5, "lantern", 131, 35), (5, "bat", 104, 64),
    (6, "bat", 36, 64), (6, "bat", 36, 103),
    (7, "lantern", 63, 35), (7, "spider_free", 76, 65),
    (8, "lantern", 79, 35),
    (9, "lantern", 79, 35), (9, "spider_free", 48, 104), (9, "bat", 112, 64),
    (10, "lantern", 79, 35), (10, "bat", 84, 64),
    (11, "tentacle", 29, 126), (11, "spider", 36, 70), (11, "bat", 92, 103),
    (12, "spider", 32, 70), (12, "spider", 76, 109),
    (13, "spider_free", 52, 104), (13, "spider", 96, 70),
    (14, "bat", 68, 103), (14, "spider", 136, 70),
    (15, "bat", 40, 64), (15, "miner", 128, 86),
]

KIND_NAME = {0: "spider", 1: "bat", 3: "snake", 4: "spider_free", 5: "tentacle"}
WATER_ROOMS = set(range(11, 16))
ROCK_CORRIDORS = {11}
OPEN_CORRIDORS = {14}                  # no wall of either kind
LIQUID = "#a8308f"
TENTACLE_BLUE = (101, 183, 217)
TENTACLE_ROOM = 11

# The mouth, measured on the ROM frame by frame from arrival: cells of the
# 8-cell gap OPEN, e frames after the room was entered (e = 0 is the
# transition frame). The same sequence as every other mouth in the game.
ROM_OPEN = "4" * 8 + "2" * 8 + "0" * 8 + "2" * 8 + "4" * 8 + "6" * 8 + "8" * 8 + "6" * 8
# Room 2's snake, px out of the rock per frame on the ROM (from arrival).
ROM_SNAKE = [0, 1, 2, 3, 4, 5, 6, 7, 7, 6, 5, 4, 3, 2, 1, 0]
# Room 1's untethered spider on the ROM, per frame over one 16-frame cycle:
# (position, pose), the position being the top row less pose 1's 2-row drop
# (jax_hero._SPIDER_FREE_ART2). Pose 1 all the way down, pose 0 all the way
# back up.
ROM_FREE = ([(104, 1), (104, 1)] + [(y, 1) for y in range(105, 111)]
            + [(111, 0), (111, 0)] + [(y, 0) for y in range(110, 104, -1)])


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


def shipped():
    """{(room, what, left x, top y)} for every creature SPIDERS carries."""
    return {(r, KIND_NAME[k], x - half, y)
            for r, x, y, half, k in HL.SPIDERS[L - 1]}


def of_kind(k):
    return [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == k]


def _state(env, room, **kw):
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    fields = dict(level=jnp.int32(L - 1), room=jnp.int32(room),
                  room_timer=jnp.int32(0), has_moved=jnp.bool_(True),
                  banner_timer=jnp.int32(0),
                  spider_alive=env.consts.SPIDER_VALID[L - 1])
    fields.update(kw)
    return state.replace(**fields)


def _tentacle_slot():
    (slot, _row), = of_kind(5)
    return slot


# --- geometry ---------------------------------------------------------------
def test_level_18_is_sixteen_green_rooms():
    common.check_shape(L, "green", rooms=16)
    assert len(HL.BG_RLE_L18) == 16


def test_all_sixteen_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_the_level_is_complete_and_nothing_is_missing():
    """The old reference listed level 18 as 7 of 16 rooms. The walk reached
    all sixteen on 2026-09-26."""
    assert len(BANDS) == 16
    assert len({(b["A"], b["B"], b["C"]) for b in BANDS}) == 16, \
        "no ROOM is a copy of another"


def test_room_6_is_the_roms_not_the_videos():
    """The file's room 6 came off the playthrough; the ROM draws an open left
    edge with magma at the right, and a pillar in the floor."""
    assert BANDS[6]["B"] == "....................................%%"
    assert BANDS[6]["C"] == "######.........######.........########"


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_every_ceiling_is_the_floor_above_it():
    """Rooms 1-5 and 7-10 are entered through a hole; rooms 6 and 11-15
    sideways, under a ceiling that is solid across the screen - and the room
    before each of those has a floor solid across the screen too, so the
    chain holds for every room."""
    for i in range(1, 16):
        assert BANDS[i]["A"] == BANDS[i - 1]["C"].replace("~", "#"), \
            f"chain breaks between rooms {i - 1} and {i}"
    for i in (6, 11, 12, 13, 14, 15):
        assert BANDS[i]["A"] == "#" * 38, f"room {i}"


def test_no_cell_was_left_uncalled():
    for i, room in enumerate(BANDS):
        for band, s in room.items():
            assert "?" not in s, f"room {i} band {band} has an uncalled cell"
            assert set(s) <= set("#%.~"), f"room {i} band {band} has a stray value"


# --- the water --------------------------------------------------------------
def test_the_liquid_cells_are_in_the_water_rooms_only():
    with_liquid = {i for i, r in enumerate(BANDS) if "~" in r["C"]}
    assert with_liquid == WATER_ROOMS


def test_no_room_from_10_on_has_a_hole_to_fall_through():
    for room in range(10, 16):
        assert "." not in BANDS[room]["C"], f"room {room} floor has a real hole"


def test_a_liquid_cell_is_solid_only_on_the_rows_it_is_drawn_on():
    y0, y1 = common.LIQUID_ROWS
    for room in WATER_ROOMS:
        liquid_x = {8 + 4 * i for i, c in enumerate(BANDS[room]["C"]) if c == "~"}
        for x, y, w, h in HL.WALL_RECTS_L18[room]:
            if x in liquid_x and y >= 99:
                assert (y, h) == (y0, y1 - y0 + 1), (
                    f"room {room}: the liquid rect at x {x} is {h} px tall "
                    f"from row {y}; it must be rows {y0}-{y1}")


def test_the_deadly_rects_are_the_water_line():
    """Rows 136-141 of the water rooms; room 10 paints the colour only on
    its bottom trim rows 139-141, under a floor solid from edge to edge."""
    assert HL.DEADLY[L - 1] == [(10, 8, 139, 152, 3)] + [
        (room, 8, 136, 152, 6) for room in sorted(WATER_ROOMS)]
    assert BANDS[10]["C"] == "#" * 38, "nothing can reach room 10's"


def test_the_liquid_is_the_json_magenta():
    """The reference says #a8308f and the ROM agrees: (168, 48, 143) in the
    floor trim of rooms 10-15 and nowhere else."""
    palette, rooms = common.level_data(L)
    assert common.rgb(LIQUID) in palette
    for i, img in enumerate(rooms):
        ys, _xs = np.nonzero((img == np.array(common.rgb(LIQUID))).all(axis=-1))
        if i >= 10:
            assert ys.size and ys.min() >= (139 if i == 10 else 136), f"room {i}"
        else:
            assert not ys.size, f"room {i} paints the liquid colour"


def test_no_creature_is_painted_into_the_cave():
    """The raft's yellow and the tentacle's blue are drawn by the engine; the
    generator takes the tentacle's feet out of room 11's water."""
    palette, rooms = common.level_data(L)
    assert TENTACLE_BLUE not in [tuple(p) for p in palette]
    rotor = np.array(common.rgb("#e8e84a"))
    for i, img in enumerate(rooms):
        for colour in (rotor, np.array(TENTACLE_BLUE)):
            ys, xs = np.nonzero((img == colour).all(axis=-1))
            assert not ys.size, f"room {i} paints {colour} at {xs[0]},{ys[0]}"


# --- the raft ---------------------------------------------------------------
def test_room_12_is_crossed_on_a_raft_from_the_left():
    assert HL.RAFTS[L - 1] == [(12, 28)]
    assert (10, 25) in runs_of(BANDS[12]["B"], "%")
    assert BANDS[12]["A"] == "#" * 38
    assert BANDS[12]["C"][4:32] == "~" * 28


def test_the_engine_floats_the_raft_in_room_12_only(env):
    rafts = np.asarray(env.consts.RAFT_IN[L - 1])
    assert set(np.nonzero(rafts)[0]) == {12}


# --- magma ------------------------------------------------------------------
def test_magma_is_a_property_of_the_room():
    """In a magma room every solid corridor cell is magma; in the others
    every one is rock. Room 14's corridor has no wall at all."""
    for i, room in enumerate(BANDS):
        if i in ROCK_CORRIDORS:
            assert "%" not in room["B"] and "#" in room["B"], f"room {i}"
        elif i in OPEN_CORRIDORS:
            assert set(room["B"]) == {"."}, f"room {i}"
        else:
            assert "%" in room["B"] and "#" not in room["B"], f"room {i}"


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


def test_magma_never_leaves_the_corridor_band():
    for _room, _x, y, _w, h in HL.MAGMA[L - 1]:
        assert (y, h) == (60, 39), "magma is a corridor register, not a band"


def test_no_magma_is_carried_as_a_creature():
    assert not any(row[4] == 2 for row in HL.SPIDERS[L - 1])


def test_nothing_flares():
    assert HL.FLARES[L - 1] == []


# --- the magma mouth --------------------------------------------------------
def test_room_8_is_the_levels_mouth():
    assert HL.MAGMA_MOUTHS[L - 1] == [(8, 64, 32, 8, 16)]
    band = BANDS[8]["B"]
    assert runs_of(band, ".") == [(14, 21)]
    assert band[13] == band[22] == "%"
    assert cells(14, 21) == (64, 32)
    assert "." in BANDS[8]["C"][14:22], "the way down is under it"
    assert "." in BANDS[8]["A"][14:22], "and the way in is over it"


def test_the_mouth_cycle_is_the_roms():
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _mouth_closed
    c = JaxHero().consts
    got = ""
    for e in range(128):
        closed = int(_mouth_closed(c, jnp.int32(L - 1), jnp.int32(e))[0])
        got += str(8 - 2 * closed)
    assert got == ROM_OPEN * 2


# --- the water tentacle -----------------------------------------------------
def test_room_11_holds_the_one_tentacle():
    slot = _tentacle_slot()
    assert HL.SPIDERS[L - 1][slot] == (11, 29, 126, 0, 5)
    assert {k: v for k, v in HL.CREATURE_TRACK.items() if k[0] == L} == {
        (L, slot): (29, 121)}
    assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 8)
    assert (L, slot) not in HL.CREATURE_PATROL
    floor = BANDS[TENTACLE_ROOM]["C"]
    assert set(floor[5:31]) == {"~"}, "it swims over liquid at x 28-131"


def test_the_tentacle_starts_at_the_heros_entry_x_clamped(env):
    """The level descends RIGHT: in by room 10's open right edge he appears
    on the LEFT of room 11 and the tentacle at its left clamp, 29; back up by
    room 12's left edge he appears on the right and it waits at 121."""
    import jax.numpy as jnp
    slot = _tentacle_slot()
    c = env.consts
    none = jnp.zeros_like(c.SPIDER_VALID[L - 1])
    s = _state(env, 10, player_x=jnp.int32(c.screen_width - 8 - c.player_width),
               player_y=jnp.int32(70), spider_alive=none)
    _obs, s, *_ = env.step(s, 3)                       # RIGHT, off the edge
    assert int(s.room) == 11 and int(s.tentacle_x[slot]) == 29
    s = _state(env, 12, player_x=jnp.int32(8), player_y=jnp.int32(70),
               spider_alive=none)
    _obs, s, *_ = env.step(s, 4)                       # LEFT, off the edge
    assert int(s.room) == 11 and int(s.tentacle_x[slot]) == 121


def test_the_engine_draws_the_tentacle_where_it_has_followed_him(env):
    import jax.numpy as jnp
    slot = _tentacle_slot()
    for x in (29, 77, 121):
        s = _state(env, TENTACLE_ROOM, player_x=jnp.int32(16),
                   player_y=jnp.int32(70), room_timer=jnp.int32(36),
                   tentacle_x=jnp.zeros_like(env.consts.SPIDER_VALID[L - 1],
                                             dtype=jnp.int32).at[slot].set(x))
        frame = np.asarray(env.render(s))
        ys, xs = np.nonzero((frame == np.array(TENTACLE_BLUE)).all(axis=-1))
        assert xs.min() == x and ys.max() == 137, x


def test_dynamite_beside_it_takes_the_pillar_and_not_the_tentacle(env):
    """Room 11's rock pillar at cells 32-33 (x 136-143), a stick planted on
    the floor right of it with the tentacle waiting at its right clamp."""
    import jax.numpy as jnp
    slot = _tentacle_slot()
    c = env.consts
    assert runs_of(BANDS[TENTACLE_ROOM]["B"], "#")[-1] == (32, 33)
    s = _state(env, TENTACLE_ROOM, player_x=jnp.int32(144),
               player_y=jnp.int32(99 - c.player_height), room_timer=jnp.int32(200),
               tentacle_x=jnp.zeros_like(c.SPIDER_VALID[L - 1],
                                         dtype=jnp.int32).at[slot].set(121))
    s = s.replace(spider_alive=s.spider_alive & (jnp.arange(c.num_spiders) == slot))
    score = int(s.score)
    _obs, s, *_ = env.step(s, 5)                      # DOWN: plant
    assert bool(s.dyn_active)
    for _ in range(120):
        _obs, s, *_ = env.step(s, 0)
    assert int(s.score) - score == c.wall_points, "the pillar, and nothing else"
    assert bool(s.spider_alive[slot]), "the tentacle survives the blast"


# --- dynamite ---------------------------------------------------------------
def test_the_blastable_pillars_are_the_two_cell_ones():
    want = []
    for i, room in enumerate(BANDS):
        for first, last in runs_of(room["B"], "#") + runs_of(room["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            want.append((i, first, last))
    got = {(r, (x - 8) // 4, (x - 8) // 4 + w // 4 - 1)
           for r, x, _y, w, _h, _n in HL.DESTRUCTIBLE[L - 1]}
    assert got == set(want)
    assert len(want) == 6


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    for room, x, y, _w, h, _n in HL.DESTRUCTIBLE[L - 1]:
        first = (x - 8) // 4
        same = (first, first + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if same else (60, 39)), f"room {room} at x {x}"
        assert same == (room == 0)


def test_the_shared_wall_table_is_empty():
    common.check_shared_walls(L)


# --- the way down -----------------------------------------------------------
def test_the_side_exits_are_the_open_corridor_edges():
    want = set()
    for i, room in enumerate(BANDS):
        if room["B"][0] == ".":
            want.add((i, -1))
        if room["B"][37] == ".":
            want.add((i, 1))
    assert {(r, s) for r, s, _d in HL.SIDE_EXITS[L - 1]} == want


def test_level_18_descends_right_through_room_5_and_from_room_10():
    by_room = {}
    for room, side, delta in HL.SIDE_EXITS[L - 1]:
        by_room.setdefault(room, {})[side] = delta
    assert set(by_room) == {5, 6} | set(range(10, 16))
    assert by_room[5] == {1: 1} and by_room[6] == {-1: -1}
    assert by_room[10] == {1: 1}
    for room in range(11, 15):
        assert by_room[room] == {1: 1, -1: -1}, f"room {room}"
    assert by_room[15] == {-1: -1}, "the last room leads nowhere but back"


def test_every_room_but_the_last_has_a_way_on():
    for i, room in enumerate(BANDS[:-1]):
        down = "." in room["C"]
        side = any(r == i and d == 1 for r, _s, d in HL.SIDE_EXITS[L - 1])
        assert down or side, f"room {i} has no way on"


# --- entities ---------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)


def test_every_entity_in_the_live_capture_is_present():
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    want_lanterns = {(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "lantern"}
    assert lanterns == want_lanterns
    want = {(r, w, x, y) for r, w, x, y in CHARACTERS_MD if w not in ("lantern", "miner")}
    assert shipped() == want
    assert len(HL.SPIDERS[L - 1]) == 25
    (miner,) = [(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "miner"]
    assert HL.MINER_POS[L - 1] == miner


def test_the_census_lanterns_are_where_it_said():
    """The old census had five lanterns for level 18, in rooms
    1-5; all five are where it put them."""
    for row in [(1, 83, 35), (2, 131, 35), (3, 127, 35), (4, 83, 35), (5, 131, 35)]:
        assert row in HL.LANTERNS[L - 1]


def test_the_census_still_bats_are_bobbing_untethered_spiders():
    """The census called rooms 1 and 3's floor creatures still 7x7 bats at
    y 110 - seen from the x = 0 park, which dies in these magma rooms and
    freezes them. They are untethered spiders bobbing 7 px from y 104/105."""
    free = {(c[0], c[1], c[2]) for _i, c in of_kind(4)}
    assert {(1, 24, 104), (3, 80, 105)} <= free


def test_nothing_was_invented_in_room_0():
    assert not any(r == 0 for r, *_ in HL.SPIDERS[L - 1])
    assert not any(r == 0 for r, *_ in HL.LANTERNS[L - 1])


def test_the_lanterns_hang_in_the_ceiling_band_on_row_35():
    assert len(HL.LANTERNS[L - 1]) == 9
    assert {r for r, *_ in HL.LANTERNS[L - 1]} == set(range(1, 6)) | {7, 8, 9, 10}
    for room, x, y in HL.LANTERNS[L - 1]:
        assert y == 35, "every lantern in the game hangs on row 35"
        assert BANDS[room]["A"][(x - 8) // 4] == ".", f"room {room}: in air"


def test_the_miner_is_in_the_last_room():
    common.check_miner(L, BANDS)
    assert HL.MINER_POS[L - 1] == (15, 128, 86)


def test_the_eleven_bats_patrol_22_px_on_46_frames_and_hold_a_pose_4():
    bats = of_kind(1)
    assert [c[0] for _i, c in bats] == [1, 3, 4, 5, 6, 6, 9, 10, 11, 14, 15]
    for slot, (_room, _x, _y, half, _k) in bats:
        assert 2 * half == 22
        assert 2 * HL.CREATURE_PATROL[(L, slot)] == 46
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 16, 4)


def test_the_untethered_spiders_bob_7_px_on_16_frames():
    free = of_kind(4)
    assert [c[0] for _i, c in free] == [1, 3, 7, 9, 13]
    for slot, (_room, _x, _y, half, _k) in free:
        assert half == 0, "it bobs; it does not patrol"
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 16, 8)


def test_the_engine_locks_the_untethered_spiders_pose_to_its_bob(env):
    """The ROM's cycle, frame by frame (ROM_FREE): the positions and the pose
    order are the ROM's. The engine's triangle wave rounds its ends
    differently - it holds the top 3 frames and the bottom 1 where the ROM
    holds each 2 - so its upward half runs up to 1 px ahead: the same
    rounding every bobbing creature in the game gets from _creature_pos."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((1, 24, 104, 0, 4))
    got = []
    for t in range(32):
        _x, y = _creature_pos(c, jnp.int32(L - 1), jnp.int32(t))
        pose = (t // int(c.SPIDER_HOLD[L - 1][slot])) % 2   # 1 = _ART2
        got.append((int(y[slot]), pose))
    # pose 1 (legs gathered) exactly while it goes down, as on the ROM
    down = [p for (y0, p), (y1, _q) in zip(got, got[1:]) if y1 > y0]
    up = [p for (y0, p), (y1, _q) in zip(got, got[1:]) if y1 < y0]
    assert set(down) == {1} and set(up) == {0}
    assert {y for y, _p in got} == {y for y, _p in ROM_FREE} == set(range(104, 112))
    assert got[:16] == got[16:], "a 16-frame cycle"


def test_the_hanging_spiders_are_still():
    hanging = of_kind(0)
    assert [(c[0], c[1], c[2]) for _i, c in hanging] == [
        (2, 136, 70), (11, 36, 70), (12, 32, 70), (12, 76, 109), (13, 96, 70),
        (14, 136, 70)]
    for slot, (_room, _x, _y, half, _k) in hanging:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 8)
        assert (L, slot) not in HL.CREATURE_SPRITES, "both poses are drawn"


def test_the_snakes_grow_out_of_the_rock_a_pixel_every_frame():
    """Rooms 2 and 4's floor snakes, anchored in the rock cell on their
    left, stretch a pixel EVERY frame: hold 1, a 16-frame cycle."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _snake_length
    snakes = of_kind(3)
    assert [(c[0], c[1], c[2]) for _i, c in snakes] == [(2, 112, 111), (4, 24, 111)]
    for slot, (room, x, y, half, _k) in snakes:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 1), "a pixel every frame"
        band = BANDS[room]["C"]
        assert band[(x - 8) // 4 - 1] == "#" and band[(x - 8) // 4] in ".~"
    got = [int(_snake_length(jnp.int32(t), jnp.int32(1))) for t in range(32)]
    assert got[:16] == got[16:]
    assert any(got[k:16] + got[:k] == ROM_SNAKE for k in range(16)), \
        "the ROM's 16-frame shape, at some phase"


def test_exactly_the_bats_and_the_untethered_spiders_bob_or_patrol():
    movers = {i for i, c in enumerate(HL.SPIDERS[L - 1])
              if c[3] or HL.CREATURE_MOTION[(L, i)][0]}
    assert movers == {i for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] in (1, 4)}
    assert len(movers) == 16


def test_the_engine_draws_the_bats_on_the_rom_clock(env):
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((3, 55, 64, 11, 1))
    xs, ys = [], []
    for t in range(0, 92):
        x, y = _creature_pos(c, jnp.int32(L - 1), jnp.int32(t))
        xs.append(int(x[slot])); ys.append(int(y[slot]))
    assert max(xs) - min(xs) == 22 and max(ys) - min(ys) == 7
    assert xs[:46] == xs[46:92], "the sweep is a 46-frame cycle"
    assert ys[:16] == ys[16:32] == ys[32:48], "the bob is a 16-frame cycle"


# --- rendering --------------------------------------------------------------
def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black."""
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    state = state.replace(level=jnp.int32(L - 1), room=jnp.int32(11))
    frame = np.asarray(env.render(state))
    assert frame[189:210].max() == 0, "something is drawn where the logo was"


def test_room_0_paints_the_levels_own_green():
    _palette, rooms = common.level_data(L)
    for role in ("dark", "mid", "light"):
        r, g, b = common.rgb(HL.SHADES[L][role])
        assert (rooms[0] == np.array([r, g, b])).all(axis=-1).any(), (
            f"room 0 never paints its {role}")


# --- room 12: the floor spider, the raft and a death (reported 2026-09-26) --
def test_the_rows_are_the_ones_the_rom_draws_with_the_hero_in_the_room():
    """Re-read on the ROM with the hero parked in the room at two heights of
    opposite parity (identical): the first capture had these 1-2 rows low."""
    rows = {(r, x): y for r, x, y, _h, _k in HL.SPIDERS[L - 1]}
    assert rows[(12, 76)] == 109 and rows[(12, 32)] == 70
    assert rows[(14, 79)] == 103 and rows[(14, 136)] == 70
    assert rows[(2, 136)] == 70 and rows[(2, 112)] == 111
    assert rows[(3, 55)] == 64 and rows[(5, 115)] == 64


def test_the_floor_spider_can_be_shot_from_the_raft(env):
    """What was reported: with the capture's y 111 its body sat on rows
    117-121, below the lowest bolt the hero can fire (row 116, riding the
    raft), so it could not be killed. At the ROM's 109 it is."""
    import jax.numpy as jnp
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((12, 76, 109, 0, 0))
    s = _state(env, 12, raft_x=jnp.int32(50), raft_dir=jnp.int32(1),
               player_x=jnp.int32(51), player_y=jnp.int32(c.raft_y - c.player_height),
               facing=jnp.int32(1))
    score = int(s.score)
    for _ in range(12):
        _obs, s, *_ = env.step(s, 1)                     # FIRE
    assert not bool(s.spider_alive[slot])
    assert int(s.score) - score == c.creature_points


def test_the_laser_takes_a_hanging_spider_through_its_thread(env):
    """The ROM kills a hanging spider with a bolt anywhere on its drawn
    sprite, thread included: room 11's (rows 70-80, thread 70-75) died to a
    bolt on every row 70-79 and lived at 68-69 and 82 (measured bolt row by
    row, 2026-09-26). Here the bolt flies on row 72, on the thread."""
    import jax.numpy as jnp
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((11, 36, 70, 0, 0))
    y = 72 - c.laser_eye_offset
    for bolt_row, dies in ((72, True), (68, False)):
        y = bolt_row - c.laser_eye_offset
        s = _state(env, 11, player_x=jnp.int32(18), player_y=jnp.int32(y),
                   facing=jnp.int32(1))
        for _ in range(12):
            # pin the rotor in its hover band too, or the ROM hero's thrust
            # drops him a row or two inside the step and the bolt with him
            s = s.replace(player_y=jnp.int32(y), player_vy=jnp.float32(0),
                          thrust_timer=jnp.int32(c.thrust_kick))
            _obs, s, *_ = env.step(s, 1)                 # FIRE
        assert bool(s.spider_alive[slot]) != dies, f"bolt on row {bolt_row}"


def test_a_death_on_the_raft_leaves_it_and_brings_him_back_onto_it(env):
    """The ROM, 2026-09-26: carried from x 28 into the floor spider, he died
    at x 70; the raft stopped at 71 and stayed there, and he came back in the
    same column, through the magma wall, stopping just under it (PY 34, y 101)
    over the raft. Here he lands on it and rides on."""
    import jax.numpy as jnp
    c = env.consts
    s = _state(env, 12, raft_x=jnp.int32(28), raft_dir=jnp.int32(1),
               player_x=jnp.int32(29), player_y=jnp.int32(c.raft_y - c.player_height))
    lives = int(s.lives)
    died_at = landed_at = None
    for f in range(200):
        prev = s
        # a new life hovers where it comes back until the first input (the
        # ROM); one tap of DOWN - a NOOP in the air - starts his rotor
        first = died_at is not None and not bool(s.has_moved)
        _obs, s, *_ = env.step(s, 5 if first else 0)
        if died_at is None and int(s.lives) < lives:
            died_at = f
            assert int(s.player_y) == c.respawn_low_y, "under the magma wall"
            assert abs(int(s.player_x) - int(prev.player_x)) <= 1, "in his own column"
            raft_at_death = int(s.raft_x)
        elif died_at is not None and int(s.player_y) < c.raft_y - c.player_height:
            assert int(s.raft_x) == raft_at_death, "the raft waits where it stopped"
        elif died_at is not None:
            # back on it: watch a few frames of the ride, not its whole run
            # to the far end, where it turns round
            landed_at = f if landed_at is None else landed_at
            if f >= landed_at + 10:
                break
    assert died_at is not None
    assert int(s.player_y) == c.raft_y - c.player_height, "back on the raft"
    assert int(s.raft_x) > raft_at_death, "and it carries him on"


@pytest.mark.parametrize("room, x, y, low", [(11, 36, 72, False), (14, 79, 104, True),
                                             (6, 47, 64, False), (6, 47, 104, True)])
def test_he_comes_back_at_the_height_of_the_band_he_died_in(env, room, x, y, low):
    """The ROM, 2026-09-26/27: pinned where a creature kills him, the hero
    comes back in his own column at corridor height (y 62) when the creature
    is in the corridor band and at y 101 when it is in the floor band - room
    11's corridor spider, room 14's floor bat, room 6's two bats."""
    import jax.numpy as jnp
    c = env.consts
    s = _state(env, room, player_x=jnp.int32(x), player_y=jnp.int32(y),
               room_timer=jnp.int32(0), step_counter=jnp.int32(0))
    lives = int(s.lives)
    for _ in range(200):
        s = s.replace(player_x=jnp.int32(x), player_y=jnp.int32(y),
                      player_vy=jnp.float32(0))
        _obs, s, *_ = env.step(s, 0)
        if int(s.lives) < lives:
            break
    assert int(s.lives) == lives - 1, "a creature killed him"
    assert int(s.player_y) == (c.respawn_low_y if low else c.respawn_y)
    assert abs(int(s.player_x) - x) <= 4, "in his own column"


def test_he_can_fly_off_the_raft_and_hover_under_the_magma(env):
    """The ROM, 2026-09-27: UP held on the raft under room 12's magma wall, he
    lifts off, rises until his head is under the magma and hovers there,
    alive. Underneath, magma is a ceiling, not a burn."""
    import jax.numpy as jnp
    c = env.consts
    s = _state(env, 12, raft_x=jnp.int32(28), raft_dir=jnp.int32(1),
               player_x=jnp.int32(29), player_y=jnp.int32(c.raft_y - c.player_height),
               spider_alive=jnp.zeros_like(c.SPIDER_VALID[L - 1]))
    lives = int(s.lives)
    ys = []
    for _ in range(90):
        _obs, s, *_ = env.step(s, 2)                     # UP
        ys.append(int(s.player_y))
    assert int(s.lives) == lives, "the magma over him does not burn"
    assert min(ys) < c.raft_y - c.player_height, "he lifted off the raft"
    assert ys[-1] == ys[-10] and 60 + 39 - 2 <= ys[-1] <= 99, "and hovers under the wall"
    assert int(s.room) == 12
