"""Level 14, against the corrected ROM reference.

The block in hero_levels.py is generated by a level builder that walks
the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), and check the engine draws it.

What came out of level 14:

  * THE WALK REACHES ALL SIXTEEN ROOMS. The old reference had it at 3 (rooms
    0-2, room 2 read off the playthrough). The walker stopped at room 12
    until blast_exit learned that a stick takes a two-cell MAGMA pillar as
    well as a rock one: room 12's way out is its open right edge, behind a
    '%%' pillar at cells 34-35.
  * ONE PLAYTHROUGH BAND WAS WRONG. Room 2's left-edge wall is MAGMA ('%%',
    the reference had '##') - the same mistake as level 12 room 3 and level
    13 room 7. The ROM wins; the reference was corrected before the rest of
    the walk was appended.
  * ROOM 5's GAP BREATHES MAGMA (HL.MAGMA_MOUTHS). Its eight-cell corridor gap
    is not a fixed gap: while the hero is alive the magma on each side grows
    over it one cell every 8 frames until it is shut, then draws back, on a
    64-frame cycle that starts from the frame the room is entered - four
    arrival times gave the identical sequence, and it repeats exactly for
    3000 frames. It burns like any magma; after a death in the room it stays
    open for the rest of the visit, and a death elsewhere does not affect it.
    The playthrough shows it: level_14 frame 67 has it 4 cells open, frame 68
    shut. The old reference's "magma flare on room entry" - 4 cells for 34
    frames, then 8 for good - is this mouth freezing while the hero DIES at
    the x = 0 reading park and then staying open, not an entry transient.
  * ITS CREATURES RUN AT LEVEL 10'S SPEED: all eight bats sweep 22 px on 92
    frames, everything that bobs bobs 7 px on 32; bats hold a wing pose 4
    frames, spiders 8. The six hanging spiders are still. Three wall snakes.
  * THE LIQUID IS THE PURPLE THE LEVEL FILE GIVES, #a8308f, on rows 136-141
    of rooms 10-15 and nowhere else.
  * The census scanned two rooms and found nothing. Every one of
    the capture's 24 creatures, 6 lanterns and the miner is new.

The shape of the level, room by room:

    rooms 0-9   GREEN, magma in every corridor; holes in the floor except
                rooms 1, 3 and 7, left through an open side (1 LEFT, 3 and 7
                RIGHT).
    room 5      the breathing mouth over the one way down.
    room 9      a two-cell magma pillar at cells 20-21: a stick (not needed
                for the way down, which is the hole at 17-18).
    room 10     ROCK, the one room of the level with no magma; water from
                here to the end, and the level descends RIGHT from here on.
    rooms 11, 13  a two-cell magma pillar at 17-18 on rock between waters.
    room 12     a SIX-cell magma wall at 15-20 over the water, crossed on the
                RAFT (HL.RAFTS), which waits at its LEFT end (x 28) because
                the hero comes in from the left; then a two-cell magma
                pillar at 34-35 in front of the right edge: a stick.
    room 14     a two-cell magma pillar at 11-12 on rock: a stick.
    room 15     the miner's room, the miner at x 128.
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

L = 14

# What the ROM draws, cell for cell, in descent order, verified against
# the reference before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "%%...........%%...................%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "....................................%%",
     "C": "######################################"},
    {"A": "######################################",
     "B": "%%....................................",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%....................................",
     "C": "######################################"},
    {"A": "######################################",
     "B": "....................................%%",
     "C": "####....########....########....######"},
    {"A": "####....########....########....######",
     "B": "%%%%%%%%%%%%%%........%%%%%%%%%%%%%%%%",
     "C": "##########................############"},
    {"A": "##########................############",
     "B": "%%........%%%%%%%%%%%%........%%%%%%%%",
     "C": "###......##################......#####"},
    {"A": "###......##################......#####",
     "B": "%%....................................",
     "C": "######################################"},
    {"A": "######################################",
     "B": "....................................%%",
     "C": "####.......##############.......######"},
    {"A": "####.......##############.......######",
     "B": "%%%%%%%%............%%......%%%%%%%%%%",
     "C": "#################..###################"},
    {"A": "#################..###################",
     "B": "##......####............####..........",
     "C": "###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#####"},
    {"A": "######################################",
     "B": ".................%%...................",
     "C": "####~~~~~~~~~~~######~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": "...............%%%%%%.............%%..",
     "C": "####~~~~~~~~~~~~~~~~~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": ".................%%...................",
     "C": "####~~~~~~~~~~~~####~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": "...........%%.........................",
     "C": "####~~~~~~####~~~~~~~~####~~~~~~######"},
    {"A": "######################################",
     "B": "....................................%%",
     "C": "##########~~~~~~####~~~~~~############"},
]

# The live-hero ROM capture (the data hero_levels.py ships), as
# (room, what, x, y) with x the LEFT edge of the drawn box - for a bat, of
# its sweep. Every row.
# The creature rows are read with the hero IN the room (2026-09-30): the
# above-the-picture park drew three of them a row low, e.g.
# "room 2 snake at x 72: drawn from row 111 with the hero in the room (the capture said 112)".
CHARACTERS_MD = [
    (1, "lantern", 83, 35), (1, "bat", 48, 64),
    (2, "snake", 72, 111), (2, "bat", 92, 64),
    (3, "lantern", 83, 35), (3, "spider_free", 72, 65),
    (4, "snake", 72, 111), (4, "spider_free", 108, 65),
    (5, "lantern", 83, 35), (5, "bat", 48, 103),
    (6, "lantern", 107, 35), (6, "spider", 120, 70),
    (7, "lantern", 135, 35), (7, "spider_free", 136, 66),
    (8, "spider_free", 36, 104), (8, "bat", 48, 64),
    (9, "spider", 44, 70),
    (10, "lantern", 79, 35), (10, "bat", 20, 103), (10, "spider_free", 68, 65),
    (11, "bat", 44, 64), (11, "bat", 92, 103),
    (12, "spider_free", 52, 65), (12, "spider", 68, 109),
    (13, "spider", 36, 70), (13, "snake", 88, 111),
    (14, "bat", 64, 103), (14, "spider", 108, 70),
    (15, "spider_free", 88, 65), (15, "spider", 92, 109), (15, "miner", 128, 86),
]

KIND_NAME = {0: "spider", 1: "bat", 3: "snake", 4: "spider_free"}
MAGMA_ROOMS = set(range(16)) - {10}

# Room 5's mouth, measured on the ROM frame by frame from arrival: cells of
# the 8-cell gap OPEN, e frames after the room was entered (e = 0 is the
# transition frame; the first frame recorded, e = 1, draws 4).
ROM_OPEN = "4" * 8 + "2" * 8 + "0" * 8 + "2" * 8 + "4" * 8 + "6" * 8 + "8" * 8 + "6" * 8


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


def shipped():
    """{(room, what, left x, top y)} for every creature SPIDERS carries."""
    return {(r, KIND_NAME[k], x - half, y)
            for r, x, y, half, k in HL.SPIDERS[L - 1]}


# --- geometry ---------------------------------------------------------------
def test_level_14_is_sixteen_green_rooms():
    common.check_shape(L, "green", rooms=16)
    assert len(HL.BG_RLE_L14) == 16


def test_all_sixteen_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_the_level_is_complete_and_nothing_is_missing():
    """The old reference listed level 14 as 3 of 16 rooms. The other thirteen
    were reached on 2026-09-24 by the walker's side exits and, for room 12,
    by blowing a two-cell MAGMA pillar."""
    assert len(BANDS) == 16
    assert len({(b["A"], b["B"], b["C"]) for b in BANDS}) == 16, \
        "no ROOM is a copy of another"


def test_the_playthrough_band_is_the_roms():
    """Room 2's left-edge wall is magma, not rock."""
    assert BANDS[2]["B"] == "%%" + "." * 36


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_where_the_level_goes_down_through_holes():
    """Room N's ceiling is drawn identically to room N-1's floor when N is
    entered through a hole. Rooms 2, 4, 8 and 11-15 are entered SIDEWAYS,
    under a ceiling that is solid across the whole screen."""
    sideways = {2, 4, 8, 11, 12, 13, 14, 15}
    for i in range(1, 16):
        if i in sideways:
            assert BANDS[i]["A"] == "#" * 38, f"room {i}"
        else:
            assert BANDS[i]["A"] == BANDS[i - 1]["C"].replace("~", "#"), \
                f"chain breaks between rooms {i - 1} and {i}"


def test_no_cell_was_left_uncalled():
    for i, room in enumerate(BANDS):
        for band, s in room.items():
            assert "?" not in s, f"room {i} band {band} has an uncalled cell"
            assert set(s) <= set("#%.~"), f"room {i} band {band} has a stray value"


# --- the water --------------------------------------------------------------
def test_the_six_pool_rooms_are_the_only_liquid_cells():
    with_liquid = {i for i, r in enumerate(BANDS) if "~" in r["C"]}
    assert with_liquid == set(range(10, 16))


def test_the_water_rooms_have_no_hole_to_fall_through():
    for room in range(10, 16):
        assert "." not in BANDS[room]["C"], f"room {room} floor has a real hole"


def test_a_liquid_cell_is_solid_only_on_the_rows_it_is_drawn_on():
    y0, y1 = common.LIQUID_ROWS
    for room in range(10, 16):
        liquid_x = {8 + 4 * i for i, c in enumerate(BANDS[room]["C"]) if c == "~"}
        for x, y, w, h in HL.WALL_RECTS_L14[room]:
            if x in liquid_x and y >= 99:
                assert (y, h) == (y0, y1 - y0 + 1), (
                    f"room {room}: the liquid rect at x {x} is {h} px tall "
                    f"from row {y}; it must be rows {y0}-{y1}")


def test_the_deadly_rects_are_the_water_line():
    assert HL.DEADLY[L - 1] == [(room, 8, 136, 152, 6) for room in range(10, 16)]


def test_the_liquid_is_the_purple_the_level_file_gives():
    """The level file says #a8308f for level 14, and the ROM agrees: it
    paints (168, 48, 143) on the water rows of rooms 10-15 and nowhere else."""
    palette, rooms = common.level_data(L)
    liquid = common.rgb("#a8308f")
    assert liquid in palette
    for i, img in enumerate(rooms):
        ys, _xs = np.nonzero((img == np.array(liquid)).all(axis=-1))
        if i >= 10:
            assert ys.size and ys.min() >= 136, f"room {i}"
        else:
            assert not ys.size, f"room {i} paints the liquid colour"


def test_no_rotor_yellow_is_painted_into_the_cave():
    """Room 12's yellow bar on the water is the RAFT, drawn by the engine
    where it currently is; neither it nor the x = 0 park's rotor tip is in
    any background."""
    _palette, rooms = common.level_data(L)
    rotor = np.array(common.rgb("#e8e84a"))
    for i, img in enumerate(rooms):
        ys, xs = np.nonzero((img == rotor).all(axis=-1))
        assert not ys.size, f"room {i} paints rotor yellow at {xs[0]},{ys[0]}"
    assert HL.RAFTS[L - 1] == [(12, 28)]


def test_room_12s_wall_is_crossed_on_the_raft():
    """Six cells of magma, three times what a stick takes, under a solid
    ceiling - but every cell under it is '~', AIR from row 99 to 135."""
    assert (15, 20) in runs_of(BANDS[12]["B"], "%")
    assert BANDS[12]["A"] == "#" * 38
    assert set(BANDS[12]["C"][15:21]) == {"~"}
    assert not any(r == 12 and x == 68 for r, x, *_ in HL.DESTRUCTIBLE[L - 1])


# --- magma ------------------------------------------------------------------
def test_magma_is_in_every_room_but_room_10():
    """Magma is a property of the ROOM: in a magma room every solid corridor
    cell is magma. Room 10 is rock."""
    with_magma = {i for i, r in enumerate(BANDS) if "%" in "".join(r.values())}
    assert with_magma == MAGMA_ROOMS
    for room in with_magma:
        assert "#" not in BANDS[room]["B"], \
            f"room {room}: in a magma room every solid corridor cell is magma"
    assert "%" not in BANDS[10]["B"] and "#" in BANDS[10]["B"]


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


def test_magma_never_leaves_the_corridor_band():
    for _room, _x, y, _w, h in HL.MAGMA[L - 1]:
        assert (y, h) == (60, 39), "magma is a corridor register, not a band"


def test_no_magma_is_carried_as_a_creature():
    assert not any(row[4] == 2 for row in HL.SPIDERS[L - 1])


# --- room 5's magma mouth ---------------------------------------------------
def test_room_5s_gap_is_the_levels_one_mouth():
    """The eight air cells 14-21 between room 5's two magma walls are the
    mouth; no other room of this level has one. The other measured
    mouths are level 15 room 9's and level 16 rooms 7 and 9 (2026-09-25),
    level 17 room 9's and level 18 room 8's (2026-09-26), and level 19
    room 6's and level 20 room 5's (2026-09-27)."""
    assert HL.MAGMA_MOUTHS[L - 1] == [(5, 64, 32, 8, 16)]
    band = BANDS[5]["B"]
    assert runs_of(band, ".") == [(14, 21)]
    assert band[13] == band[22] == "%"
    assert cells(14, 21) == (64, 32)
    for lv, mouths in enumerate(HL.MAGMA_MOUTHS):
        if lv + 1 not in (L, 15, 16, 17, 18, 19, 20):
            assert mouths == [], f"level {lv + 1}"


def test_the_mouth_cycle_is_the_roms():
    """The engine's clock gives exactly the measured widths, frame by frame,
    and the cycle is 64 frames long."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _mouth_closed
    c = JaxHero().consts
    got = ""
    for e in range(128):
        closed = int(_mouth_closed(c, jnp.int32(L - 1), jnp.int32(e))[0])
        got += str(8 - 2 * closed)
    assert got == ROM_OPEN * 2


def _corridor(frame):
    row = np.asarray(frame)[80]
    magma = {(167, 26, 26), (184, 50, 50)}
    return "".join("%" if tuple(int(v) for v in row[9 + 4 * i]) in magma
                   else ("#" if row[9 + 4 * i].sum() else ".") for i in range(38))


def test_the_engine_draws_the_mouth_in_magma(env):
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    state = state.replace(level=jnp.int32(L - 1), room=jnp.int32(5),
                          player_x=jnp.int32(30), player_y=jnp.int32(0),
                          spider_alive=env.consts.SPIDER_VALID[L - 1])
    for e in range(0, 64, 4):
        band = _corridor(env.render(state.replace(room_timer=jnp.int32(e))))
        gap = band[14:22]
        n = int(ROM_OPEN[e])
        closed = (8 - n) // 2
        assert gap == "%" * closed + "." * n + "%" * closed, f"e {e}: {gap}"
        assert band[:14] == "%" * 14 and band[22:] == "%" * 16
    # a death leaves it open whatever the clock says
    shut = env.render(state.replace(room_timer=jnp.int32(16), mouth_open=jnp.bool_(True)))
    assert _corridor(shut)[14:22] == "." * 8


def _in_room_5(env, **kw):
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    fields = dict(level=jnp.int32(L - 1), room=jnp.int32(5),
                  room_timer=jnp.int32(0), has_moved=jnp.bool_(True),
                  banner_timer=jnp.int32(0),
                  spider_alive=env.consts.SPIDER_VALID[L - 1])
    fields.update(kw)
    return state.replace(**fields)


def test_the_mouth_burns_and_then_stays_open_for_the_visit(env):
    """A hero hovering in the middle of the gap dies on the frame it shuts on
    him (e 16). The respawn is in the same room, with the mouth open; the
    next room change closes it and restarts the clock."""
    import jax.numpy as jnp
    state = _in_room_5(env, player_x=jnp.int32(77), player_y=jnp.int32(70))
    lives = int(state.lives)
    for _ in range(40):
        state = state.replace(player_x=jnp.int32(77), player_y=jnp.int32(70),
                              player_vy=jnp.float32(0))
        _obs, state, *_ = env.step(state, 0)
        if int(state.lives) < lives:
            break
    assert int(state.lives) == lives - 1 and int(state.room_timer) == 16
    assert int(state.room) == 5 and bool(state.mouth_open)
    # drop through the open gap into room 6: a real room change
    state = state.replace(player_x=jnp.int32(77), player_y=jnp.int32(104),
                          player_vy=jnp.float32(2.0), invuln_timer=jnp.int32(0))
    for _ in range(60):
        _obs, state, *_ = env.step(state, 5)
        if int(state.room) != 5:
            break
    assert int(state.room) == 6 and int(state.room_timer) == 0
    assert not bool(state.mouth_open)


def test_the_clock_restarts_on_every_room_entry(env):
    """Falling from room 4 into room 5 zeroes the clock, whatever it was."""
    import jax.numpy as jnp
    state = _in_room_5(env, room=jnp.int32(4), room_timer=jnp.int32(500),
                       player_x=jnp.int32(77), player_y=jnp.int32(120),
                       player_vy=jnp.float32(2.0),
                       invuln_timer=jnp.int32(1000))   # past room 4's snake
    for _ in range(40):
        _obs, state, *_ = env.step(state, 5)
        if int(state.room) == 5:
            break
    assert int(state.room) == 5 and int(state.room_timer) == 0


def test_room_5_is_passed_by_waiting_in_the_shaft(env):
    """The way the ROM is played: the hero comes in at the top, hovers in the
    ceiling shaft (rows 16-59, above the mouth) until it has shut and begins
    to open, then drops through it holding DOWN. Falling straight in puts
    him in the gap as it shuts, exactly as the ROM walker's hero died."""
    import jax.numpy as jnp

    def attempt(hover_until):
        # he comes in slowly, the rotor in its hover band: the ROM hero
        # cannot brake a 2 px/frame fall before the mouth (his thrust needs
        # ~40 frames of UP), so a fast entry dies whatever he does next
        state = _in_room_5(env, player_x=jnp.int32(77), player_y=jnp.int32(2),
                           player_vy=jnp.float32(0.0),
                           thrust_timer=jnp.int32(env.consts.thrust_hover))
        lives = int(state.lives)
        for _ in range(200):
            waiting = int(state.room_timer) < hover_until
            # hover by tapping UP to hold the thrust in its hover band
            act = (2 if int(state.thrust_timer) < 24 else 0) if waiting else 5
            _obs, state, *_ = env.step(state, act)
            if int(state.lives) < lives:
                return "died"
            if int(state.room) == 6:
                return "through"
        return "stuck"

    assert attempt(0) == "died"
    # one whole 64-frame mouth cycle in the shaft, and the drop is timed
    # (measured on the engine: waits of 4-16, 60-80 and 124-128 frames get
    # through, the 64-frame period of the mouth; the rest die)
    assert attempt(64) == "through"


# --- dynamite ---------------------------------------------------------------
def test_the_blastable_pillars_are_the_two_cell_ones():
    """Only a run of exactly two cells breaks, never one that reaches the side
    of the screen - magma the same as rock."""
    want = []
    for i, room in enumerate(BANDS):
        for first, last in runs_of(room["B"], "#") + runs_of(room["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            want.append((i, first, last))
    got = {(r, (x - 8) // 4, (x - 8) // 4 + w // 4 - 1)
           for r, x, _y, w, _h, _n in HL.DESTRUCTIBLE[L - 1]}
    assert got == set(want)
    assert len(want) == 6


def test_room_12s_way_out_is_a_magma_pillar():
    """The walker's stop: the right edge that leads on sits behind '%%' at
    cells 34-35, with solid rock above it and below it."""
    assert BANDS[12]["B"][34:36] == "%%" and BANDS[12]["B"][36:] == ".."
    assert set(BANDS[12]["C"][34:36]) == {"#"}
    x, w = cells(34, 35)
    assert (12, x, 60, w, 39, 1) in HL.DESTRUCTIBLE[L - 1]


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    for room, x, y, _w, h, _n in HL.DESTRUCTIBLE[L - 1]:
        first = (x - 8) // 4
        same = (first, first + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if same else (60, 39)), f"room {room} at x {x}"
        assert same == (room == 0)


def test_the_shared_wall_table_is_empty():
    common.check_shared_walls(L)


def test_nothing_flares():
    """The old block's flare rows were authored on the superseded reference;
    the one moving magma in the level is room 5's mouth, a measured table of
    its own."""
    assert HL.FLARES[L - 1] == []


# --- the way down -----------------------------------------------------------
def test_the_side_exits_are_the_open_corridor_edges():
    want = set()
    for i, room in enumerate(BANDS):
        if room["B"][0] == ".":
            want.add((i, -1))
        if room["B"][37] == ".":
            want.add((i, 1))
    assert {(r, s) for r, s, _d in HL.SIDE_EXITS[L - 1]} == want


def test_level_14_descends_left_once_then_right():
    """A side exit's direction is DATA. Room 1 goes on through its LEFT edge,
    rooms 3 and 7 through their RIGHT, and from room 10 the level goes RIGHT
    with every left edge leading back up."""
    by_room = {}
    for room, side, delta in HL.SIDE_EXITS[L - 1]:
        by_room.setdefault(room, {})[side] = delta
    assert by_room[1] == {-1: 1} and by_room[2] == {1: -1}
    assert by_room[3] == {1: 1} and by_room[4] == {-1: -1}
    assert by_room[7] == {1: 1} and by_room[8] == {-1: -1}
    assert by_room[10] == {1: 1}
    for room in range(11, 15):
        assert by_room[room] == {-1: -1, 1: 1}, f"room {room}"
    assert by_room[15] == {-1: -1}, "the last room leads nowhere but back"


def test_every_room_but_the_last_has_a_way_on():
    for i, room in enumerate(BANDS[:-1]):
        down = "." in room["C"]
        side = any(r == i and d == 1 for r, _s, d in HL.SIDE_EXITS[L - 1])
        assert down or side, f"room {i} has no way on"


# --- entities ---------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)


def test_every_entity_in_the_live_capture_is_present():
    """Every lantern, every creature at its kind, x and y, and the miner -
    and not one creature more."""
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    want_lanterns = {(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "lantern"}
    assert lanterns == want_lanterns
    want = {(r, w, x, y) for r, w, x, y in CHARACTERS_MD if w not in ("lantern", "miner")}
    assert shipped() == want
    assert len(HL.SPIDERS[L - 1]) == 24
    (miner,) = [(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "miner"]
    assert HL.MINER_POS[L - 1] == miner


def test_nothing_was_invented_in_room_0():
    """Neither the census nor the ROM draws a creature or a lamp in room 0."""
    assert not any(r == 0 for r, *_ in HL.SPIDERS[L - 1])
    assert not any(r == 0 for r, *_ in HL.LANTERNS[L - 1])


def test_the_lanterns_hang_in_the_ceiling_band_on_row_35():
    assert len(HL.LANTERNS[L - 1]) == 6
    assert {r for r, *_ in HL.LANTERNS[L - 1]} == {1, 3, 5, 6, 7, 10}
    for _room, _x, y in HL.LANTERNS[L - 1]:
        assert y == 35, "every lantern in the game hangs on row 35"


def test_the_miner_is_in_the_last_room():
    common.check_miner(L, BANDS)
    assert HL.MINER_POS[L - 1] == (15, 128, 86)


def test_the_eight_bats_patrol_22_px_on_92_frames_and_hold_a_pose_4():
    bats = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 1]
    assert [c[0] for _i, c in bats] == [1, 2, 5, 8, 10, 11, 11, 14]
    for slot, (_room, _x, _y, half, _k) in bats:
        assert 2 * half == 22
        assert 2 * HL.CREATURE_PATROL[(L, slot)] == 92
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 32, 4)


def test_the_untethered_spiders_bob_7_px_on_32_frames():
    free = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 4]
    assert [c[0] for _i, c in free] == [3, 4, 7, 8, 10, 12, 15]
    for slot, (_room, _x, _y, half, _k) in free:
        assert half == 0, "it bobs; it does not patrol"
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 32, 8)


def test_the_hanging_spiders_are_still():
    """Whether a creature moves is a property of the room. Level 14's six
    hanging spiders are all still: no patrol, no bob, two poses on an 8-frame
    hold."""
    hanging = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 0]
    assert [(c[0], c[1], c[2]) for _i, c in hanging] == [
        (6, 120, 70), (9, 44, 70), (12, 68, 109), (13, 36, 70),
        (14, 108, 70), (15, 92, 109)]
    for slot, (_room, _x, _y, half, _k) in hanging:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 8)
        assert (L, slot) not in HL.CREATURE_SPRITES, "both poses are drawn"


def test_the_three_snakes_grow_out_of_the_rock():
    """Each snake is anchored in the rock on its left - rooms 2 and 4 at the
    left wall of the floor hole at cells 16-19, room 13 at the rock between
    two pools - and has no patrol and no bob of its own."""
    snakes = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 3]
    assert [(c[0], c[1], c[2]) for _i, c in snakes] == [
        (2, 72, 111), (4, 72, 111), (13, 88, 111)]
    for slot, (room, x, _y, half, _k) in snakes:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 2), "a pixel every 2 frames"
        assert BANDS[room]["C"][(x - 8) // 4 - 1] == "#", "rock on its left"


# Room 2's snake on the ROM, hero alive above the picture, from arrival (px
# out of the rock per frame): twice level 9's speed - the same stretch in a
# 32-frame cycle where levels 1-9 take 64 (measured 2026-09-25).
ROM_SNAKE = [0] * 2 + [n for n in range(1, 7) for _ in range(2)] + [7] * 4 + \
            [n for n in range(6, 0, -1) for _ in range(2)] + [0] * 2


def test_the_snakes_stretch_on_the_roms_32_frame_cycle():
    """The engine's stretch at level 14's 2 frames per pixel is the ROM's
    sequence (up to its phase), and the head still flips every 8 frames, as it
    does on every level - only the length runs faster."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _snake_length, _snake_head_down
    got = [int(_snake_length(jnp.int32(t), jnp.int32(2))) for t in range(64)]
    assert got[:32] == got[32:], "a 32-frame cycle"
    assert any(got[k:32] + got[:k] == ROM_SNAKE for k in range(32))
    slow = [int(_snake_length(jnp.int32(t))) for t in range(64)]
    assert got[:32] == slow[::2], "level 9's cycle at twice the speed"
    head = [bool(_snake_head_down(jnp.int32(t))) for t in range(32)]
    flips = [t for t in range(1, 32) if head[t] != head[t - 1]]
    assert [b - a for a, b in zip(flips, flips[1:])] == [8] * (len(flips) - 1)


def test_the_engine_draws_and_collides_the_fast_snake(env):
    """The renderer and the collision box read the same per-snake rate."""
    import jax.numpy as jnp
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((2, 72, 111, 0, 3))
    assert int(c.SPIDER_HOLD[L - 1, slot]) == 2
    other = [i for i in range(c.num_spiders)
             if bool(c.SPIDER_VALID[3, i]) and int(c.SPIDER_KIND[3, i]) == 3]
    assert other and all(int(c.SPIDER_HOLD[3, i]) == 4 for i in other), \
        "level 4's snakes keep the 64-frame cycle"


def test_exactly_the_bats_and_the_untethered_spiders_move():
    movers = {i for i, c in enumerate(HL.SPIDERS[L - 1])
              if c[3] or HL.CREATURE_MOTION[(L, i)][0]}
    assert movers == {i for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] in (1, 4)}
    assert len(movers) == 15


def test_the_engine_draws_the_bats_on_the_rom_clock(env):
    """The engine's creature positions over 184 frames sweep 22 px and repeat
    every 92 frames, and the bob repeats every 32 - room 1's bat."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((1, 59, 64, 11, 1))
    xs, ys = [], []
    for t in range(0, 184):
        x, y = _creature_pos(c, jnp.int32(L - 1), jnp.int32(t))
        xs.append(int(x[slot])); ys.append(int(y[slot]))
    assert max(xs) - min(xs) == 22 and max(ys) - min(ys) == 7
    assert xs[:92] == xs[92:184], "the sweep is a 92-frame cycle"
    assert ys[:32] == ys[32:64] == ys[64:96], "the bob is a 32-frame cycle"


# --- rendering --------------------------------------------------------------
def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black."""
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    state = state.replace(level=jnp.int32(L - 1), room=jnp.int32(5))
    frame = np.asarray(env.render(state))
    assert frame[189:210].max() == 0, "something is drawn where the logo was"


def test_room_0_paints_the_levels_own_green():
    """Room 0 is recoloured from the ROM's brown boot palette to the level's
    green ramp."""
    _palette, rooms = common.level_data(L)
    for role in ("dark", "mid", "light"):
        r, g, b = common.rgb(HL.SHADES[L][role])
        assert (rooms[0] == np.array([r, g, b])).all(axis=-1).any(), (
            f"room 0 never paints its {role}")
    brown = common.rgb(HL.SHADES[1]["mid"])
    assert not (rooms[0] == np.array(brown)).all(axis=-1).any()
