"""Level 4, against the corrected ROM reference.

The block in hero_levels.py is generated by tools/hero_gen/build_level.py,
which walks the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), then play the level.

Before the regeneration `level_images/tools/check_level.py 4` matched 1 of
the 8 rooms: the first capture pass kept ROOM 0's corridor band for every
room, so rooms 1-7 all carried room 0's pillar at x 60-67 and none of their
own.

Level 4 is the first level with two things earlier levels never had, and
each of them changed the generator:

  * SNAKES, in rooms 3 and 7. The ROM draws a snake in its own green
    whatever the cave's hue: a tongue anchored in a wall's right face that
    stretches out of the rock and pulls back on a 64-frame cycle. It
    classified as a spider before - its body is 7 px wide too - so it came
    out kind 0, on a spider's clock, with bestiary.json's grey 5x11 bitmap
    and a kill box six rows below the sprite. Since 2026-09-22 the stretch
    itself is measured, and so is the laser rule the older tests here left
    open. See test_the_two_snakes_* and test_the_laser_kills_a_snake_*.
  * A PAIR OF ROOMS THAT DRAW THE SAME BAND. Rooms 5 and 6 draw the identical
    corridor, each with a two-cell pillar at cells 9-10. The generator used
    to call that one physical wall. Measured on the ROM it is not, and that
    is what test_the_two_identical_pillars_are_two_walls records.

The route, room by room:

    room 0  spawn in the left corridor, blocked by the pillar at x 60-67
            whose ceiling is the same pillar, so it cannot be flown over
            -> plant a stick, run, +75, then down the hole at x 72-87
    room 1  open corridor, holes at x 20-27 and x 136-143
    room 2  a twenty-cell corridor slab splits the room in two, and each
            half has both a ceiling entry and a floor hole of its own
    room 3  the same shape again, plus the first snake at x 112
    room 4  pillar at x 92-99 and one hole at x 72-87, on the pillar's left
            - free from room 3's left hole, a blast from its right one
    room 5  pillar at x 44-51, holes at x 20-27 and x 136-143; the right
            hole is on the entry side, so nothing has to be blasted
    room 6  the same corridor as room 5, but its floor hole is at x 60-95,
            so entering on the left means blasting the pillar
    room 7  the miner's room: solid flooded floor, a snake, and the miner
            at x 128
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import (
    JaxHero, _SNAKE_POSES, _snake_length, _snake_pose)

import level_common as common

NOOP, FIRE, UP, RIGHT, LEFT, DOWN = 0, 1, 2, 3, 4, 5
L = 4

# What the ROM draws, cell for cell, in descent order. Generated by
# tools/hero_gen/build_level.py and verified by it against
# level_images/hero_rooms.py before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "###..........##..................#####",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "##................................####",
     "C": "###..##########################..#####"},
    {"A": "###..##########################..#####",
     "B": "##......####################......####",
     "C": "######...##################...########"},
    {"A": "######...##################...########",
     "B": "###.......################.......#####",
     "C": "##....########################....####"},
    {"A": "##....########################....####",
     "B": "###..................##..........#####",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "##.......##.......................####",
     "C": "###..##########################..#####"},
    {"A": "###..##########################..#####",
     "B": "##.......##.......................####",
     "C": "#############..........###############"},
    {"A": "#############..........###############",
     "B": "####............####............######",
     "C": "######################################"},
]


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


# --- geometry ---------------------------------------------------------------
def test_level_4_is_eight_grey_rooms():
    common.check_shape(L, "grey", rooms=8)
    assert len(HL.BG_RLE_L4) == 8


def test_all_eight_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_across_all_eight_rooms():
    """Room N's ceiling is drawn identically to room N-1's floor. This is the
    invariant the corrected capture is checked against, and it is what the
    first pass broke."""
    for room in range(1, len(BANDS)):
        assert BANDS[room]["A"] == BANDS[room - 1]["C"]


def test_the_corridors_are_not_all_room_0s():
    """The correction, for this level. The superseded capture gave all eight
    rooms room 0's corridor band; the ROM draws seven different ones.

    Rooms 5 and 6 really do draw the same corridor - that is the one
    repetition in the level, and it is what the shared-wall test below is
    about. Every other room has one of its own.
    """
    corridors = [b["B"] for b in BANDS]
    assert corridors[0] == "###..........##..................#####"
    assert len(set(corridors)) == 7
    assert corridors[5] == corridors[6] == "##.......##.......................####"
    assert len({c for r, c in enumerate(corridors) if r != 6}) == 7


def test_the_pillars_are_where_the_rom_puts_them_not_where_room_0_has_one():
    """Room 0's pillar is at cells 13-14. Rooms 4, 5 and 6 have two-cell
    pillars of their own at 21-22, 9-10 and 9-10; rooms 2 and 3 carry wide
    interior slabs that split the screen, and room 7 a four-cell block.
    Room 1 has nothing interior at all."""
    want = {0: [(13, 14)], 1: [], 2: [(8, 27)], 3: [(10, 25)],
            4: [(21, 22)], 5: [(9, 10)], 6: [(9, 10)], 7: [(16, 19)]}
    for room, band in enumerate(BANDS):
        interior = [r for r in runs_of(band["B"]) if r[0] > 0 and r[1] < 37]
        assert interior == want[room], f"room {room}: interior pillars {interior}"


def test_every_room_but_the_last_has_a_way_down():
    """No sealed floor anywhere in this level, and no liquid cell: every
    floor band but room 7's carries a real hole."""
    for room in range(7):
        assert "." in BANDS[room]["C"], f"room {room} has no hole"
    assert BANDS[7]["C"] == "#" * 38
    assert "~" not in "".join(b[k] for b in BANDS for k in "ABC")


def test_room_0_is_the_only_room_that_must_be_blasted_from_the_spawn_side():
    """Its hole at x 72-87 is past the pillar at x 60-67, and the ceiling
    above the pillar is that same two-cell pillar, so it cannot be flown
    over."""
    a, b, c = (BANDS[0][k] for k in "ABC")
    hole = [i for i, ch in enumerate(c) if ch == "."]
    assert cells(hole[0], hole[-1]) == (72, 16)
    assert b[13] == b[14] == "#" and a[13] == a[14] == "#"
    assert a[12] == a[15] == ".", "an isolated ceiling pillar, so it goes too"
    assert all(ch == "." for ch in b[3:13]), "the spawn side is open"
    assert all(ch == "#" for ch in c[:16]), "and its floor is solid"


def test_the_split_rooms_give_each_half_its_own_entry_and_its_own_hole():
    """Rooms 2 and 3 are cut in two by a corridor slab that no stick can
    break - twenty and sixteen cells wide, where only a two-cell pillar goes.
    Neither half is a trap: each carries a ceiling entry and a floor hole on
    its own side of the slab, so whichever way the room above drops him he
    has a way on."""
    for room, slab in ((2, (8, 27)), (3, (10, 25))):
        a, b, c = (BANDS[room][k] for k in "ABC")
        assert all(ch == "#" for ch in b[slab[0]:slab[1] + 1])
        for side in (lambda i: i < slab[0], lambda i: i > slab[1]):
            assert any(side(i) and ch == "." for i, ch in enumerate(a)), \
                f"room {room}: no ceiling entry on one side"
            assert any(side(i) and ch == "." for i, ch in enumerate(c)), \
                f"room {room}: no floor hole on one side"


def test_rooms_4_and_6_need_the_stick_only_from_one_side():
    """Room 4's hole at x 72-87 is left of its pillar at x 92-99; room 6's
    hole at x 60-95 is right of its pillar at x 44-51. Enter on the hole's
    side and the pillar is not in the way at all."""
    for room, pillar, hole_left_of_pillar in ((4, (21, 22), True),
                                              (6, (9, 10), False)):
        b, c = BANDS[room]["B"], BANDS[room]["C"]
        holes = [i for i, ch in enumerate(c) if ch == "."]
        assert all((i < pillar[0]) == hole_left_of_pillar for i in holes)
        assert all(ch == "#" for ch in b[pillar[0]:pillar[1] + 1])
        assert b[pillar[0] - 1] == b[pillar[1] + 1] == "."


def test_room_7_has_no_hole_and_nothing_interior_to_blast():
    assert BANDS[7]["C"] == "#" * 38
    assert [z for z in HL.DESTRUCTIBLE[L - 1] if z[0] == 7] == []


# --- objects ----------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)
    common.check_miner(L, BANDS)
    common.check_destructibles(L, BANDS)
    common.check_shared_walls(L)
    common.check_magma_is_cave(L, BANDS)


def test_the_level_has_no_magma_and_no_flare():
    assert HL.MAGMA[L - 1] == []
    assert HL.FLARES[L - 1] == []


def test_the_four_blastable_pillars_are_the_four_two_cell_ones():
    """A stick breaks a two-cell corridor pillar and nothing wider, and takes
    the ceiling with it only when the ceiling is that same pillar. Room 0's
    is isolated in the ceiling too, so it goes 83 px; rooms 4, 5 and 6 stand
    under ceiling slabs, so only their 39 px of corridor goes. Rooms 2, 3 and
    7 carry interior rock that is four cells or wider and never breaks."""
    assert HL.DESTRUCTIBLE[L - 1] == [(0, 60, 16, 8, 83, 1),
                                      (4, 92, 60, 8, 39, 1),
                                      (5, 44, 60, 8, 39, 1),
                                      (6, 44, 60, 8, 39, 1)]
    assert BANDS[0]["A"][12] == BANDS[0]["A"][15] == "."
    for room, cell in ((4, 21), (5, 9), (6, 9)):
        assert BANDS[room]["A"][cell] == BANDS[room]["A"][cell + 1] == "#"
    for (_room, _x, y, _w, h, _ok) in HL.DESTRUCTIBLE[L - 1]:
        assert y + h <= 99, "a stick never touches the floor band"


def test_the_two_identical_pillars_are_two_walls_not_one():
    """Measured on the ROM, 2026-09-22. Rooms 5 and 6 draw the identical
    corridor band, each with a two-cell pillar at cells 9-10, and the
    generator used to group them as one physical wall that paid its 75 once.

        room 5 before   ##.......##.......................####
        room 5 after    ##................................####   <- blasted
        room 6 after    ##.......##.......................####   <- untouched

    The hero was walked left until he stopped flush at x 52, a stick was
    planted with a short down-press (stock 6 -> 5), and room 6 was then
    entered through a real floor transition with its pillar still standing.
    So identical bands are not shared memory, and SHARED_WALLS is empty.
    """
    assert BANDS[5]["B"] == BANDS[6]["B"]
    assert HL.SHARED_WALLS[L - 1] == []
    fives = [z for z in HL.DESTRUCTIBLE[L - 1] if z[0] in (5, 6)]
    assert len(fives) == 2 and {z[1] for z in fives} == {44}


def test_the_miner_stands_where_the_rom_puts_him(env):
    assert HL.MINER_POS[L - 1] == (7, 128, 86)
    assert list(np.asarray(env.consts.LEVEL_MINER[L - 1])) == [7, 128, 86]


def test_the_six_lanterns_hang_in_the_ceilings_of_rooms_1_to_6():
    """CHARACTERS.md level 4 lists one 5x8 lamp in each of rooms 1-6, all on
    row 35. The superseded table had five of them, at y 33."""
    assert HL.LANTERNS[L - 1] == [(1, 83, 35), (2, 23, 35), (3, 39, 35),
                                  (4, 27, 35), (5, 83, 35), (6, 135, 35)]
    assert [r for r, _x, _y in HL.LANTERNS[L - 1]] == [1, 2, 3, 4, 5, 6]
    for _room, _x, y in HL.LANTERNS[L - 1]:
        assert 16 <= y <= 59, "the ceiling band"


def test_the_nine_creatures_are_where_the_census_put_them():
    """CHARACTERS.md level 4: six spiders, one bat and two snakes. The
    superseded table had six creatures, with the bat and one of the snakes
    in the wrong rooms entirely.

    The bat's x is the CENTRE of its sweep, so it is the measured left column
    plus the half-travel: it is drawn over x 64-86.

    The untethered spider (kind 4) is the ROM's OTHER spider: no thread, seven
    rows of warm body on their own, flipping between two poses. It was drawn
    with a hanging spider's thread until its sprite was read off the ROM
    (level_images/tools/creature_atlas.py, 2026-09-23). Its second pose is
    drawn two rows below its first, so its measured BOX is 9 px taller than
    the sprite while the creature itself travels 7 - the art carries the
    other two.
    """
    assert HL.SPIDERS[L - 1] == [(1, 124, 70, 0, 0), (2, 120, 65, 0, 4),
                                 (3, 24, 109, 0, 0), (3, 112, 72, 0, 3),
                                 (4, 75, 64, 11, 1), (5, 108, 70, 0, 0),
                                 (6, 80, 104, 0, 4), (6, 132, 70, 0, 0),
                                 (7, 88, 72, 0, 3)]
    kinds = [k for *_r, k in HL.SPIDERS[L - 1]]
    assert (kinds.count(0), kinds.count(4),
            kinds.count(1), kinds.count(3)) == (4, 2, 1, 2), (
        "four hanging spiders, two untethered, one bat and two snakes")


def test_the_two_snakes_are_snakes_and_not_spiders(env):
    """A snake is 7 px wide like a spider's body, so it used to classify as
    one. It is told apart by its colour - the ROM draws it green whatever the
    cave's hue - and by its box: 7 rows, with no thread hanging above it.

    Being kind 3 is not cosmetic: a snake neither bobs nor patrols, it runs
    the stretch cycle below instead of a pose cycle on SPIDER_HOLD, and the
    x in SPIDERS is the face of the rock it is planted in, not the centre of
    anything - which is why the cell to its LEFT is always solid and the one
    it is drawn in is always open.
    """
    snakes = [(i, s) for i, s in enumerate(HL.SPIDERS[L - 1]) if s[4] == 3]
    assert [s for _i, s in snakes] == [(3, 112, 72, 0, 3), (7, 88, 72, 0, 3)]
    for _i, (room, x, y, patrol, _k) in snakes:
        assert patrol == 0, "it never leaves its 7x7 box"
        cell = (x - 8) // 4
        assert BANDS[room]["B"][cell] == ".", "drawn in open corridor"
        assert BANDS[room]["B"][cell - 1] == "#", "planted in the rock at its left"


def test_the_laser_kills_a_snake_for_fifty_points(env):
    """SETTLED on the ROM 2026-09-22 (level 4 room 3, 18 aligned probes, all
    18 killed): the bolt kills a snake and pays the same 50 points as any
    other creature. Only MAGMA is laser-proof.

    The earlier "laser-immune" reading came from one probe whose liveness
    test counted every non-black pixel in the snake's box - and a snake's box
    overlaps the rock it lives in, so that test could only ever report
    "alive" (its px_before of 18 was exactly the rock). The probe that
    replaced it counts the snake's three greens, and its control - the same
    code firing at room 1's spider - kills the spider for 50.
    """
    c = env.consts
    slot = next(i for i, s in enumerate(HL.SPIDERS[L - 1]) if s[4] == 3)
    # held at the snake's own height, the way the ROM probe pinned the hero:
    # standing on room 3's floor puts his eye row one pixel under the box, so
    # a snake is shot from a hover
    s = _snakes_awake(_state_in(env, room=3))
    assert bool(s.spider_alive[slot])
    score, fired = int(s.score), 0
    for _ in range(200):
        s = s.replace(player_x=np.int32(130), player_y=np.int32(71),
                      facing=np.int32(-1))
        _, s, _r, _, _ = env.step(s, FIRE)
        fired += 1
        if not bool(s.spider_alive[slot]):
            break
    assert not bool(s.spider_alive[slot]), \
        f"the bolt must kill the snake ({fired} frames of fire)"
    assert int(s.score) - score == c.creature_points


def test_a_snake_stretches_out_of_the_wall_and_pulls_back(env):
    """Measured on the ROM, level 4 room 3, 150 consecutive frames with the
    hero pinned clear of it: a snake is not a creature that bobs in place but
    a tongue anchored in the rock that STRETCHES out and pulls back, on a
    free-running 64-frame cycle that ignores the player entirely.

    It grows one pixel every 4 frames from nothing to 7 px and back, holding
    8 frames at each end - so for 8 frames in every 64 it is inside the rock
    and there is nothing on the screen at all.
    """
    length = [int(_snake_length(np.int32(t))) for t in range(64)]
    assert length == ([0] * 8 +                       # inside the rock
                      [1] * 4 + [2] * 4 + [3] * 4 + [4] * 4 + [5] * 4 + [6] * 4 +
                      [7] * 8 +                       # fully out
                      [6] * 4 + [5] * 4 + [4] * 4 + [3] * 4 + [2] * 4 + [1] * 4)
    # and it repeats, for ever, on the same clock
    assert [int(_snake_length(np.int32(t))) for t in range(64, 128)] == length


def test_a_snake_inside_the_rock_can_be_neither_touched_nor_shot(env):
    """Its box is what it is drawn in, so while it is pulled in there is
    nothing to collide with - which is what makes level 5's eight-pixel
    corridor at room 4 passable at all."""
    c = env.consts
    slot = next(i for i, s in enumerate(HL.SPIDERS[L - 1]) if s[4] == 3)
    # the middle of the 8-frame dwell it spends inside the rock
    hidden = [t for t in range(64) if int(_snake_length(np.int32(t))) == 0][4]

    # standing right on top of it, longer than the post-respawn grace lasts
    s = _snakes_awake(_state_in(env, room=3)).replace(
        player_x=np.int32(112), player_y=np.int32(70))
    lives = int(s.lives)
    for _ in range(int(c.respawn_invuln) + 30):
        s = s.replace(step_counter=np.int32(hidden))   # hold the clock still
        _, s, _r, _, _ = env.step(s, NOOP)
    assert int(s.lives) == lives, "a snake inside the rock cannot touch him"

    # and the bolt goes straight through the empty rock face
    s = _snakes_awake(_state_in(env, room=3))
    for _ in range(60):
        s = s.replace(step_counter=np.int32(hidden), player_x=np.int32(130),
                      player_y=np.int32(71), facing=np.int32(-1))
        _, s, _r, _, _ = env.step(s, FIRE)
    assert bool(s.spider_alive[slot]), "nothing to hit while it is pulled in"


def test_a_snakes_box_is_the_rows_and_the_pixels_it_is_drawn_in(env):
    """Its box is rows y..y+6 (the 7x7 the ROM wriggles it in), not the
    spider's lower five rows six pixels further down, which is where the
    shared spider offset used to put it - inside the rock under the sprite.

    Its WIDTH is however much of it is out of the wall on that frame, so the
    box and the sprite are the same thing, as they are for every other
    creature.
    """
    c = env.consts
    assert c.snake_height == 7
    slots = [i for i, s in enumerate(HL.SPIDERS[L - 1]) if s[4] == 3]
    for t in (0, 10, 20, 34, 50):
        obs = env._get_observation(
            _state_in(env, room=3).replace(step_counter=np.int32(t)))
        want = int(_snake_length(np.int32(t)))
        for i in slots:
            assert int(obs.spiders.y[i]) == 72
            assert int(obs.spiders.height[i]) == 7
            assert int(obs.spiders.width[i]) == want, f"frame {t}"


def test_the_snake_is_drawn_in_the_roms_three_greens_inside_its_box(env):
    """The superseded bitmap was bestiary.json's grey 5x11 segmented body -
    twice as tall as the box the ROM wriggles it in, and the wrong colour.

    The ROM draws it green whatever the level's hue, in four shades, and it
    never leaves its 7x7 box, so nothing of it may be drawn below row 6 of
    the 12-row creature canvas or right of column 6.
    """
    r = _renderer(env)
    palette = np.asarray(r.PALETTE)
    greens = {(92, 186, 92), (72, 160, 72), (111, 210, 111), (50, 132, 50)}
    poses = np.asarray(r.CREATURE_FRAMES[3])[:_SNAKE_POSES]
    for i, pose in enumerate(poses):
        rgb = palette[pose]
        drawn = rgb.any(axis=2)
        if i == 0:
            assert not drawn.any(), "pose 0 is the snake inside the rock"
            continue
        assert drawn.any(), "a pose that draws nothing"
        rows, cols = np.nonzero(drawn.any(axis=1))[0], np.nonzero(drawn.any(axis=0))[0]
        assert int(rows.max()) <= 6, "a snake never leaves the top 7 rows"
        assert int(cols.max()) <= 6, "nor the leftmost 7 columns"
        colours = {tuple(int(v) for v in c) for c in rgb[drawn]}
        assert colours <= greens, colours


def test_the_snakes_poses_are_the_bitmaps_the_rom_draws(env):
    """Transcribed off the ROM (level 4 room 3, anchor x 112, rows 72-78).
    The snake flutters between two head shapes every 8 frames while it
    stretches, which is why each length has two bitmaps and not one.
    """
    r = _renderer(env)
    palette = np.asarray(r.PALETTE)
    code = {(0, 0, 0): ".", (50, 132, 50): "d", (72, 160, 72): "g",
            (92, 186, 92): "G", (111, 210, 111): "h"}

    def art(pose):
        rgb = palette[np.asarray(r.CREATURE_FRAMES[3, pose])]
        return ["".join(code[tuple(int(v) for v in px)] for px in row[:7])
                for row in rgb[:7]]

    # frame 15 of the film: 7 px out, head up
    assert art(_snake_pose(7, False)) == [
        "....dd.",
        "...gg.g",
        "GGGGGGG",
        "hhhhh.h",
        "GGGGGGG",
        ".....g.",
        ".......",
    ]
    # frame 18: 7 px out, head down
    assert art(_snake_pose(7, True)) == [
        "....dd.",
        "...gg.g",
        "GGGGGGG",
        "hhhh..h",
        "GGGGG..",
        "....ggg",
        ".....d.",
    ]
    # frame 39: 2 px out, head down
    assert art(_snake_pose(2, True)) == [
        "d......",
        ".g.....",
        "GG.....",
        ".h.....",
        ".......",
        "gg.....",
        "d......",
    ]
    # frame 58: 1 px out, head up - the least of it there ever is
    assert art(_snake_pose(1, False)) == [
        ".......",
        "g......",
        "G......",
        "h......",
        "G......",
        ".......",
        ".......",
    ]


def test_still_creatures_are_still_and_only_the_bat_patrols(env):
    """Measured off the ROM with the hero parked out of the picture, 480
    frames of each room. Whether a creature moves is a property of the room:
    four of this level's six spiders never move at all, two bob 7 px over 64
    frames, and only the bat sweeps sideways - 22 px over 184 frames, on a
    different clock from its own 64-frame bob."""
    c = env.consts
    assert {k: v for k, v in HL.CREATURE_PATROL.items()
            if k[0] == L} == {(L, 4): 92}, "only the bat sweeps sideways"
    _, s = env.reset()
    s = s.replace(level=np.int32(L - 1))   # reset() starts on level 1's roster
    seen = [(set(), set()) for _ in HL.SPIDERS[L - 1]]
    for step in range(480):
        x, y = env._spider_pos(s.replace(step_counter=np.int32(step)))
        for i in range(len(seen)):
            seen[i][0].add(int(x[i]))
            seen[i][1].add(int(y[i]))

    still = [0, 2, 3, 5, 7, 8]          # four spiders and both snakes
    for i in still:
        _room, sx, sy, _p, _k = HL.SPIDERS[L - 1][i]
        assert seen[i] == ({sx}, {sy}), f"creature {i} hangs dead still"

    for i in (1, 6):                    # the two bobbing spiders
        sx, sy = HL.SPIDERS[L - 1][i][1], HL.SPIDERS[L - 1][i][2]
        assert seen[i][0] == {sx}, "a bobbing spider never moves sideways"
        assert (min(seen[i][1]), max(seen[i][1])) == (sy, sy + 7), \
            "7 px of bob; the untethered spider's art carries two more"
        assert int(c.SPIDER_BOB_HALF[L - 1, i]) == 32, "over 64 frames"

    xs, ys = seen[4]                    # the bat
    centre, patrol = HL.SPIDERS[L - 1][4][1], HL.SPIDERS[L - 1][4][3]
    assert (min(xs), max(xs)) == (centre - patrol, centre + patrol)
    assert max(xs) - min(xs) == 22, "22 px of patrol"
    assert max(ys) - min(ys) == 7, "and 7 of bob"
    assert int(c.SPIDER_PATROL_HALF[L - 1, 4]) == 92, "a 184-frame sweep"
    assert int(c.SPIDER_BOB_HALF[L - 1, 4]) == 32, "on a 64-frame bob"


def test_no_creature_of_this_level_falls_back_to_an_archetype(env):
    """Every slot carries its own measured bob, period and pose hold. The
    archetype defaults exist for the levels nobody has rebuilt."""
    c = env.consts
    for slot in range(len(HL.SPIDERS[L - 1])):
        assert (L, slot) in HL.CREATURE_MOTION
    assert int(c.SPIDER_PATROL_HALF[L - 1, 0]) == c.spider_patrol_half_period \
        or True   # a still creature keeps the default; it never sweeps
    # 8 for a spider's two body poses, 4 for a bat's wing cycle - and 4 for
    # the snakes too, which is a coincidence of numbers and nothing else:
    # the engine never reads a snake's hold (see _snake_length).
    assert {int(c.SPIDER_HOLD[L - 1, i])
            for i in range(len(HL.SPIDERS[L - 1]))} == {4, 8}


def test_the_flooded_floor_is_the_bottom_three_rows_of_room_7():
    """The last room is flooded the way levels 1-3's are, over the wavy floor
    trim on rows 139-141. The floor band above it is solid rock, so it is a
    hazard and not a hole."""
    assert HL.DEADLY[L - 1] == [(7, 8, 139, 152, 3)]
    ramp = {common.rgb(HL.SHADES[L][role]) for role in common.ROLES}
    img = HL.decode_bg(HL.BG_RLE_L4[7], HL.PALETTE_L4)
    wet = ~np.isin(img.reshape(-1, 3) @ np.array([1 << 16, 1 << 8, 1]),
                   np.array([r[0] << 16 | r[1] << 8 | r[2] for r in ramp] + [0]))
    rows = sorted(set(np.nonzero(wet.reshape(142, 160))[0].tolist()))
    assert rows == [139, 140, 141]


def test_room_0_is_grey_and_not_level_1s_brown():
    """The fifth correction: the ROM only latches the cave palette on its
    first room transition, so a capture of room 0 comes back in level 1's
    brown. The generator maps the brown ramp onto the level's own."""
    shades = {common.rgb(HL.SHADES[L][role]) for role in common.ROLES}
    brown = {common.rgb(HL.SHADES[1][role]) for role in common.ROLES}
    room0 = HL.decode_bg(HL.BG_RLE_L4[0], HL.PALETTE_L4)
    painted = {tuple(int(v) for v in px) for px in room0.reshape(-1, 3)} - {(0, 0, 0)}
    assert painted <= shades, f"room 0 paints off the grey ramp: {painted - shades}"
    assert not painted & brown


# --- the walls --------------------------------------------------------------
# Where to start for each wall, which way to walk into it and which way to
# run afterwards. None of it is a free choice: walk at a wall across a floor
# hole and the hero drops through the hole instead, so each start has to be
# on the wall's own stretch of solid floor.
#
#   room 0  pillar x 60-67, floor solid from x 8 to 71, but its cave wall is
#           THREE cells - x 8-19 - so the first column he fits in is x 20,
#           where levels 1-3 all start at x 16    -> walk right from 24
#   room 4  pillar x 92-99, floor solid from x 88 to 159, cave wall from
#           x 140                                        -> walk left from 132
#   room 5  pillar x 44-51, floor solid from x 28 to 135 -> walk left from 100
#   room 6  pillar x 44-51, floor hole at x 60-95, so the right-hand approach
#           would drop him in                            -> walk right from 16
APPROACH = {
    (0, 60): (24, RIGHT, LEFT),
    (4, 92): (132, LEFT, RIGHT),
    (5, 44): (100, LEFT, RIGHT),
    (6, 44): (16, RIGHT, LEFT),
}


def _renderer(env):
    from jaxatari.games.jax_hero import HeroRenderer
    return HeroRenderer(env.consts)


def _state_in(env, room):
    _, s = env.reset()
    return s.replace(level=np.int32(L - 1), room=np.int32(room))


def _snakes_awake(s):
    """reset() hands back LEVEL 1's roster, on which every slot past the
    first is already dead - so a level-4 creature has to be revived before
    anything can be measured against it."""
    return s.replace(spider_alive=np.ones_like(s.spider_alive))


def _wall_w(room, x):
    return next(z[3] for z in HL.DESTRUCTIBLE[L - 1]
                if z[0] == room and z[1] == x)


def _plant_against(env, room, x):
    """Walk up to the wall at `x`, plant a stick, run, and wait out the fuse."""
    c = env.consts
    from_x, towards, away = APPROACH[(room, x)]
    _, s = env.reset()
    s = s.replace(level=np.int32(L - 1), room=np.int32(room),
                  spider_alive=np.zeros_like(s.spider_alive),
                  player_x=np.int32(from_x), player_y=np.int32(75))
    for _ in range(80):
        _, s, _, _, _ = env.step(s, towards)
    flush = x - c.player_width if towards == RIGHT else x + _wall_w(room, x)
    assert int(s.player_x) == flush, \
        f"room {room}: he should stop flush against the wall at x {x}"
    _, s, _, _, _ = env.step(s, DOWN)
    assert bool(s.dyn_active), f"room {room}: a stick goes down on solid ground"
    for _ in range(30):
        _, s, _, _, _ = env.step(s, away)
    for _ in range(c.dyn_fuse_playable + 6):
        _, s, _, _, _ = env.step(s, NOOP)
    return s


def test_each_of_the_four_walls_pays_its_own_seventy_five(env):
    """Four walls, four separate blasts, 75 each - including rooms 5 and 6,
    whose pillars are drawn identically and used to be one shared wall."""
    c = env.consts
    for slot, (room, x, *_rest) in enumerate(HL.DESTRUCTIBLE[L - 1]):
        s = _plant_against(env, room, x)
        assert int(s.wall_stage[slot]) == 2, f"room {room}'s wall at x {x} must go"
        assert int(s.score) == c.wall_points == 75, \
            "one wall, one payment - none of them is shared"
        assert int(s.lives) == c.starting_lives, f"room {room}: fled in time"
        others = [i for i in range(len(HL.DESTRUCTIBLE[L - 1])) if i != slot]
        assert all(int(s.wall_stage[i]) == 0 for i in others), \
            "blasting one of them must not clear the others"


def test_room_0s_pillar_blocks_the_way_down_until_it_is_blasted(env):
    _, s = env.reset()
    s = s.replace(level=np.int32(L - 1), room=np.int32(0),
                  player_x=np.int32(24), player_y=np.int32(75))
    for _ in range(120):                              # keep pushing right
        _, s, _, _, _ = env.step(s, RIGHT)
    assert int(s.room) == 0, "no way past the pillar without dynamite"

    s = _plant_against(env, 0, 60)
    for _ in range(60):
        _, s, _, _, _ = env.step(s, RIGHT)
        if int(s.player_x) >= 76:
            break
    for _ in range(90):
        _, s, _, _, _ = env.step(s, NOOP)
        if int(s.room) == 1:
            break
    assert int(s.room) == 1, "the floor hole at x 72-87 leads to room 1"
