"""Level 9, against the corrected ROM reference.

The block in hero_levels.py is generated by tools/hero_gen/build_level.py,
which walks the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), then play the level.

Three things came out of level 9, and two of them are about the tools:

  * THE WALK NOW REACHES ALL SIXTEEN ROOMS. CORRECTIONS.md had it at 11.
    Room 10 is left through its open RIGHT edge. Rooms 11, 12 and 13 each
    have a two-cell pillar between the hero and the way on, under a ceiling
    that is solid across the whole room, so each one takes a stick. The first
    walk came back with rooms 12 and 13 MISSING, straight from 11 to 14:
    blast_exit tried room 11's LEFT edge first, stood the hero on the far
    side of the pillar at x 152 - which is inside the open RIGHT edge - and
    pinning him there carried him 11 -> 12 -> 13 -> 14 one room per re-pin.
    A stand that leaves the room is now refused.
  * THE READING PARK KILLS THE HERO IN A MAGMA ROOM. Both the capture and
    CHARACTERS.md's census read a room with the hero pinned at RAM x = 0,
    and where cells 0-1 of the corridor are magma - every room 0-10 here -
    that costs a life at frame 107 (measured with lives unpinned). The ROM
    then draws the room FROZEN: bats that patrol stand still, untethered
    spiders that bob hang still, and the spiders hanging in the CORRIDOR are
    not drawn at all after frame 106. So the census calls this level's
    creatures still, and has no row for five of them. The capture now
    watches such a room again with the hero pinned above the picture, where
    he does not die, and takes its creatures from there.
  * The rooms past the water - 11 to 15 - have never been censused.

The shape of the level, room by room:

    rooms 0-10  BROWN, and magma in every one of them.
    room 10     the corridor is open end to end, the floor is liquid from
                cell 10 to cell 25, and the way on is the open RIGHT edge.
    room 11     sealed ceiling, liquid floor, a patrolling bat. Blast the
                cells 34-35 pillar to reach the right edge.
    room 12     a pillar at cells 17-18 over the rock between two stretches
                of water, a snake out of that rock and a corridor spider.
    room 13     an eight-cell wall over the water - flown UNDER, through the
                air above the liquid - then a pillar at 34-35 to blast.
    room 14     a sixteen-cell wall, also over the water and flown under.
    room 15     the miner's room: solid floor, solid ceiling, one spider and
                the miner at x 128.
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

L = 9

# What the ROM draws, cell for cell, in descent order. Generated by
# tools/hero_gen/build_level.py and verified by it against
# level_images/hero_rooms.py before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "%%...........%%...................%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%.........%%.....................%%%%",
     "C": "####....####################....######"},
    {"A": "####....####################....######",
     "B": "%%%......%%%%%%%%%%%%%%%%%%......%%%%%",
     "C": "####............................######"},
    {"A": "####............................######",
     "B": "%%%%%%...%%%%%%%%%%%%%%%%%%...%%%%%%%%",
     "C": "####............................######"},
    {"A": "####............................######",
     "B": "%%%%%%%%%...%%%%%%%%%%%%...%%%%%%%%%%%",
     "C": "####............................######"},
    {"A": "####............................######",
     "B": "%%%%%%%%%%%...%%%%%%%%...%%%%%%%%%%%%%",
     "C": "####............................######"},
    {"A": "####............................######",
     "B": "%%%%%%%%%%%..............%%%%%%%%%%%%%",
     "C": "############....####....##############"},
    {"A": "############....####....##############",
     "B": "%%........................%%......%%%%",
     "C": "####..########################..######"},
    {"A": "####..########################..######",
     "B": "%%.......%%.......................%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%%%%%%%%%%%%%%......%%%%%%%%%%%%%%%%%",
     "C": "####............................######"},
    {"A": "####............................######",
     "B": "%%....................................",
     "C": "##########~~~~~~~~~~~~~~~~############"},
    {"A": "######################################",
     "B": "..................................##..",
     "C": "######~~~~~~~~~~~~~~~~~~~~~~~~########"},
    {"A": "######################################",
     "B": ".................##...................",
     "C": "###~~~~~~~~~~~~~####~~~~~~~~~~~~~#####"},
    {"A": "######################################",
     "B": "..............########............##..",
     "C": "##########~~~~~~~~~~~~~~~~############"},
    {"A": "######################################",
     "B": "..........################............",
     "C": "####~~~~~~~~~~~~~~~~~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": "....................................##",
     "C": "######################################"},
]

# CHARACTERS.md, "Level 9" - rewritten on 2026-09-23 from the live-hero ROM
# capture - as (room, what, x, y), x the left edge of the drawn box. Every row.
CHARACTERS_MD = [
    (1, "lantern", 83, 35), (1, "spider", 124, 109), (1, "spider_free", 28, 65),
    (2, "lantern", 131, 35), (2, "spider", 56, 110),
    (3, "lantern", 131, 35), (3, "spider_free", 60, 105),
    (4, "lantern", 131, 35),
    (5, "lantern", 131, 35), (5, "bat", 56, 104),
    (6, "lantern", 131, 35), (6, "spider", 92, 71),
    (7, "lantern", 67, 35), (7, "spider", 24, 109),
    (8, "lantern", 27, 35), (8, "spider_free", 64, 65),
    (9, "lantern", 83, 35), (9, "bat", 40, 103), (9, "spider", 84, 70),
    (10, "lantern", 131, 35), (10, "bat", 76, 104), (10, "spider", 128, 71),
    (11, "bat", 60, 103),
    (12, "spider", 112, 70), (12, "snake", 88, 111),
    (13, "bat", 80, 103), (13, "spider", 112, 70),
    (14, "spider", 132, 70),
    (15, "spider", 76, 70), (15, "miner", 128, 86),
]

# The CENSUS table CHARACTERS.md carried for this level before 2026-09-23,
# kept as the record of what the lethal reading park did to it. Every row of
# it is still honoured: the same room and x, with the kind and the row the
# ROM draws with a live hero (SHIPPED_AS). Rooms 11-15 it never reached, and
# five creatures of rooms 1-10 it never saw (NOT_IN_CENSUS).
OLD_CENSUS = [
    (1, "lantern", 83, 35),
    (1, "spider", 124, 109),
    (2, "lantern", 131, 35),
    (2, "spider", 56, 109),
    (3, "lantern", 131, 35),
    (3, "bat", 60, 111),
    (4, "lantern", 131, 35),
    (5, "lantern", 131, 35),
    (5, "bat", 56, 110),
    (6, "lantern", 131, 35),
    (7, "lantern", 67, 35),
    (7, "spider", 24, 109),
    (8, "lantern", 27, 35),
    (9, "lantern", 83, 35),
    (9, "bat", 40, 110),
    (10, "lantern", 131, 35),
]

# The census rows the ROM does not draw that way with a LIVE hero, and what
# is shipped instead. Every x is the census's; only the kind or the row moves.
#
#   room 3  the census's test for a bat is "no thread", and this creature has
#           none because it is the UNTETHERED spider (kind 4): warm ramp, no
#           grey, seven rows (a bat is 11 rows with grey wings). It bobs 7 px,
#           so the box starts at 105.
#   room 5  a bat that PATROLS 22 px and bobs 7; the box starts at 104.
#   room 9  the same; the box starts at 103.
#   room 2  a still spider, drawn with its top on row 110 on all 1500 frames
#           of a live watch. The census's 109 is the pose the ROM draws
#           after the reading park has killed the hero.
SHIPPED_AS = {
    (3, "bat", 60, 111): ("spider_free", 60, 105),
    (5, "bat", 56, 110): ("bat", 56, 104),
    (9, "bat", 40, 110): ("bat", 40, 103),
    (2, "spider", 56, 109): ("spider", 56, 110),
}

# What the ROM draws that the old census has no row for, as (what, x, y).
# Rooms 1-10: hidden from it by its lethal park. Rooms 11-15: never reached.
NOT_IN_CENSUS = {
    1: [("spider_free", 28, 65)],
    6: [("spider", 92, 71)],
    8: [("spider_free", 64, 65)],
    9: [("spider", 84, 70)],
    10: [("bat", 76, 104), ("spider", 128, 71)],
    11: [("bat", 60, 103)],
    12: [("snake", 88, 111), ("spider", 112, 70)],
    13: [("bat", 80, 103), ("spider", 112, 70)],
    14: [("spider", 132, 70)],
    15: [("spider", 76, 70), ("miner", 128, 86)],
}

KIND_NAME = {0: "spider", 1: "bat", 3: "snake", 4: "spider_free"}


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


def shipped():
    """{(room, what, left x, top y)} for every creature SPIDERS carries."""
    return {(r, KIND_NAME[k], x - half, y)
            for r, x, y, half, k in HL.SPIDERS[L - 1]}


# --- geometry ---------------------------------------------------------------
def test_level_9_is_sixteen_brown_rooms():
    common.check_shape(L, "brown", rooms=16)
    assert len(HL.BG_RLE_L9) == 16


def test_all_sixteen_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_the_level_is_complete_and_nothing_is_missing():
    """CORRECTIONS.md listed level 9 as 11 of 16 rooms. The other five were
    reached on 2026-09-23: room 11 by flying off room 10's RIGHT edge, and
    rooms 12 to 15 past two sticks and two walls flown under."""
    assert len(BANDS) == 16
    assert len({(b["A"], b["B"], b["C"]) for b in BANDS}) == 16, \
        "no ROOM is a copy of another"


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_across_all_sixteen_rooms():
    """Room N's ceiling is drawn identically to room N-1's floor, with '~'
    folded onto '#' - liquid is floor seen from above and rock from below."""
    for i in range(1, len(BANDS)):
        below = BANDS[i]["A"].replace("~", "#")
        above = BANDS[i - 1]["C"].replace("~", "#")
        assert below == above, f"chain breaks between rooms {i - 1} and {i}"


def test_no_cell_was_left_uncalled():
    for i, room in enumerate(BANDS):
        for band, s in room.items():
            assert "?" not in s, f"room {i} band {band} has an uncalled cell"
            assert set(s) <= set("#%.~"), f"room {i} band {band} has a stray value"


# --- the water --------------------------------------------------------------
def test_the_five_water_rooms_are_the_only_liquid():
    with_liquid = {i for i, r in enumerate(BANDS) if "~" in r["C"]}
    assert with_liquid == {10, 11, 12, 13, 14}
    assert BANDS[15]["C"] == "#" * 38


def test_the_water_rooms_have_no_hole_to_fall_through():
    """Liquid LOOKS like a hole and is not - LEVEL_09.md's "needs dynamite"
    for room 10 is this. None of the five water rooms has a '.' in its floor,
    which is why every room past 9 is left by a side."""
    for room in range(10, 15):
        assert "." not in BANDS[room]["C"], f"room {room} floor has a real hole"


def test_a_liquid_cell_is_solid_only_on_the_rows_it_is_drawn_on():
    y0, y1 = common.LIQUID_ROWS
    for room in range(10, 15):
        liquid_x = {8 + 4 * i for i, c in enumerate(BANDS[room]["C"]) if c == "~"}
        for x, y, w, h in HL.WALL_RECTS_L9[room]:
            if x in liquid_x and y >= 99:
                assert (y, h) == (y0, y1 - y0 + 1), (
                    f"room {room}: the liquid rect at x {x} is {h} px tall "
                    f"from row {y}; it must be rows {y0}-{y1}")


def test_the_deadly_rects_are_the_water_line():
    """DEADLY is the lethal surface, the pixels the ROM draws off the rock
    ramp: level 9's water is BLUE (#2d32b8) in a brown cave. Room 15 carries
    a three-row strip under its solid floor, as level 8's room 13 does - it
    is drawn, it sits under 40 px of rock, and nothing can reach it."""
    rooms = {r for r, _x, _y, _w, _h in HL.DEADLY[L - 1]}
    assert rooms == {10, 11, 12, 13, 14, 15}
    for room, x, y, w, h in HL.DEADLY[L - 1]:
        assert y + h - 1 <= 141, "the surface cannot reach past the floor band"
        if room != 15:
            assert (y, h) == (136, 6), f"room {room} water is not the 136-141 line"
    assert (15, 8, 139, 152, 3) in HL.DEADLY[L - 1]
    assert common.rgb("#2d32b8") in HL.PALETTE_L9


def test_the_two_long_walls_stand_over_water_and_are_flown_under():
    """Room 13's eight-cell wall and room 14's sixteen-cell one are far too
    wide for a stick, and the ceiling is solid - but every cell under them is
    '~', which is AIR from row 99 to 135. The way on is underneath, over the
    water; the recorded playthrough flies it (level_09 frames 176-191)."""
    for room in (13, 14):
        (first, last), = [r for r in runs_of(BANDS[room]["B"]) if r[1] - r[0] > 2]
        assert set(BANDS[room]["C"][first:last + 1]) == {"~"}, f"room {room}"
        x, w = cells(first, last)
        assert not any(r == room and rx == x for r, rx, *_ in HL.DESTRUCTIBLE[L - 1])


# --- magma ------------------------------------------------------------------
def test_magma_is_in_every_room_down_to_ten_and_none_below():
    """Magma is a property of the ROOM: the corridor colour register is either
    the level hue or magma red. Rooms 0-10 are red; the five past the water
    have none."""
    with_magma = {i for i, r in enumerate(BANDS) if "%" in r["B"]}
    assert with_magma == set(range(11))
    for room in range(11, 16):
        assert "%" not in "".join(BANDS[room].values())
    for room in range(11):
        assert "#" not in BANDS[room]["B"], \
            f"room {room}: in a magma room every solid corridor cell is magma"


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


def test_magma_never_leaves_the_corridor_band():
    for _room, _x, y, _w, h in HL.MAGMA[L - 1]:
        assert (y, h) == (60, 39), "magma is a corridor register, not a band"


# --- dynamite ---------------------------------------------------------------
def test_the_blastable_pillars_are_the_two_cell_ones():
    """Only a run of exactly two cells breaks, never one that reaches the side
    of the screen - magma the same as rock."""
    want = []
    for i, room in enumerate(BANDS):
        for first, last in runs_of(room["B"], "#") + runs_of(room["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            want.append((i, first, last))
    got = {(r, (x - 8) // 4, (x - 8) // 4 + w // 4 - 1)
           for r, x, _y, w, _h, _n in HL.DESTRUCTIBLE[L - 1]}
    assert got == set(want)
    assert len(want) == 7


def test_three_sticks_are_needed_to_reach_the_miner():
    """Rooms 11, 12 and 13 each stand a two-cell pillar between the hero and
    the way on, with solid rock ABOVE it (the ceiling) and BELOW it (the
    floor under a pillar is rock, not water), so it can be neither flown over
    nor under. The walker blew all three to reach room 15."""
    for room, (first, last) in ((11, (34, 35)), (12, (17, 18)), (13, (34, 35))):
        assert BANDS[room]["B"][first:last + 1] == "##"
        assert BANDS[room]["A"] == "#" * 38, "nothing to fly over"
        assert set(BANDS[room]["C"][first:last + 1]) == {"#"}, "nothing to fly under"
        x, w = cells(first, last)
        assert (room, x, 60, w, 39, 1) in HL.DESTRUCTIBLE[L - 1]


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    for room, x, y, _w, h, _n in HL.DESTRUCTIBLE[L - 1]:
        first = (x - 8) // 4
        same = (first, first + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if same else (60, 39)), f"room {room} at x {x}"
        assert same == (room == 0)


def test_the_shared_wall_table_is_empty():
    common.check_shared_walls(L)


def test_nothing_flares():
    """FLARES is not derivable from a still capture. The six rows this level
    carried were authored on the superseded reference."""
    assert HL.FLARES[L - 1] == []


# --- the way down -----------------------------------------------------------
def test_the_side_exits_are_the_open_corridor_edges():
    want = set()
    for i, room in enumerate(BANDS):
        if room["B"][0] == ".":
            want.add((i, -1))
        if room["B"][37] == ".":
            want.add((i, 1))
    assert {(r, s) for r, s, _d in HL.SIDE_EXITS[L - 1]} == want


def test_level_9_descends_through_right_edges():
    """A side exit's direction is DATA. Level 8 descended through LEFT edges;
    level 9 goes RIGHT from room 10 to room 15, and every left edge from room
    11 on leads back up."""
    by_room = {}
    for room, side, delta in HL.SIDE_EXITS[L - 1]:
        by_room.setdefault(room, {})[side] = delta
    assert by_room[10] == {1: 1}
    for room in range(11, 15):
        assert by_room[room] == {-1: -1, 1: 1}, f"room {room}"
    assert by_room[15] == {-1: -1}, "the last room leads nowhere but back"


def test_every_room_but_the_last_has_a_way_on():
    for i, room in enumerate(BANDS[:-1]):
        down = "." in room["C"]
        side = any(r == i and d == 1 for r, _s, d in HL.SIDE_EXITS[L - 1])
        assert down or side, f"room {i} has no way on"


# --- entities ---------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)


def test_every_entity_in_characters_md_is_present():
    """CHARACTERS.md's level 9 table is exactly what the game ships: every
    lantern, every creature at its kind, x and y, and the miner - and not one
    creature more."""
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    want_lanterns = {(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "lantern"}
    assert lanterns == want_lanterns
    want = {(r, w, x, y) for r, w, x, y in CHARACTERS_MD if w not in ("lantern", "miner")}
    assert shipped() == want
    (miner,) = [(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "miner"]
    assert HL.MINER_POS[L - 1] == miner


def test_every_old_census_row_is_still_honoured():
    """The superseded census, row for row: each is shipped at its own x, with
    the kind and row the live ROM draws (SHIPPED_AS) - and for the movers the
    census's row is one frame of the bob, inside the shipped box."""
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    got = shipped()
    for row in OLD_CENSUS:
        room, what, x, y = row
        if what == "lantern":
            assert (room, x, y) in lanterns
            continue
        what, sx, sy = SHIPPED_AS.get(row, (what, x, y))
        assert sx == x
        assert (room, what, sx, sy) in got, f"{what} {room} {sx},{sy} missing"
        if what in ("bat", "spider_free"):
            assert sy <= y <= sy + 7 + 11


def test_the_creatures_the_old_census_never_saw():
    got = shipped()
    n = len(OLD_CENSUS) - len(HL.LANTERNS[L - 1])
    for room, entities in NOT_IN_CENSUS.items():
        for what, x, y in entities:
            if what == "miner":
                assert HL.MINER_POS[L - 1] == (room, x, y)
            else:
                assert (room, what, x, y) in got, f"room {room} {what} missing"
                n += 1
    assert n == len(HL.SPIDERS[L - 1]), "a creature is in neither table"


def test_nothing_was_invented_in_room_0_or_room_4():
    """Neither the census nor the ROM draws a creature in rooms 0 and 4."""
    assert not any(r in (0, 4) for r, *_ in HL.SPIDERS[L - 1])
    assert not any(r == 0 for r, *_ in HL.LANTERNS[L - 1])


def test_the_lanterns_hang_in_the_ceiling_band_on_row_35():
    assert len(HL.LANTERNS[L - 1]) == 10
    assert {r for r, *_ in HL.LANTERNS[L - 1]} == set(range(1, 11))
    for _room, _x, y in HL.LANTERNS[L - 1]:
        assert y == 35, "every lantern in the game hangs on row 35"


def test_the_miner_is_in_the_last_room():
    """At x 128 - one pixel left of the 129 the old RAM-teleport scan gave,
    the same correction as level 7's."""
    common.check_miner(L, BANDS)
    assert HL.MINER_POS[L - 1] == (15, 128, 86)


def test_the_snake_is_anchored_in_rock_on_its_left():
    snakes = [(r, x, y) for r, x, y, _h, k in HL.SPIDERS[L - 1] if k == 3]
    assert snakes == [(12, 88, 111)]
    room, x, y = snakes[0]
    assert BANDS[room]["C"][(x - 8) // 4 - 1] == "#", \
        "room 12's snake grows out of the rock between its two waters"


def test_the_five_bats_patrol_22_px_on_184_frames_and_hold_a_pose_4():
    """A bat's two clocks: it sweeps 22 px on 184 frames and bobs 7 px on
    64, holding each wing pose 4 frames. The three in the magma rooms were
    measured over a 2000-frame watch; 480 frames put them at 180."""
    bats = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 1]
    assert [c[0] for _i, c in bats] == [5, 9, 10, 11, 13]
    for slot, (_room, _x, _y, half, _k) in bats:
        assert 2 * half == 22
        assert 2 * HL.CREATURE_PATROL[(L, slot)] == 184
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 64, 4)


def test_the_untethered_spiders_bob_7_px_on_64_frames():
    free = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 4]
    assert [c[0] for _i, c in free] == [1, 3, 8]
    for slot, (_room, _x, _y, half, _k) in free:
        assert half == 0, "it bobs; it does not patrol"
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 64, 8)


def test_the_hanging_spiders_are_still():
    """Whether a creature moves is a property of the room. Every hanging
    spider on level 9 - three in the floor band, seven in the corridor - is
    still: no patrol, no bob, and two poses on an 8-frame hold."""
    hanging = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 0]
    assert len(hanging) == 10
    for slot, (_room, _x, _y, half, _k) in hanging:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 8)
        assert (L, slot) not in HL.CREATURE_SPRITES, "both poses are drawn"


def test_exactly_the_bats_and_the_untethered_spiders_move():
    movers = {i for i, c in enumerate(HL.SPIDERS[L - 1])
              if c[3] or HL.CREATURE_MOTION[(L, i)][0]}
    assert movers == {i for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] in (1, 4)}
    assert len(movers) == 8


# --- rendering --------------------------------------------------------------
def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black."""
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    state = state.replace(level=jnp.int32(L - 1), room=jnp.int32(10))
    frame = np.asarray(env.render(state))
    assert frame[189:210].max() == 0, "something is drawn where the logo was"


def test_room_0_paints_the_levels_own_brown():
    """Level 9 is brown, the same hue as the boot palette the ROM leaves in
    place on room 0, so here the recolour is the identity."""
    _palette, rooms = common.level_data(L)
    for role in ("dark", "mid", "light"):
        r, g, b = common.rgb(HL.SHADES[L][role])
        assert (rooms[0] == np.array([r, g, b])).all(axis=-1).any(), (
            f"room 0 never paints its {role}")

