"""Level 13, against the corrected ROM reference.

The block in hero_levels.py is generated by a level builder that walks
the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), and check the engine draws it.

What came out of level 13:

  * THE WALK REACHES ALL SIXTEEN ROOMS. The old reference had it at 9 (rooms
    0-8, rooms 7 and 8 read off the playthrough). Room 6 has a solid floor
    and is left through its open RIGHT edge; room 9 through its LEFT one, and
    from there the level descends LEFT to the miner in room 15.
  * TWO PLAYTHROUGH BANDS WERE WRONG. Room 7's right-edge wall is MAGMA ('%%',
    the reference had '##'), and room 8's ceiling hole is four cells wide - the
    reference had an uncalled '?' in it. The ROM wins; the reference was
    corrected before the rest of the walk was appended.
  * ITS CREATURES RUN AT LEVEL 10'S SPEED: all thirteen bats sweep 22 px on 92
    frames, everything that bobs bobs 7 px on 32; bats hold a wing pose 4
    frames, spiders 8. All six hanging spiders are still. No snakes.
  * THE LIQUID IS THE BLUE THE LEVEL FILE GIVES, #2d32b8: the ROM paints it on
    rows 136-141 of rooms 11-15 and on the three-row strip 139-141 under
    room 10's solid rock floor, and nowhere else.
  * ROOM 12's BAT KILLED THE READING HERO. The room has no park off the
    picture, so it is read with the hero standing at (16, 73) - inside the
    bat's sweep (x 16-45). He died to it in the first frames of the read,
    with lives pinned, and the ROM removes the creature that kills you: the
    first capture had no bat, and the room-12 spider came out as one frozen
    pose. The playthrough shows the bat flapping there (level_13 frames
    196-212). The capture now tests an on-screen park from the ARRIVAL frame
    and re-watches such a room from parks that do not kill - (44, 73) and
    (152, 73) - taking each creature from the capture that saw it clear of
    the hero (_merge_clean).
  * The census is the lethal-park kind: it saw rooms 0-6, with the
    hero dying in their left-edge magma, and has five rows. All five are
    honoured; the capture has 19 more creatures than it does.

The shape of the level, room by room:

    rooms 0-7   BROWN, magma in every corridor, holes in the floor except
                room 6 (open right edge). Room 1's two-cell magma pillar at
                cells 6-7, and room 3's and room 4's at 17-18, take a stick.
    room 7      entered sideways from room 6; its left edge leads back up.
    room 8      ROCK, the one room of 0-9 with no magma.
    room 9      sealed floor, open LEFT edge: the way on.
    room 10     sealed ceiling and floor (a three-row water strip UNDER the
                rock), a two-cell magma pillar at 17-18: a stick.
    room 11     the same pillar standing on rock between two waters: a stick.
    room 12     a SIX-cell magma wall at 15-20 over the water, crossed on the
                RAFT (HL.RAFTS): it waits at x 124 and carries the hero left -
                the playthrough rides it, frames 198-208.
    room 13     the two-cell magma pillar at 17-18 on rock: a stick.
    room 14     no wall at all: an open corridor over two pools.
    room 15     the miner's room: rock at the left edge, water under the
                middle, two bats and the miner at x 25.
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

L = 13

# What the ROM draws, cell for cell, in descent order, verified against
# the reference before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "%%...........%%...................%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%....%%....%%%......%%%..........%%%%",
     "C": "###..####..#####....#####..####..#####"},
    {"A": "###..####..#####....#####..####..#####",
     "B": "%%%..%%%....................%%%..%%%%%",
     "C": "##....########################....####"},
    {"A": "##....########################....####",
     "B": "%%%..............%%..............%%%%%",
     "C": "########..################..##########"},
    {"A": "########..################..##########",
     "B": "%%%%%%...........%%...........%%%%%%%%",
     "C": "##......####################......####"},
    {"A": "##......####################......####",
     "B": "%%%%....%%%%%%%%%%%%%%%%%%%%....%%%%%%",
     "C": "##....########################....####"},
    {"A": "##....########################....####",
     "B": "%%......%%%%%%%%%%%%%%%%%%%%..........",
     "C": "######################################"},
    {"A": "######################################",
     "B": "....................................%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "##................................####",
     "C": "#########..##############..###########"},
    {"A": "#########..##############..###########",
     "B": "....................................%%",
     "C": "######################################"},
    {"A": "######################################",
     "B": ".................%%...................",
     "C": "######################################"},
    {"A": "######################################",
     "B": ".................%%...................",
     "C": "####~~~~~~~~~~~######~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": "...............%%%%%%.................",
     "C": "####~~~~~~~~~~~~~~~~~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": ".................%%...................",
     "C": "####~~~~~~~~~~~~####~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": "......................................",
     "C": "##########~~~~########~~~~############"},
    {"A": "######################################",
     "B": "##....................................",
     "C": "##########~~~~~~~~~~~~~~~~############"},
]

# The live-hero ROM capture (the data hero_levels.py ships), as
# (room, what, x, y) with x the LEFT edge of the drawn box - for a bat, of
# its sweep. Every row.
CHARACTERS_MD = [
    (1, "lantern", 83, 35), (1, "spider", 20, 70), (1, "spider", 108, 109),
    (2, "lantern", 47, 35), (2, "bat", 48, 64),
    (3, "lantern", 27, 35), (3, "bat", 32, 64),
    (4, "lantern", 43, 35), (4, "bat", 84, 64),
    (5, "lantern", 139, 35), (5, "spider_free", 128, 66), (5, "spider", 136, 110),
    (6, "lantern", 139, 35), (6, "spider_free", 136, 66),
    (7, "bat", 40, 64), (7, "spider_free", 80, 104),
    (8, "lantern", 83, 35), (8, "spider", 56, 70), (8, "spider_free", 108, 104),
    (9, "lantern", 47, 35), (9, "bat", 16, 64),
    (10, "bat", 96, 64),
    (11, "spider", 60, 70), (11, "bat", 96, 103),
    (12, "bat", 16, 64), (12, "spider", 76, 109),
    (13, "bat", 44, 64), (13, "bat", 92, 103),
    (14, "bat", 64, 64), (14, "spider_free", 100, 104),
    (15, "bat", 61, 64), (15, "bat", 61, 103), (15, "miner", 25, 86),
]

# The CENSUS table carried for this level before 2026-09-24
# (rooms 0-6 scanned, five entities), kept as the record of what the lethal
# reading park did to it. Every row of it is shipped exactly as it stands.
OLD_CENSUS = [
    (1, "lantern", 83, 35),
    (1, "spider", 108, 109),
    (2, "lantern", 47, 35),
    (3, "lantern", 27, 35),
    (4, "lantern", 43, 35),
]

# What the ROM draws that the old census has no row for, as (what, x, y).
# Rooms 1-6: hidden from it by its lethal park. Rooms 7-15: never reached.
NOT_IN_CENSUS = {
    1: [("spider", 20, 70)],
    2: [("bat", 48, 64)],
    3: [("bat", 32, 64)],
    4: [("bat", 84, 64)],
    5: [("lantern", 139, 35), ("spider_free", 128, 66), ("spider", 136, 110)],
    6: [("lantern", 139, 35), ("spider_free", 136, 66)],
    7: [("bat", 40, 64), ("spider_free", 80, 104)],
    8: [("lantern", 83, 35), ("spider", 56, 70), ("spider_free", 108, 104)],
    9: [("lantern", 47, 35), ("bat", 16, 64)],
    10: [("bat", 96, 64)],
    11: [("spider", 60, 70), ("bat", 96, 103)],
    12: [("bat", 16, 64), ("spider", 76, 109)],
    13: [("bat", 44, 64), ("bat", 92, 103)],
    14: [("bat", 64, 64), ("spider_free", 100, 104)],
    15: [("bat", 61, 64), ("bat", 61, 103), ("miner", 25, 86)],
}

KIND_NAME = {0: "spider", 1: "bat", 3: "snake", 4: "spider_free"}
MAGMA_ROOMS = set(range(8)) | {9, 10, 11, 12, 13}


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


def shipped():
    """{(room, what, left x, top y)} for every creature SPIDERS carries."""
    return {(r, KIND_NAME[k], x - half, y)
            for r, x, y, half, k in HL.SPIDERS[L - 1]}


# --- geometry ---------------------------------------------------------------
def test_level_13_is_sixteen_brown_rooms():
    common.check_shape(L, "brown", rooms=16)
    assert len(HL.BG_RLE_L13) == 16


def test_all_sixteen_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_the_level_is_complete_and_nothing_is_missing():
    """The old reference listed level 13 as 9 of 16 rooms. The other seven were
    reached on 2026-09-24 by the walker's side exits (rooms 9-14)."""
    assert len(BANDS) == 16
    assert len({(b["A"], b["B"], b["C"]) for b in BANDS}) == 16, \
        "no ROOM is a copy of another"


def test_the_two_playthrough_bands_are_the_roms():
    """Room 7's right wall is magma, not rock; room 8's ceiling hole has no
    uncalled cell - it is four cells wide, the width of room 7's floor hole."""
    assert BANDS[7]["B"] == "." * 36 + "%%"
    assert BANDS[8]["A"] == "#" * 16 + "...." + "#" * 18
    assert BANDS[8]["A"] == BANDS[7]["C"]


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_where_the_level_goes_down_through_holes():
    """Room N's ceiling is drawn identically to room N-1's floor when N is
    entered through a hole. Room 7 is entered SIDEWAYS (from room 6's open
    right edge), as are rooms 10-15, all under a ceiling that is solid across
    the whole screen."""
    sideways = {7, 10, 11, 12, 13, 14, 15}
    for i in range(1, 16):
        if i in sideways:
            assert BANDS[i]["A"] == "#" * 38, f"room {i}"
        else:
            assert BANDS[i]["A"] == BANDS[i - 1]["C"].replace("~", "#"), \
                f"chain breaks between rooms {i - 1} and {i}"


def test_no_cell_was_left_uncalled():
    for i, room in enumerate(BANDS):
        for band, s in room.items():
            assert "?" not in s, f"room {i} band {band} has an uncalled cell"
            assert set(s) <= set("#%.~"), f"room {i} band {band} has a stray value"


# --- the water --------------------------------------------------------------
def test_the_five_pool_rooms_are_the_only_liquid_cells():
    with_liquid = {i for i, r in enumerate(BANDS) if "~" in r["C"]}
    assert with_liquid == {11, 12, 13, 14, 15}


def test_the_water_rooms_have_no_hole_to_fall_through():
    for room in range(10, 16):
        assert "." not in BANDS[room]["C"], f"room {room} floor has a real hole"


def test_a_liquid_cell_is_solid_only_on_the_rows_it_is_drawn_on():
    y0, y1 = common.LIQUID_ROWS
    for room in range(11, 16):
        liquid_x = {8 + 4 * i for i, c in enumerate(BANDS[room]["C"]) if c == "~"}
        for x, y, w, h in HL.WALL_RECTS_L13[room]:
            if x in liquid_x and y >= 99:
                assert (y, h) == (y0, y1 - y0 + 1), (
                    f"room {room}: the liquid rect at x {x} is {h} px tall "
                    f"from row {y}; it must be rows {y0}-{y1}")


def test_the_deadly_rects_are_the_water_line():
    """Rooms 11-15 carry the water on rows 136-141; room 10 has only the
    three-row strip 139-141 under its solid rock floor, like level 11's
    room 15."""
    assert HL.DEADLY[L - 1] == [(10, 8, 139, 152, 3)] + [
        (room, 8, 136, 152, 6) for room in range(11, 16)]


def test_the_liquid_is_the_blue_the_level_file_gives():
    """The level file says #2d32b8 for level 13, and the ROM agrees: it
    paints (45, 50, 184) on the water rows of rooms 10-15 and nowhere else."""
    palette, rooms = common.level_data(L)
    liquid = common.rgb("#2d32b8")
    assert liquid in palette
    for i, img in enumerate(rooms):
        ys, _xs = np.nonzero((img == np.array(liquid)).all(axis=-1))
        if i >= 10:
            assert ys.size and ys.min() >= (139 if i == 10 else 136), f"room {i}"
        else:
            assert not ys.size, f"room {i} paints the liquid colour"


def test_no_rotor_yellow_is_painted_into_the_cave():
    """Room 12's yellow bar on the water is the RAFT (HL.RAFTS), drawn by the
    engine where it currently is: the playthrough shows it waiting at x 124
    (frames 198-200) and carrying the hero left under the magma wall (202-
    208). Neither it nor the x = 0 park's rotor tip is in any background."""
    _palette, rooms = common.level_data(L)
    rotor = np.array(common.rgb("#e8e84a"))
    for i, img in enumerate(rooms):
        ys, xs = np.nonzero((img == rotor).all(axis=-1))
        assert not ys.size, f"room {i} paints rotor yellow at {xs[0]},{ys[0]}"
    assert HL.RAFTS[L - 1] == [(12, 124)]


def test_room_12s_wall_is_crossed_on_the_raft():
    """Six cells of magma, three times what a stick takes, under a solid
    ceiling - but every cell under it is '~', AIR from row 99 to 135."""
    assert (15, 20) in runs_of(BANDS[12]["B"], "%")
    assert BANDS[12]["A"] == "#" * 38
    assert set(BANDS[12]["C"][15:21]) == {"~"}
    assert not any(r == 12 for r, *_ in HL.DESTRUCTIBLE[L - 1])


# --- magma ------------------------------------------------------------------
def test_magma_is_in_every_room_down_to_13_but_room_8():
    """Magma is a property of the ROOM: the corridor colour register is either
    the level hue or magma red. In a magma room every solid corridor cell is
    magma; rooms 8 and 15 are rock and room 14 has no corridor wall."""
    with_magma = {i for i, r in enumerate(BANDS) if "%" in "".join(r.values())}
    assert with_magma == MAGMA_ROOMS
    for room in with_magma:
        assert "#" not in BANDS[room]["B"], \
            f"room {room}: in a magma room every solid corridor cell is magma"
    for room in (8, 15):
        assert "%" not in BANDS[room]["B"] and "#" in BANDS[room]["B"]
    assert BANDS[14]["B"] == "." * 38


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


def test_magma_never_leaves_the_corridor_band():
    for _room, _x, y, _w, h in HL.MAGMA[L - 1]:
        assert (y, h) == (60, 39), "magma is a corridor register, not a band"


def test_no_magma_is_carried_as_a_creature_any_more():
    """Level 13 was the last level still carrying magma as kind-2 rows in
    SPIDERS; the capture emits it as MAGMA rects from the '%' cells."""
    assert not any(row[4] == 2 for row in HL.SPIDERS[L - 1])


# --- dynamite ---------------------------------------------------------------
def test_the_blastable_pillars_are_the_two_cell_ones():
    """Only a run of exactly two cells breaks, never one that reaches the side
    of the screen - magma the same as rock."""
    want = []
    for i, room in enumerate(BANDS):
        for first, last in runs_of(room["B"], "#") + runs_of(room["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            want.append((i, first, last))
    got = {(r, (x - 8) // 4, (x - 8) // 4 + w // 4 - 1)
           for r, x, _y, w, _h, _n in HL.DESTRUCTIBLE[L - 1]}
    assert got == set(want)
    assert len(want) == 7


def test_rooms_10_11_and_13_each_take_a_stick():
    """A two-cell magma pillar at cells 17-18 with solid rock ABOVE it (the
    ceiling) and BELOW it, so it can be neither flown over nor under, between
    the hero - who arrives at the right edge - and the left edge that leads
    on."""
    for room in (10, 11, 13):
        assert BANDS[room]["B"][17:19] == "%%"
        assert BANDS[room]["A"] == "#" * 38, "nothing to fly over"
        assert set(BANDS[room]["C"][17:19]) == {"#"}, "nothing to fly under"
        x, w = cells(17, 18)
        assert (room, x, 60, w, 39, 1) in HL.DESTRUCTIBLE[L - 1]


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    for room, x, y, _w, h, _n in HL.DESTRUCTIBLE[L - 1]:
        first = (x - 8) // 4
        same = (first, first + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if same else (60, 39)), f"room {room} at x {x}"
        assert same == (room == 0)


def test_the_shared_wall_table_is_empty():
    common.check_shared_walls(L)


def test_nothing_flares():
    """FLARES is not derivable from a still capture, and the capture finds no
    periodic eruption in any room of the level. (The four rows the old block
    carried were authored on top of the superseded reference.)"""
    assert HL.FLARES[L - 1] == []


# --- the way down -----------------------------------------------------------
def test_the_side_exits_are_the_open_corridor_edges():
    want = set()
    for i, room in enumerate(BANDS):
        if room["B"][0] == ".":
            want.add((i, -1))
        if room["B"][37] == ".":
            want.add((i, 1))
    assert {(r, s) for r, s, _d in HL.SIDE_EXITS[L - 1]} == want


def test_level_13_descends_right_once_then_left():
    """A side exit's direction is DATA. Room 6 goes on through its RIGHT edge
    and room 7 leads back through its left; from room 9 the level goes LEFT
    and every right edge leads back up."""
    by_room = {}
    for room, side, delta in HL.SIDE_EXITS[L - 1]:
        by_room.setdefault(room, {})[side] = delta
    assert by_room[6] == {1: 1} and by_room[7] == {-1: -1}
    assert by_room[9] == {-1: 1}
    for room in range(10, 15):
        assert by_room[room] == {-1: 1, 1: -1}, f"room {room}"
    assert by_room[15] == {1: -1}, "the last room leads nowhere but back"


def test_every_room_but_the_last_has_a_way_on():
    for i, room in enumerate(BANDS[:-1]):
        down = "." in room["C"]
        side = any(r == i and d == 1 for r, _s, d in HL.SIDE_EXITS[L - 1])
        assert down or side, f"room {i} has no way on"


# --- entities ---------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)


def test_every_entity_in_the_live_capture_is_present():
    """Every lantern, every creature at its kind, x and y, and the miner -
    and not one creature more."""
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    want_lanterns = {(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "lantern"}
    assert lanterns == want_lanterns
    want = {(r, w, x, y) for r, w, x, y in CHARACTERS_MD if w not in ("lantern", "miner")}
    assert shipped() == want
    (miner,) = [(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "miner"]
    assert HL.MINER_POS[L - 1] == miner


def test_every_old_census_row_is_shipped_as_it_stands():
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    got = shipped()
    for room, what, x, y in OLD_CENSUS:
        if what == "lantern":
            assert (room, x, y) in lanterns
        else:
            assert (room, what, x, y) in got, f"{what} {room} {x},{y} missing"


def test_the_entities_the_old_census_never_saw():
    got = shipped()
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    n = sum(1 for _r, w, _x, _y in OLD_CENSUS if w != "lantern")
    for room, entities in NOT_IN_CENSUS.items():
        for what, x, y in entities:
            if what == "miner":
                assert HL.MINER_POS[L - 1] == (room, x, y)
            elif what == "lantern":
                assert (room, x, y) in lanterns
            else:
                assert (room, what, x, y) in got, f"room {room} {what} missing"
                n += 1
    assert n == len(HL.SPIDERS[L - 1]) == 24, "a creature is in neither table"


def test_nothing_was_invented_in_room_0():
    """Neither the census nor the ROM draws a creature or a lamp in room 0."""
    assert not any(r == 0 for r, *_ in HL.SPIDERS[L - 1])
    assert not any(r == 0 for r, *_ in HL.LANTERNS[L - 1])


def test_the_lanterns_hang_in_the_ceiling_band_on_row_35():
    assert len(HL.LANTERNS[L - 1]) == 8
    assert {r for r, *_ in HL.LANTERNS[L - 1]} == {1, 2, 3, 4, 5, 6, 8, 9}
    for _room, _x, y in HL.LANTERNS[L - 1]:
        assert y == 35, "every lantern in the game hangs on row 35"


def test_the_miner_is_in_the_last_room():
    common.check_miner(L, BANDS)
    assert HL.MINER_POS[L - 1] == (15, 25, 86)


def test_room_12_has_its_bat():
    """The bat that killed the reading hero (see the module docstring): it
    sweeps x 16-45 on row 64 at the level's speed, and the spider under the
    magma wall flips its two poses like every other hanging spider."""
    bat = HL.SPIDERS[L - 1].index((12, 27, 64, 11, 1))
    assert HL.CREATURE_PATROL[(L, bat)] == 46
    assert HL.CREATURE_MOTION[(L, bat)] == (7, 16, 4)
    spider = HL.SPIDERS[L - 1].index((12, 76, 109, 0, 0))
    assert HL.CREATURE_MOTION[(L, spider)] == (0, 0, 8)
    assert (L, spider) not in HL.CREATURE_SPRITES


def test_the_thirteen_bats_patrol_22_px_on_92_frames_and_hold_a_pose_4():
    """Level 10's speed, the same distances and the same pose hold."""
    bats = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 1]
    assert [c[0] for _i, c in bats] == [2, 3, 4, 7, 9, 10, 11, 12, 13, 13, 14, 15, 15]
    for slot, (_room, _x, _y, half, _k) in bats:
        assert 2 * half == 22
        assert 2 * HL.CREATURE_PATROL[(L, slot)] == 92
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 32, 4)


def test_the_untethered_spiders_bob_7_px_on_32_frames():
    free = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 4]
    assert [c[0] for _i, c in free] == [5, 6, 7, 8, 14]
    for slot, (_room, _x, _y, half, _k) in free:
        assert half == 0, "it bobs; it does not patrol"
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 32, 8)


def test_the_hanging_spiders_are_still():
    """Whether a creature moves is a property of the room. Level 13's six
    hanging spiders - in the floor band and in the corridor - are all still:
    no patrol, no bob, and two poses on an 8-frame hold."""
    hanging = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 0]
    assert [(c[0], c[1], c[2]) for _i, c in hanging] == [
        (1, 20, 70), (1, 108, 109), (5, 136, 110), (8, 56, 70),
        (11, 60, 70), (12, 76, 109)]
    for slot, (_room, _x, _y, half, _k) in hanging:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 8)
        assert (L, slot) not in HL.CREATURE_SPRITES, "both poses are drawn"


def test_exactly_the_bats_and_the_untethered_spiders_move():
    movers = {i for i, c in enumerate(HL.SPIDERS[L - 1])
              if c[3] or HL.CREATURE_MOTION[(L, i)][0]}
    assert movers == {i for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] in (1, 4)}
    assert len(movers) == 18


def test_the_engine_draws_the_bats_on_the_rom_clock(env):
    """Not just the tables: the engine's creature positions over 184 frames
    sweep 23 columns (22 px of travel) and repeat every 92 frames, and the
    bob repeats every 32 - room 12's bat."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((12, 27, 64, 11, 1))
    xs, ys = [], []
    for t in range(0, 184):
        x, y = _creature_pos(c, jnp.int32(L - 1), jnp.int32(t))
        xs.append(int(x[slot])); ys.append(int(y[slot]))
    assert max(xs) - min(xs) == 22 and max(ys) - min(ys) == 7
    assert xs[:92] == xs[92:184], "the sweep is a 92-frame cycle"
    assert ys[:32] == ys[32:64] == ys[64:96], "the bob is a 32-frame cycle"


# --- rendering --------------------------------------------------------------
def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black."""
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    state = state.replace(level=jnp.int32(L - 1), room=jnp.int32(12))
    frame = np.asarray(env.render(state))
    assert frame[189:210].max() == 0, "something is drawn where the logo was"


def test_room_0_paints_the_levels_own_brown():
    """Level 13 is brown like level 1, so the ROM's boot palette happens to be
    right here; room 0 must still paint all three of the level's shades."""
    _palette, rooms = common.level_data(L)
    for role in ("dark", "mid", "light"):
        r, g, b = common.rgb(HL.SHADES[L][role])
        assert (rooms[0] == np.array([r, g, b])).all(axis=-1).any(), (
            f"room 0 never paints its {role}")
