"""Level 7, against the corrected ROM reference.

The block in hero_levels.py is generated by tools/hero_gen/build_level.py,
which walks the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), then play the level.

Level 7 is the first level past the six CORRECTIONS.md calls complete, and
the first one where the walker had to be TAUGHT something before it finished.
Three things came out of it, and each has a test below:

  * THE WALK NOW REACHES ALL TWELVE ROOMS. It used to stop at room 10, whose
    floor is `~` from end to end - the lethal liquid surface, not a hole. Room
    10's corridor reaches the RIGHT edge of the screen as open air, and that
    edge is the way on; the hero just cannot WALK to it, because with liquid
    under him he falls in first. Holding the rotor gets him there in 68
    frames. `hero_extract.py rooms 7` now reports 12 of 12, and room 11 - the
    miner's - agrees cell for cell with what the recorded playthrough draws in
    frames 190 to 210.
  * A SIDE EXIT'S DIRECTION IS DATA. Level 5 descends through a LEFT edge and
    level 7 descends through a RIGHT one, so "left is down and right is up",
    which the engine used to hardcode, is right for one level and backwards
    for the other. SIDE_EXITS now carries (room, side, delta).
  * A LIQUID CELL IS AIR ABOVE ITS SURFACE. `~` is drawn only on rows 136-141
    and is black from row 99 down to 135, and the ROM hangs creatures in that
    gap. Counting the whole cell as solid hid room 10's spider - CHARACTERS.md
    has it at (72, 109) - from the sprite pass, and it came back as part of
    the room's DEADLY rect instead of as a creature.

Magma is in the six EVEN rooms, and in each of them every solid corridor cell
is magma, because the corridor colour register is either the level hue or
magma red and nothing in between.

The route, room by room:

    room 0  magma corridor, blocked by the pillar at x 60-67 whose ceiling is
            the same pillar -> plant a stick, run, +75, then down the hole at
            x 72-87
    room 1  a lantern and a still spider at x 52; the pillar at x 92-99 and
            holes at x 24-31 and x 128-135
    room 2  magma, a lantern, the pillar at x 60-67, the hole at x 76-83
    room 3  a lantern and a SNAKE at x 48 growing out of the rock; the pillar
            at x 64-71 and holes at x 52-59 and x 104-111
    room 4  magma down both sides and a twelve-cell magma slab in the middle -
            too wide to blast, so it is flown around; holes at x 24-39 and
            x 120-135
    room 5  a lantern at x 131, a still spider at x 60 and the level's one
            PATROLLING bat sweeping 22 px across the floor band; the pillar at
            x 100-107 and holes at x 16-39 and x 128-143
    room 6  magma at both edges and a sixteen-cell magma slab in the middle;
            a lantern, a still creature at x 24 and holes at x 16-27 and
            x 124-135
    room 7  a lantern, a snake at x 28, a still spider at x 80; the pillar at
            x 100-107 and the hole at x 72-87
    room 8  magma, a lantern, the pillar at x 60-67, holes at x 32-47 and
            x 116-131
    room 9  a lantern, a still spider at x 76, the pillar at x 100-107 and
            holes at x 64-71 and x 88-95
    room 10 THE WATER ROOM: one magma cell at the left edge, a lantern, a
            still spider at x 72, and a floor that is liquid from x 32 to
            x 127. No way down at all - the way on is the open RIGHT edge of
            the corridor, and it has to be flown to.
    room 11 the miner's room: sealed floor and ceiling, one bobbing creature
            at x 76 and the miner at x 128. Its own open LEFT edge leads back
            up to room 10.
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

NOOP, FIRE, UP, RIGHT, LEFT, DOWN = 0, 1, 2, 3, 4, 5
L = 7

# What the ROM draws, cell for cell, in descent order. Generated by
# tools/hero_gen/build_level.py and verified by it against
# level_images/hero_rooms.py before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "%%%..........%%..................%%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "###..................##..........#####",
     "C": "####..########################..######"},
    {"A": "####..########################..######",
     "B": "%%...........%%...................%%%%",
     "C": "#################..###################"},
    {"A": "#################..###################",
     "B": "##########....##..........############",
     "C": "###########..##########..#############"},
    {"A": "###########..##########..#############",
     "B": "%%%%%%........%%%%%%%%%%%%........%%%%",
     "C": "####....####################....######"},
    {"A": "####....####################....######",
     "B": "######.................##.....########",
     "C": "##........################........####"},
    {"A": "##........################........####",
     "B": "%%%%%%%%....%%%%%%%%%%%%%%%%....%%%%%%",
     "C": "##.....######################.....####"},
    {"A": "##.....######################.....####",
     "B": "#####..................##......#######",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%%%%........%%................%%%%%%%",
     "C": "######....################....########"},
    {"A": "######....################....########",
     "B": "####...................##.......######",
     "C": "##############..####..################"},
    {"A": "##############..####..################",
     "B": "%%....................................",
     "C": "######~~~~~~~~~~~~~~~~~~~~~~~~########"},
    {"A": "######################################",
     "B": "....................................##",
     "C": "######################################"},
]

# CHARACTERS.md, "Level 7 (11 of 12 rooms scanned, 19 entities)", as
# (room, what, x, y). Room 0 has NO row: no entity was measured there, and
# none is invented here.
#
# The table stops at room 10 because the census was taken when the walker
# still stopped there. Room 11 was reached for the first time in this session
# and has never been censused, so its two entities are checked against the
# capture instead - see test_room_11_is_the_one_room_no_census_ever_saw.
#
# The BAT of room 5 is the one place this table and HL.SPIDERS do not print
# the same number, and they are not measuring the same thing: CHARACTERS.md
# gives the tight box of the ink the scan saw most of the time, HL.SPIDERS
# gives the CENTRE of the patrol, derived from the envelope the sprite is ever
# drawn in.
CHARACTERS_MD = [
    (1, "lantern", 83, 35),
    (1, "spider", 52, 70),
    (2, "lantern", 27, 35),
    (3, "lantern", 79, 35),
    (3, "snake", 48, 72),
    (4, "lantern", 103, 35),
    (5, "lantern", 131, 35),
    (5, "spider", 60, 70),
    (5, "bat", 114, 104),
    (6, "lantern", 43, 35),
    (6, "bat", 24, 111),
    (7, "lantern", 31, 35),
    (7, "snake", 28, 72),
    (7, "spider", 80, 109),
    (8, "lantern", 83, 35),
    (9, "lantern", 123, 35),
    (9, "spider", 76, 70),
    (10, "lantern", 67, 35),
    (10, "spider", 72, 109),
]

# The one row of CHARACTERS_MD whose KIND the capture contradicts, kept here
# rather than quietly changed. The census calls the still creature at
# (24, 111) a BAT; the ROM draws it as the UNTETHERED SPIDER, the same seven
# pixels of the same sprite it draws at (76, 65) two rooms further down and in
# three rooms of level 6 - where the census calls the same thing a Spider.
# See test_room_6s_creature_is_the_untethered_spider for the evidence.
KIND_OVERRIDDEN = {(6, 24, 111): ("bat", "spider_free")}


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


# --- geometry ---------------------------------------------------------------
def test_level_7_is_twelve_blue_rooms():
    common.check_shape(L, "blue", rooms=12)
    assert len(HL.BG_RLE_L7) == 12


def test_all_twelve_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_the_level_is_complete_and_nothing_is_missing():
    """CORRECTIONS.md listed level 7 as 11 of 12 rooms, and the twelfth was
    reached on 2026-09-22 by flying the hero out of room 10's right edge.
    Nothing here is a placeholder."""
    assert len(BANDS) == HL.ROOMS_PER_LEVEL[L - 1] == 12
    assert len(HL.WALL_RECTS_L7) == 12


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_across_all_twelve_rooms():
    """Room N's ceiling is drawn identically to room N-1's floor. This is the
    invariant the corrected capture is checked against, and it is what the
    first pass broke.

    Room 11 is the one room where the two strings are not the same characters:
    room 10's floor carries `~`, and a liquid cell drawn as a CEILING is just
    solid rock - the `~` shape only exists in the floor band, where it means
    "black until row 136". So the comparison is of solid against air.
    """
    for room in range(1, len(BANDS)):
        above = BANDS[room - 1]["C"].replace("~", "#")
        assert BANDS[room]["A"] == above


def test_the_corridors_are_not_all_room_0s():
    """The superseded capture kept room 0's corridor for every room, which is
    exactly what was wrong with the level-7 block this one replaces."""
    corridors = [b["B"] for b in BANDS]
    assert corridors.count(corridors[0]) == 1
    assert len(set(corridors)) == 12, "every room draws its own corridor"


def test_no_cell_was_left_uncalled():
    assert "?" not in "".join(b[k] for b in BANDS for k in "ABC")


# --- the liquid floor -------------------------------------------------------
def test_room_10s_floor_is_liquid_from_end_to_end_and_is_not_a_hole():
    """`~` LOOKS like a hole and is not one: it is empty from row 99 down to
    about 135 and filled on rows 136-141, it is lethal, and it is not a way
    down. Room 10 is the only room of the level that has any, and it has
    twenty-four cells of it."""
    liquid = {r for r, b in enumerate(BANDS) if "~" in b["C"]}
    assert liquid == {10}
    assert runs_of(BANDS[10]["C"], "~") == [(6, 29)]
    assert cells(6, 29) == (32, 96)
    assert "." not in BANDS[10]["C"], "no cell of it is a real hole"


def test_the_deadly_rects_are_the_water_line_and_the_flooded_trim():
    """Room 10's is the liquid surface itself, all six rows a `~` cell is
    drawn on. Room 11's is the flooded trim on the last rows of the miner's
    room, the same shape level 5 room 7 and level 6 room 9 have.

    Room 10's rect starts at 136 and not at 137, where the off-ramp colour
    test alone put it: 136 is the trim row along the top of the same water,
    and it is exactly the row the hero comes to rest on. A hazard one row
    below where he stands is a hazard he stands on top of for ever.
    """
    assert HL.DEADLY[L - 1] == [(10, 8, 136, 152, 6), (11, 8, 139, 152, 3)]
    for room, x, y, w, h in HL.DEADLY[L - 1]:
        assert y + h - 1 == 141, "the surface sits on the last rows"
        assert y >= 136, "and never reaches up into the body of the floor band"
        assert (x, w) == (8, 152), "right across the playfield"


def test_a_liquid_cell_is_solid_only_on_the_rows_it_is_drawn_on():
    """`~` is filled on rows 136-141 and black from 99 to 135. A rect over the
    whole floor band would be an invisible ledge: before this, the hero fell
    into room 10 and stopped with his feet on row 99, thirty-seven pixels
    above the water and in the middle of the air the room's spider hangs
    in."""
    floor = [r for r in HL.WALL_RECTS_L7[10] if r[1] >= 99]
    assert sorted(floor) == [(8, 99, 24, 43), (32, 136, 96, 6),
                             (128, 99, 32, 43)]
    assert HL.WALL_RECTS_L7[11][-1] == (8, 99, 152, 43), \
        "a room with no liquid still gets a full-band floor"


def test_the_water_of_room_10_is_lethal_and_still_not_a_way_down(env):
    """Both halves of the rule at once: he cannot fall through it, and he
    cannot stand on it either."""
    import jax.numpy as jnp
    c = env.consts
    _, state = env.reset()
    state = state.replace(level=jnp.int32(L - 1), room=jnp.int32(10),
                          player_x=jnp.int32(70), player_y=jnp.int32(62),
                          spider_alive=jnp.zeros_like(state.spider_alive))
    lives = int(state.lives)
    for _ in range(120):
        _obs, state, _r, _d, _i = env.step(state, jnp.int32(NOOP))
        if int(state.lives) != lives:
            break
    assert int(state.lives) == lives - 1, "the liquid surface kills him"
    assert int(state.room) == 10, "and it is not a way down"


def test_the_spider_of_room_10_is_a_creature_and_not_part_of_the_water():
    """It hangs at (72, 109) - inside the floor band, above the water line and
    over a `~` cell. While a liquid cell counted as solid the sprite pass
    never looked there, so it was erased into the room's DEADLY rect, which
    then reached from row 109 instead of row 137."""
    assert (10, 72, 109, 0, 0) in HL.SPIDERS[L - 1]
    assert BANDS[10]["C"][(72 - 8) // 4] == "~"
    room10 = [d for d in HL.DEADLY[L - 1] if d[0] == 10][0]
    assert room10[2] > 109 + 11, "the hazard starts below the spider, not at it"


# --- magma ------------------------------------------------------------------
def test_the_magma_is_in_the_six_even_rooms():
    """Magma is a property of the ROOM: the corridor colour register is either
    the level hue or magma red, so in a magma room every solid corridor cell
    is magma and in any other room none is."""
    magma_rooms = sorted({r for r, *_rest in HL.MAGMA[L - 1]})
    assert magma_rooms == [0, 2, 4, 6, 8, 10]
    for room in magma_rooms:
        assert "#" not in BANDS[room]["B"], \
            "in a magma room every solid corridor cell is magma"
    for room in range(12):
        if room not in magma_rooms:
            assert "%" not in BANDS[room]["B"]


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


def test_magma_never_leaves_the_corridor_band():
    for _room, _x, y, _w, h in HL.MAGMA[L - 1]:
        assert (y, h) == (60, 39)


# --- blastable walls --------------------------------------------------------
def test_the_eight_blastable_pillars_are_the_eight_two_cell_ones():
    """A stick takes a two-cell corridor pillar and nothing wider, and never
    one that reaches the side of the screen. Rooms 4, 6, 10 and 11 have none:
    4 and 6 carry slabs twelve and sixteen cells wide, and 10 and 11 have
    nothing in mid-corridor at all."""
    assert HL.DESTRUCTIBLE[L - 1] == [
        (0, 60, 16, 8, 83, 1),
        (1, 92, 60, 8, 39, 1),
        (2, 60, 60, 8, 39, 1),
        (3, 64, 60, 8, 39, 1),
        (5, 100, 60, 8, 39, 1),
        (7, 100, 60, 8, 39, 1),
        (8, 60, 60, 8, 39, 1),
        (9, 100, 60, 8, 39, 1),
    ]
    expect = []
    for room, band in enumerate(BANDS):
        for first, last in runs_of(band["B"], "#") + runs_of(band["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            expect.append((room, cells(first, last)[0]))
    assert [(z[0], z[1]) for z in HL.DESTRUCTIBLE[L - 1]] == sorted(expect)


def test_the_wide_slabs_of_rooms_4_and_6_are_not_blastable():
    """Dynamite breaks a two-cell pillar and wider runs are immune."""
    assert runs_of(BANDS[4]["B"], "%") == [(0, 5), (14, 25), (34, 37)]
    assert runs_of(BANDS[6]["B"], "%") == [(0, 7), (12, 27), (32, 37)]
    for room in (4, 6, 10, 11):
        assert [z for z in HL.DESTRUCTIBLE[L - 1] if z[0] == room] == []


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    """Room 0's ceiling IS that pillar, so both bands go. The rest carry
    theirs under a solid ceiling slab and only the corridor cells go."""
    for room, x, y, w, h, _ok in HL.DESTRUCTIBLE[L - 1]:
        cell = (x - 8) // 4
        ceiling_is_the_pillar = (cell, cell + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if ceiling_is_the_pillar else (60, 39))
    assert BANDS[0]["A"][13:15] == "##" and BANDS[0]["B"][13:15] == "%%"


def test_the_magma_pillars_are_blastable():
    """Magma is rock that glows: a stick takes a two-cell magma pillar for the
    same 75 points. Three of the eight are magma."""
    magma_zones = [z for z in HL.DESTRUCTIBLE[L - 1] if z[0] in (0, 2, 8)]
    assert len(magma_zones) == 3
    for room, x, *_rest in magma_zones:
        cell = (x - 8) // 4
        assert BANDS[room]["B"][cell:cell + 2] == "%%"
        assert any(m[0] == room and m[1] == x for m in HL.MAGMA[L - 1])


def test_the_shared_wall_table_is_empty():
    """Two rooms that draw the identical band are NOT one physical wall
    (measured on level 4 rooms 5 and 6: blast one pillar and the twin
    stands)."""
    common.check_shared_walls(L)
    assert HL.SHARED_WALLS[L - 1] == []


def test_nothing_flares(env):
    """FLARES used to carry three authored rows for this level - a periodic
    eruption at a gap mouth of room 6 and two along the water line of room 10
    - which no capture supports; they were invented on top of the superseded
    reference. The ROM's real entry transient is a different thing: magma is
    drawn EXTENDED for about 34 frames on entering a room and then recedes two
    cells each side permanently, which is a property of the magma rects."""
    assert HL.FLARES[L - 1] == []


# --- routes -----------------------------------------------------------------
def test_the_side_exits_are_the_open_corridor_edges():
    assert HL.SIDE_EXITS[L - 1] == [(10, 1, 1), (11, -1, -1)]
    for room, side, _delta in HL.SIDE_EXITS[L - 1]:
        cell = 0 if side < 0 else 37
        assert BANDS[room]["B"][cell] == ".", \
            "a side exit is an open corridor cell at the edge of the screen"
    for room, band in enumerate(BANDS):
        for cell, side in ((0, -1), (37, 1)):
            if band["B"][cell] == ".":
                assert room in {r for r, sd, _d in HL.SIDE_EXITS[L - 1]
                                if sd == side}


def test_room_10_descends_through_its_RIGHT_edge_not_its_left():
    """This is the one that breaks "left is down, right is up". Level 5 room 1
    goes down the chain through its LEFT edge; level 7 room 10 goes down
    through its RIGHT one, and the ROM walk was watched doing it with nothing
    writing RAM 28. Room 11's own open left edge leads back UP."""
    assert (10, 1, 1) in HL.SIDE_EXITS[L - 1], "right edge, down the chain"
    assert (11, -1, -1) in HL.SIDE_EXITS[L - 1], "left edge, back up"
    assert HL.SIDE_EXITS[4] == [(1, -1, 1), (2, 1, -1)], \
        "and level 5 still goes the other way round"


def test_every_room_but_the_last_has_a_way_on():
    """A hole in the floor, or an open side edge. Room 10 has only the second
    kind - its floor is liquid from end to end."""
    sides = {room for room, _side, delta in HL.SIDE_EXITS[L - 1] if delta > 0}
    for room in range(11):
        has_hole = "." in BANDS[room]["C"]
        assert has_hole or room in sides, f"room {room} has no way on"
    assert "." not in BANDS[10]["C"] and 10 in sides, \
        "room 10 is the water room and leaves sideways"
    assert "." not in BANDS[11]["C"], "the miner's room has no hole"


def test_room_0_must_be_blasted_to_reach_its_hole():
    """Its pillar at x 60-67 is the same pillar in the ceiling, so it cannot
    be flown over, and the hole at x 72-87 is on its far side."""
    assert HL.DESTRUCTIBLE[L - 1][0] == (0, 60, 16, 8, 83, 1)
    assert runs_of(BANDS[0]["C"], ".") == [(16, 19)]
    assert cells(16, 19) == (72, 16)


def test_flying_off_room_10s_right_edge_enters_room_11(env):
    """The engine has to do what the ROM does. He leaves by the right edge and
    arrives in room 11 near its left, keeping his height."""
    import jax.numpy as jnp
    c = env.consts
    _, state = env.reset()
    state = state.replace(level=jnp.int32(L - 1), room=jnp.int32(10),
                          player_x=jnp.int32(c.screen_width - 8
                                             - c.player_width),
                          player_y=jnp.int32(70),
                          spider_alive=jnp.zeros_like(state.spider_alive))
    y_before = int(state.player_y)
    for _ in range(12):
        _obs, state, _r, _d, _i = env.step(state, jnp.int32(RIGHT))
        if int(state.room) != 10:
            break
    assert int(state.room) == 11, "the right edge leads DOWN to room 11"
    assert int(state.player_x) == c.side_enter_right_x
    assert abs(int(state.player_y) - y_before) <= 2, "he keeps his height"


# --- objects ----------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_miner(L, BANDS)
    common.check_destructibles(L, BANDS)
    common.check_creatures_are_sane(L)


def test_every_entity_in_characters_md_is_present():
    """The level's whole cast, room by room, against CHARACTERS.md.

    Lanterns, spiders, snakes and the miner are compared exactly. A BAT is
    compared against its patrol envelope instead of the centre HL.SPIDERS
    prints - see the note on CHARACTERS_MD above - and the tolerance is the
    2 px the tight box trims off the spread wing, never more.
    """
    got = [(r, "lantern", x, y) for r, x, y in HL.LANTERNS[L - 1]]
    got.append((HL.MINER_POS[L - 1][0], "miner",
                HL.MINER_POS[L - 1][1], HL.MINER_POS[L - 1][2]))
    kinds = {0: "spider", 1: "bat", 3: "snake", 4: "spider_free"}
    for room, x, y, patrol, kind in HL.SPIDERS[L - 1]:
        got.append((room, kinds[kind], x - patrol, y))

    for room, what, x, y in CHARACTERS_MD:
        want = KIND_OVERRIDDEN.get((room, x, y), (what, what))[1]
        near = [g for g in got
                if g[0] == room and g[1] == want
                and abs(g[2] - x) <= 2 and abs(g[3] - y) <= 1]
        assert near, f"CHARACTERS.md row ({room}, {what}, {x}, {y}) is missing"
        if what != "bat":
            assert (room, want, x, y) in got, \
                f"({room}, {what}) must match CHARACTERS.md exactly"


def test_room_11_is_the_one_room_no_census_ever_saw():
    """CHARACTERS.md stops at room 10 because the walker did. Everything this
    level ships beyond its nineteen rows is room 11's, and room 11 was
    captured off the ROM in this session: a bobbing creature at (76, 65) and
    the miner at (128, 86)."""
    assert max(row[0] for row in CHARACTERS_MD) == 10
    # compared on the left edge of the patrol, which is what CHARACTERS.md
    # prints; HL.SPIDERS carries the centre (the bat of room 5 is the only
    # creature on the level where the two differ)
    extra = [(r, x - p, y) for r, x, y, p, _k in HL.SPIDERS[L - 1]
             if not any(row[0] == r and abs(row[2] - (x - p)) <= 2
                        and abs(row[3] - y) <= 1 for row in CHARACTERS_MD)]
    assert extra == [(11, 76, 65)]
    assert HL.MINER_POS[L - 1][0] == 11
    assert [g for g in HL.LANTERNS[L - 1] if g[0] == 11] == [], \
        "room 11 has no lantern"


def test_room_0_has_no_creature_and_none_was_invented():
    """CHARACTERS.md has no row for room 0, so nothing is placed there."""
    assert [c for c in HL.SPIDERS[L - 1] if c[0] == 0] == []
    assert [g for g in HL.LANTERNS[L - 1] if g[0] == 0] == []


def test_the_lanterns_hang_in_the_ceiling_band_on_row_35():
    """"Always in the ceiling band, top left of its 5x8 box on row 35"
    (CHARACTERS.md). Ten of the twelve rooms have one; rooms 0 and 11 do
    not."""
    assert len(HL.LANTERNS[L - 1]) == 10
    assert {r for r, _x, _y in HL.LANTERNS[L - 1]} == set(range(1, 11))
    for _room, _x, y in HL.LANTERNS[L - 1]:
        assert y == 35


def test_the_miner_is_at_the_bottom_right_of_room_11():
    """One per level, in the last room, sprite top left on row 86, at x 25 on
    the left of the screen or x 128 on the right (CHARACTERS.md). Level 7's
    stands on the right, which is also where the recorded playthrough finds
    him."""
    assert HL.MINER_POS[L - 1] == (11, 128, 86)
    assert BANDS[11]["B"][(128 - 8) // 4] == ".", "he stands in open corridor"


def test_room_6s_creature_is_the_untethered_spider():
    """The one row where this level does not follow CHARACTERS.md's label.

    The census calls the still creature at (24, 111) a BAT. It tells a bat
    from a spider by whether a 1 px thread is drawn above the body, and this
    one has none - so it falls through to "bat" by elimination. Read off the
    ROM it is neither of the two things the census can name:

      * A BAT is eleven rows in every pose, and the ROM paints it in six
        shades laid out by row and mirrored about the body - #8e8e8e #aaaaaa
        #c0c0c0 wings around a #c3903d #b47a30 #a26221 body. Level 7's real
        bat, the patrolling one in room 5, comes back exactly like that.
      * A HANGING SPIDER is a five row body under six rows of #aaaaaa thread.
      * THIS is seven rows of warm body with no grey in it at all, and the
        ROM draws the identical seven pixels at (76, 65) in room 11 and in
        three rooms of level 6 - where the census calls the same sprite a
        Spider. It is its own form, kind 4.

    Measured with level_images/tools/creature_atlas.py over levels 1-7, which
    records every bitmap of every sprite with the colour of every pixel, and
    confirmed by watching this one for 900 consecutive frames: one bitmap, no
    movement.
    """
    assert (6, 24, 111, 0, 4) in HL.SPIDERS[L - 1], "kind 4 = untethered"
    assert KIND_OVERRIDDEN[(6, 24, 111)] == ("bat", "spider_free")
    bats = [c for c in HL.SPIDERS[L - 1] if c[4] == 1]
    assert bats == [(5, 123, 103, 11, 1)], "level 7 ships exactly one bat"
    free = [c for c in HL.SPIDERS[L - 1] if c[4] == 4]
    assert free == [(6, 24, 111, 0, 4), (11, 76, 65, 0, 4)], \
        "and two untethered spiders, the still one and room 11's"


def test_the_bat_is_painted_in_the_roms_six_shades_not_one_flat_grey(env):
    """CHARACTERS.md: "an orange body with grey wings above and below it".

    The art used to be one flat #6f6f6f for the whole bat, which is a colour
    the ROM never paints a creature in. Read off level 7 room 5, every pose is
    laid out by row and mirrored about the middle: #8e8e8e #aaaaaa #c0c0c0
    for the wings, then #c3903d #b47a30 #a26221 for the body, then back out.
    """
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import HeroRenderer
    renderer = HeroRenderer(env.consts)
    c = env.consts
    _, s = env.reset()
    s = s.replace(level=jnp.int32(L - 1), room=jnp.int32(5),
                  player_x=jnp.int32(-40), player_y=jnp.int32(-40),
                  step_counter=jnp.int32(46),      # the centre of the sweep
                  spider_alive=c.SPIDER_VALID[L - 1])
    frame = np.asarray(renderer.render(s))[:142, :, :3]
    band = frame[103:114, 112:135].reshape(-1, 3)
    inked = {tuple(int(v) for v in px) for px in band if tuple(px) != (0, 0, 0)}
    wings = {(142, 142, 142), (170, 170, 170), (192, 192, 192)}
    body = {(195, 144, 61), (180, 122, 48), (162, 98, 33)}
    assert wings <= inked, "all three wing greys are drawn"
    assert body <= inked, "and all three body shades"
    assert (111, 111, 111) not in inked, "and not the flat grey it used to be"


# --- the clocks that are not shared -----------------------------------------
def test_the_one_bat_patrols_22_px_on_184_frames_and_holds_a_pose_4():
    """"A bat patrols 22 px with a 184-frame horizontal period and a 64-frame
    vertical one, and holds each wing pose for 4 frames" (CHARACTERS.md). The
    two clocks are different lengths, so the path is a slow Lissajous figure
    and not a straight line."""
    bats = [slot for slot, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 1]
    assert bats == [3]
    for slot in bats:
        travel, half, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half) == (7, 64), "the bat bobs 7 px on 64 frames"
        assert hold == 4, "and holds each wing pose for 4 frames"
        assert 2 * HL.CREATURE_PATROL[(L, slot)] == 184
        assert 2 * HL.SPIDERS[L - 1][slot][3] == 22, "22 px of patrol"
        assert HL.CREATURE_PATROL[(L, slot)] != half, \
            "the bob and the patrol must not share a clock"


def test_the_two_snakes_are_anchored_and_run_the_engines_own_clock():
    """A snake grows a pixel out of the rock every 4 frames and never
    travels, so it carries no patrol and no bob."""
    snakes = [slot for slot, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 3]
    assert [HL.SPIDERS[L - 1][s][:3] for s in snakes] == [(3, 48, 72),
                                                          (7, 28, 72)]
    for slot in snakes:
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 4)
        assert (L, slot) not in HL.CREATURE_PATROL
        room, x, _y, _p, _k = HL.SPIDERS[L - 1][slot]
        assert BANDS[room]["B"][(x - 8) // 4 - 1] != ".", \
            "a snake's head comes out of the rock on its LEFT"


def test_a_creature_that_does_not_travel_may_still_animate():
    """Six of the ten never move a pixel. Only TWO of those six are drawn as
    a single bitmap.

    This is the distinction the census cannot make. "Still" used to be taken
    from its `distinct_sprites`, which reports 1 for creatures that plainly
    alternate two bitmaps every seven or eight frames, so four spiders that
    swap their legs on the spot were pinned to one pose. Counted over the
    capture's own 480 frames, room 6's untethered spider and room 10's hanging
    one draw ONE bitmap for the whole window; rooms 1, 5, 7 and 9 draw two.
    """
    still = [slot for slot, c in enumerate(HL.SPIDERS[L - 1])
             if c[4] != 3 and HL.CREATURE_MOTION[(L, slot)][0] == 0]
    assert still == [0, 2, 4, 6, 7, 8]
    for slot in still:
        travel, half, _hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, half) == (0, 0), "a still creature does not travel"
        assert (L, slot) not in HL.CREATURE_PATROL, "and does not sweep"
    frozen = [s for s in still if HL.CREATURE_SPRITES.get((L, s)) == 1]
    assert frozen == [4, 8], "rooms 6 and 10 draw one bitmap all window"
    assert [HL.SPIDERS[L - 1][s][0] for s in frozen] == [6, 10]
    for slot in set(still) - set(frozen):
        assert (L, slot) not in HL.CREATURE_SPRITES, \
            "the other four keep both of their poses"


def test_the_moving_creatures_keep_their_kinds_full_cycle():
    """A creature that does move must NOT be pinned to one sprite: the bat
    keeps all four wings and room 11's bobbing creature both poses."""
    for slot, c in enumerate(HL.SPIDERS[L - 1]):
        if HL.CREATURE_MOTION[(L, slot)][0] > 0:
            assert (L, slot) not in HL.CREATURE_SPRITES
    assert [slot for slot, c in enumerate(HL.SPIDERS[L - 1])
            if HL.CREATURE_MOTION[(L, slot)][0] > 0] == [3, 9]


def test_room_11s_bobbing_creature_carries_the_captures_own_numbers():
    """It moves 7 px on a 64-frame cycle and holds each of its two poses for
    8 frames - the same numbers every untethered spider in the game carries,
    in levels 2, 3, 4 and 6 as well.

    Room 11 has never been censused, so nothing outside the ROM confirms it.
    It does not need to: the identical sprite in level 6 room 1 was watched
    for 400 consecutive frames and its whole (pose, position) sequence repeats
    exactly every 64.
    """
    travel, half, hold = HL.CREATURE_MOTION[(L, 9)]
    assert (travel, 2 * half, hold) == (7, 64, 8)
    assert (L, 9) not in HL.CREATURE_SPRITES
    assert HL.SPIDERS[L - 1][9] == (11, 76, 65, 0, 4)
    for lvl, slot in ((2, 1), (2, 3), (3, 4), (4, 1), (4, 6),
                      (6, 1), (6, 6), (6, 8)):
        assert HL.CREATURE_MOTION[(lvl, slot)] == (7, 32, 8),             f"level {lvl} slot {slot} is the same creature on the same clock"


def test_the_renderer_holds_a_still_creature_on_one_sprite(env):
    """The table is only half of it - the engine has to read it. Slot 4 is
    the frozen untethered spider of room 6; its drawn pose must be the same on
    every frame, while the bat in slot 3 must cycle."""
    c = env.consts
    lvl = L - 1
    assert int(c.SPIDER_POSES[lvl, 4]) == 1, "the frozen one is pinned"
    assert int(c.SPIDER_POSES[lvl, 3]) == 0, "the bat keeps its kind's cycle"
    assert int(c.SPIDER_POSES[lvl, 0]) == 0,         "and a still creature that DOES swap its legs keeps both poses"
    hold = int(c.SPIDER_HOLD[lvl, 4])
    frames = {(step // hold) % max(1, int(c.SPIDER_POSES[lvl, 4]))
              for step in range(600)}
    assert frames == {0}, "a frozen creature never changes sprite"


def test_a_still_creature_never_moves_and_a_bobbing_one_does(env):
    """Position, not just artwork: over a full 184-frame sweep the still
    spider of room 1 must not shift by a pixel, and the bat must."""
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    lvl = L - 1
    seen_still, seen_bat, seen_bob = set(), set(), set()
    for step in range(400):
        x, y = _creature_pos(c, lvl, step)
        seen_still.add((int(x[0]), int(y[0])))
        seen_bat.add((int(x[3]), int(y[3])))
        seen_bob.add((int(x[9]), int(y[9])))
    assert seen_still == {(52, 70)}, "the still spider of room 1 never moves"
    assert len({p[0] for p in seen_bat}) > 1, "the bat patrols sideways"
    assert len({p[1] for p in seen_bat}) > 1, "and bobs"
    assert {p[0] for p in seen_bob} == {76}, "a bobbing one does not translate"
    assert len({p[1] for p in seen_bob}) > 1, "but it does bob"


# --- the screen -------------------------------------------------------------
def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black. The HUD panel above them does not."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import HeroRenderer
    renderer = HeroRenderer(env.consts)
    _, s = env.reset()
    s = s.replace(level=jnp.int32(L - 1), room=jnp.int32(0))
    frame = np.asarray(renderer.render(s))[:, :, :3]
    assert frame.shape[0] >= 210
    assert frame[189:210].max() == 0, "rows 189-209 must stay black"
    assert frame[142:189].max() > 0, "the grey HUD panel is still drawn"


def test_room_0_is_blue_and_not_the_boot_palette_brown(env):
    """The ROM latches the cave palette on the first room transition, so a
    level booted by holding the level register down draws room 0 in level 1's
    BROWN. The capture maps the brown ramp back onto the level's own, and the
    old level-7 block is where that was visible: its palette carried the whole
    brown ramp beside the blue one."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import HeroRenderer
    renderer = HeroRenderer(env.consts)
    _, s = env.reset()
    s = s.replace(level=jnp.int32(L - 1), room=jnp.int32(0))
    frame = np.asarray(renderer.render(s))[:142, :, :3]
    for role in ("dark", "mid", "light"):
        want = common.rgb(HL.SHADES[L][role])
        assert (frame == np.array(want)).all(axis=-1).any(), \
            f"room 0 does not paint its own {role} shade {HL.SHADES[L][role]}"
    brown = common.rgb(HL.SHADES[1]["mid"])
    assert not (frame == np.array(brown)).all(axis=-1).any(), \
        "and it paints none of level 1's brown"
