"""Level 5, against the corrected ROM reference.

The block in hero_levels.py is generated by tools/hero_gen/build_level.py,
which walks the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), then play the level.

Level 5 is the level that made the walker honest. Before this, the ROM walk
reached two of its eight rooms and stopped, and `CORRECTIONS.md` recorded
level 5 among the ones that "stop very early" and put it down to a sealed
floor. The floor of room 1 is sealed - but the room is not a dead end, and
three separate things had to be measured before the ROM would give up the
rest of the level:

  * A ROOM IS ALSO LEFT SIDEWAYS. Room 1's corridor reaches the LEFT edge of
    the screen as open air, and walking into that edge runs the same
    transition code a fall does. Measured: off x 13 of room 1 the hero
    arrives in room 2 at x 148, and back off x 146 of room 2 he arrives in
    room 1 at x 16 - so a left edge leads down the chain and a right edge
    back up it, mirroring the floor and the ceiling. Rooms 2-7 had been read
    off the recorded video until this was found.
  * A TWO-CELL HOLE IS 8 PX WIDE and so is the hero. Aiming the descent at a
    cell edge misses it more often than not: room 3 refused both of its
    cells for 700 frames each and went through at x 78, between them.
  * READING A ROOM CAN MOVE THE HERO OUT OF IT. The reader parks him at RAM
    x = 0 so his sprite sits in the column strip the Atari never draws; in a
    room with a side exit the ROM reads x < 16 as "he has left" and
    transitions, so room 2 was being read as room 3.

What the ROM then said that the video had got wrong, in seven bands: four
`?` cells the video could not call (rooms 3, 4, 5 and 6, all of them `.`),
and three corridors the video read as plain rock and the ROM draws as MAGMA
(rooms 3, 5 and 6). hero_rooms.py was corrected from the walk.

The route, room by room:

    room 0  spawn in the left corridor, blocked by the pillar at x 60-67
            whose ceiling is the same pillar -> plant a stick, run, +75,
            then down the hole at x 72-87
    room 1  no hole anywhere in the floor and magma in the last two cells:
            walk LEFT off the open edge into room 2
    room 2  arrive at the right; a still spider hangs at x 76 and a bat
            patrols the floor band; the floor is open from x 24 to x 135
    room 3  magma down both sides of the corridor, safe from x 48 to x 111,
            hole at x 76-83
    room 4  a bat on the left, a snake on the floor at x 128, holes at
            x 24-31 and x 128-135
    room 5  magma at both edges and a magma pillar at x 48, hole at x 72-87
    room 6  the same again with the pillar at x 56, a still spider at
            x 112, holes at x 40-47 and x 112-119
    room 7  the miner's room: no hole, a flooded floor, a bat overhead and
            the miner at x 128
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

NOOP, FIRE, UP, RIGHT, LEFT, DOWN = 0, 1, 2, 3, 4, 5
L = 5

# What the ROM draws, cell for cell, in descent order. Generated by
# tools/hero_gen/build_level.py and verified by it against
# level_images/hero_rooms.py before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "##...........##...................####",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "....................................%%",
     "C": "######################################"},
    {"A": "######################################",
     "B": "##....................................",
     "C": "####............................######"},
    {"A": "####............................######",
     "B": "%%%%%%%%%%................%%%%%%%%%%%%",
     "C": "#################..###################"},
    {"A": "#################..###################",
     "B": "##.........##.....................####",
     "C": "####..########################..######"},
    {"A": "####..########################..######",
     "B": "%%........%%......................%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%..........%%....................%%%%",
     "C": "########..################..##########"},
    {"A": "########..################..##########",
     "B": "##................................####",
     "C": "######################################"},
]


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


# --- geometry ---------------------------------------------------------------
def test_level_5_is_eight_brown_rooms():
    common.check_shape(L, "brown", rooms=8)
    assert len(HL.BG_RLE_L5) == 8


def test_all_eight_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_across_all_eight_rooms():
    """Room N's ceiling is drawn identically to room N-1's floor. This is the
    invariant the corrected capture is checked against, and it is what the
    first pass broke."""
    for room in range(1, len(BANDS)):
        assert BANDS[room]["A"] == BANDS[room - 1]["C"]


def test_the_corridors_are_not_all_room_0s():
    """The superseded capture kept room 0's corridor for every room. No two
    rooms of level 5 draw the same corridor, and only room 0 draws room 0's."""
    corridors = [b["B"] for b in BANDS]
    assert corridors.count(corridors[0]) == 1
    assert len(set(corridors)) == 8


def test_rooms_2_to_7_come_from_the_rom_and_not_from_the_video():
    """Every band here is one the ROM walk produced. The four cells the video
    could not call are all open air, and they are exactly the cells the chain
    invariant fixes."""
    assert "?" not in "".join(b[k] for b in BANDS for k in "ABC")
    # the four former '?' cells, in rooms 3, 4, 5 and 6
    assert BANDS[3]["A"][31] == "."
    assert BANDS[4]["A"][18] == "."
    assert BANDS[5]["A"][31] == "."
    assert BANDS[6]["A"][19] == "."


def test_the_magma_is_in_four_rooms_not_one():
    """The video read rooms 3, 5 and 6 as plain rock. The ROM's corridor
    colour register says magma, and magma is a property of the ROOM: every
    solid corridor cell of a magma room is magma."""
    magma_rooms = sorted({r for r, *_rest in HL.MAGMA[L - 1]})
    assert magma_rooms == [1, 3, 5, 6]
    for room in magma_rooms:
        assert "#" not in BANDS[room]["B"], \
            "in a magma room every solid corridor cell is magma"
    for room in range(8):
        if room not in magma_rooms:
            assert "%" not in BANDS[room]["B"]


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


# --- the side exit ----------------------------------------------------------
def test_room_1_is_sealed_and_has_no_blastable_floor():
    """It used to be listed as a blastable floor, on no measurement at all."""
    assert "." not in BANDS[1]["C"] and "~" not in BANDS[1]["C"]
    assert [z for z in HL.DESTRUCTIBLE[L - 1] if z[0] == 1] == []


def test_the_side_exits_are_the_open_corridor_edges():
    # (room, side, delta): room 1's LEFT edge goes DOWN the chain (+1) and
    # room 2's RIGHT edge comes back UP it (-1). Which edge descends is a
    # property of the room - level 7 descends through a RIGHT edge - so the
    # direction is carried as data rather than derived from the side.
    assert HL.SIDE_EXITS[L - 1] == [(1, -1, 1), (2, 1, -1)]
    for room, side, _delta in HL.SIDE_EXITS[L - 1]:
        cell = 0 if side < 0 else 37
        assert BANDS[room]["B"][cell] == ".", \
            "a side exit is an open corridor cell at the edge of the screen"
    # and no other room has one
    for room, band in enumerate(BANDS):
        for cell, side in ((0, -1), (37, 1)):
            if band["B"][cell] == ".":
                assert room in {r for r, sd, _d in HL.SIDE_EXITS[L - 1]
                                if sd == side}


def test_walking_off_room_1s_left_edge_enters_room_2(env):
    """Measured on the ROM: off x 13 of room 1 he arrives in room 2 at x 148,
    keeping his height. This is the only way on from room 1."""
    c = env.consts
    _, s = env.reset()
    s = s.replace(level=np.int32(L - 1), room=np.int32(1),
                  spider_alive=np.zeros_like(s.spider_alive),
                  player_x=np.int32(60), player_y=np.int32(75))
    y_before = int(s.player_y)
    for _ in range(80):
        _, s, _, _, _ = env.step(s, LEFT)
        if int(s.room) != 1:
            break
    assert int(s.room) == 2, "the left edge of room 1 leads to room 2"
    assert int(s.player_x) == c.side_enter_left_x, "he comes in from the right"
    assert int(s.player_y) == y_before, "a side exit does not change his height"


def test_walking_off_room_2s_right_edge_goes_back_to_room_1(env):
    """The mirror of it, also measured: off x 146 of room 2 he arrives in
    room 1 at x 16.

    He has to start on the right-hand LEDGE (x 136-159): room 2's floor is
    open from x 24 to x 135 and anywhere left of the ledge he falls into
    room 3 before he ever reaches the edge.
    """
    c = env.consts
    _, s = env.reset()
    s = s.replace(level=np.int32(L - 1), room=np.int32(2),
                  spider_alive=np.zeros_like(s.spider_alive),
                  player_x=np.int32(138), player_y=np.int32(75))
    for _ in range(80):
        _, s, _, _, _ = env.step(s, RIGHT)
        if int(s.room) != 2:
            break
    assert int(s.room) == 1, "the right edge of room 2 leads back to room 1"
    assert int(s.player_x) == c.side_enter_right_x, "he comes in from the left"


def test_a_room_without_an_open_edge_keeps_him_in(env):
    """Room 7's corridor is walled at both edges, so he stops at the wall and
    the room does not change however long he pushes."""
    _, s = env.reset()
    s = s.replace(level=np.int32(L - 1), room=np.int32(7),
                  spider_alive=np.zeros_like(s.spider_alive),
                  player_x=np.int32(60), player_y=np.int32(75))
    for _ in range(120):
        _, s, _, _, _ = env.step(s, LEFT)
    assert int(s.room) == 7
    assert int(s.player_x) >= 16, "the two rock cells at the left edge hold him"


# --- routes -----------------------------------------------------------------
def test_every_room_but_the_last_has_a_way_on():
    """A hole in the floor, or an open side edge. Room 1 has only the second
    kind, which is why the level used to be unfinishable here."""
    sides = {room for room, _side, _delta in HL.SIDE_EXITS[L - 1]}
    for room in range(7):
        has_hole = "." in BANDS[room]["C"]
        assert has_hole or room in sides, f"room {room} has no way on"
    assert "." not in BANDS[7]["C"], "the miner's room has no hole"
    assert 1 not in {r for r in range(8) if "." in BANDS[r]["C"]}


def test_room_0_is_the_only_wall_that_must_be_blasted():
    """Its pillar at x 60-67 is the same pillar in the ceiling, so it cannot
    be flown over, and the floor hole is on its far side."""
    zones = HL.DESTRUCTIBLE[L - 1]
    assert zones[0] == (0, 60, 16, 8, 83, 1)
    assert BANDS[0]["A"][13:15] == "##" and BANDS[0]["B"][13:15] == "##"


def test_the_four_blastable_pillars_are_the_four_two_cell_ones():
    """A stick takes a two-cell corridor pillar and nothing wider, and never
    one that reaches the side of the screen."""
    assert HL.DESTRUCTIBLE[L - 1] == [(0, 60, 16, 8, 83, 1), (4, 52, 60, 8, 39, 1),
                                      (5, 48, 60, 8, 39, 1), (6, 56, 60, 8, 39, 1)]
    expect = []
    for room, band in enumerate(BANDS):
        for first, last in runs_of(band["B"], "#") + runs_of(band["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            expect.append((room, cells(first, last)[0]))
    assert [(z[0], z[1]) for z in HL.DESTRUCTIBLE[L - 1]] == sorted(expect)


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    """Room 0's ceiling IS that pillar, so both bands go. Rooms 4, 5 and 6
    carry theirs under a solid ceiling slab and only the corridor cells go."""
    for room, x, y, w, h, _ok in HL.DESTRUCTIBLE[L - 1]:
        cell = (x - 8) // 4
        same = BANDS[room]["A"][cell:cell + 2] in ("##", "%%")
        ceiling_is_the_pillar = (cell, cell + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if ceiling_is_the_pillar else (60, 39))
        assert same or not ceiling_is_the_pillar


def test_the_magma_pillars_of_rooms_5_and_6_are_blastable():
    """Magma is rock that glows: a stick takes a two-cell magma pillar for the
    same 75 points, and rooms 5 and 6 each have one in mid-corridor."""
    for room, x in ((5, 48), (6, 56)):
        cell = (x - 8) // 4
        assert BANDS[room]["B"][cell:cell + 2] == "%%"
        assert any(z[0] == room and z[1] == x for z in HL.DESTRUCTIBLE[L - 1])
        assert any(m[0] == room and m[1] == x for m in HL.MAGMA[L - 1])


def test_the_shared_wall_table_is_empty():
    common.check_shared_walls(L)


# --- objects ----------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_miner(L, BANDS)
    common.check_destructibles(L, BANDS)
    common.check_creatures_are_sane(L)


def test_the_miner_stands_where_the_rom_puts_him(env):
    assert HL.MINER_POS[L - 1] == (7, 128, 87)
    assert list(np.asarray(env.consts.LEVEL_MINER[L - 1])) == [7, 128, 87]


def test_the_four_lanterns_hang_in_the_ceilings_of_rooms_1_3_5_and_6():
    """Rooms 2, 4 and 7 have none. The census had one in room 4 at (79, 35);
    the capture found no lamp yellow anywhere in that room, and room 1's -
    which the census missed - is there."""
    assert HL.LANTERNS[L - 1] == [(1, 83, 35), (3, 131, 35),
                                  (5, 131, 35), (6, 83, 35)]
    assert [r for r, _x, _y in HL.LANTERNS[L - 1]] == [1, 3, 5, 6]
    for _room, _x, y in HL.LANTERNS[L - 1]:
        assert 16 <= y <= 59, "the ceiling band"


def test_the_seven_creatures_are_where_the_rom_draws_them():
    """Four bats, two still spiders and a snake. A bat's x is the CENTRE of
    its sweep, so it is the measured left column plus the half-travel.

    The untethered spider (kind 4) is the ROM's OTHER spider: no thread, seven
    rows of warm body on their own, flipping between two poses. It was drawn
    with a hanging spider's thread until its sprite was read off the ROM
    (level_images/tools/creature_atlas.py, 2026-09-23). Its second pose is
    drawn two rows below its first, so its measured BOX is 9 px taller than
    the sprite while the creature itself travels 7 - the art carries the
    other two.

    Room 6's is one of those, and a STILL one: the ROM draws it as a single
    bitmap for 140 consecutive frames.
    """
    assert HL.SPIDERS[L - 1] == [(1, 31, 64, 11, 1), (2, 76, 71, 0, 0),
                                 (2, 103, 104, 11, 1), (4, 31, 64, 11, 1),
                                 (4, 128, 111, 0, 3), (6, 112, 111, 0, 4),
                                 (7, 87, 65, 11, 1)]
    kinds = [k for *_r, k in HL.SPIDERS[L - 1]]
    assert (kinds.count(0), kinds.count(4),
            kinds.count(1), kinds.count(3)) == (1, 1, 4, 1), (
        "one hanging spider, one untethered, four bats and a snake")


def test_no_creature_of_this_level_falls_back_to_an_archetype():
    """Every slot carries its own measured motion; the kind-based defaults are
    for the levels nobody has remeasured."""
    for slot in range(len(HL.SPIDERS[L - 1])):
        assert (L, slot) in HL.CREATURE_MOTION


def test_the_four_bats_hold_each_wing_pose_four_frames_and_sweep_on_184():
    """CHARACTERS.md: a bat patrols 22 px on a 184-frame horizontal period and
    bobs 7 px on a 64-frame one, holding each wing pose 4 frames. Nothing else
    on this level shares that rhythm."""
    for slot, (_room, _x, _y, patrol, kind) in enumerate(HL.SPIDERS[L - 1]):
        if kind != 1:
            continue
        travel, half, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half, hold) == (7, 64, 4)
        assert patrol == 11 and 2 * HL.CREATURE_PATROL[(L, slot)] == 184


def test_the_still_creatures_carry_no_patrol_at_all():
    """33 of 44 bats and 39 of 50 spiders in the scanned rooms never move, and
    whether a creature moves is a property of the room. The two spiders and
    the snake of this level are among the still ones."""
    for slot, (_room, _x, _y, patrol, kind) in enumerate(HL.SPIDERS[L - 1]):
        if kind == 1:
            continue
        travel, half, _hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, half, patrol) == (0, 0, 0)
        assert (L, slot) not in HL.CREATURE_PATROL


def test_the_snake_is_a_snake_and_stretches_out_of_the_rock(env):
    """The snake in room 4 is kind 3, not a spider: the ROM draws it green
    whatever the cave's hue, anchored in the rock at x 127 and stretching
    rightwards out of it on the 64-frame cycle measured on level 4.

    This one is planted in an EIGHT pixel corridor (x 128-135, rock either
    side), so at full stretch it very nearly seals the gap and the way past
    it is the 8 frames in every 64 it spends pulled in. That only works
    because its box is what it is drawn in - see
    tests/games/hero/test_level4.py::test_a_snake_inside_the_rock_*.
    """
    from jaxatari.games.jax_hero import _snake_length
    slot = next(i for i, (*_r, k) in enumerate(HL.SPIDERS[L - 1]) if k == 3)
    room, x, y, patrol, _kind = HL.SPIDERS[L - 1][slot]
    assert (room, x, y, patrol) == (4, 128, 111, 0)
    assert int(env.consts.SPIDER_KIND[L - 1, slot]) == 3

    bg = HL.decode_bg(HL.BG_RLE_L5[room], HL.PALETTE_L5)
    solid = np.any(bg > 16, axis=-1)
    mid = y + 3
    assert solid[mid, x - 1], "anchored in the rock to its left"
    assert not solid[mid, x], "and drawn into the open corridor"
    assert solid[mid, x + 8], "an eight-pixel gap, all but sealed at full stretch"

    seen = {int(_snake_length(np.int32(t))) for t in range(64)}
    assert seen == set(range(8)), "every length from pulled in to 7 px out"


def test_the_still_creatures_never_leave_their_pixel(env):
    """A patrol is a property of the room, so a still creature must be drawn
    on the same pixel on every frame of a long run."""
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    lvl = L - 1
    for slot, (*_r, patrol, kind) in enumerate(HL.SPIDERS[L - 1]):
        if kind == 1:
            continue
        xs, ys = zip(*[(int(_creature_pos(c, lvl, np.int32(t))[0][slot]),
                        int(_creature_pos(c, lvl, np.int32(t))[1][slot]))
                       for t in range(0, 400, 7)])
        assert len(set(xs)) == 1 and len(set(ys)) == 1


def test_a_bat_really_sweeps_twenty_two_pixels(env):
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    lvl = L - 1
    slot = next(i for i, (*_r, k) in enumerate(HL.SPIDERS[L - 1]) if k == 1)
    xs = [int(_creature_pos(c, lvl, np.int32(t))[0][slot]) for t in range(400)]
    assert max(xs) - min(xs) == 22


# --- the flooded floor and the level start ----------------------------------
def test_the_flooded_floor_is_the_bottom_rows_of_room_7():
    """The miner's room is the only one with liquid, and it is a surface on
    the floor, not a hole: room 7's floor band is solid rock right across."""
    assert [d[0] for d in HL.DEADLY[L - 1]] == [7]
    _room, x, y, w, h = HL.DEADLY[L - 1][0]
    assert y + h <= 142 and y >= 136, "the last rows of the floor band"
    assert "." not in BANDS[7]["C"]


def test_room_0_is_brown_and_not_something_else():
    """Level 5's hue is brown, which is also level 1's, so the room 0 palette
    fix cannot be seen here - but the shades still have to be the level's."""
    palette, bgs = common.level_data(L)
    for role in ("edge", "dark", "mid", "light"):
        assert common.rgb(HL.SHADES[L][role]) in palette


# --- the level is finishable ------------------------------------------------
def _settle(env, s, budget=200):
    """Let him fall to the floor of the room he has just entered.

    He arrives at y = -3, above the ceiling band, and UP there lifts him
    straight back out of the top of the room, so nothing may steer until he
    is down."""
    room = int(s.room)
    for _ in range(budget):
        if int(s.player_y) > 60 and float(s.player_vy) == 0.0:
            return s
        _, s, _, _, _ = env.step(s, NOOP)
        if int(s.room) != room:
            return s
    return s


def _go(env, s, target, air):
    """Cross the room to `target`, flying if `air` and walking if not."""
    s = _settle(env, s)
    room = int(s.room)
    for _ in range(600):
        x = int(s.player_x)
        if x == target:
            return s
        if air:
            a = 6 if x < target else 7            # UPRIGHT / UPLEFT
        else:
            a = 8 if x < target else 9            # RIGHTFIRE / LEFTFIRE
        _, s, _, _, _ = env.step(s, a)
        if int(s.room) != room:
            return s
    return s


def _fall(env, s, budget=300):
    room = int(s.room)
    for _ in range(budget):
        _, s, _, _, _ = env.step(s, NOOP)
        if int(s.room) != room:
            return s
    return s


def test_level_5_can_be_played_from_the_spawn_to_the_miner(env):
    """The whole level, on the real engine, without losing a life.

    This is the check the level block could not pass before the side exit was
    measured: room 1 has no hole and nothing blastable, so the route simply
    stopped there.
    """
    import jax.numpy as jnp
    c = env.consts
    _, s = env.reset()
    s = s.replace(level=jnp.int32(L - 1))
    assert int(s.room) == 0 and int(s.lives) == c.starting_lives

    # room 0: blast the pillar at x 60-67, fly over the rubble, drop at x 78
    for _ in range(40):
        _, s, _, _, _ = env.step(s, RIGHT)
    _, s, _, _, _ = env.step(s, DOWN)
    assert bool(s.dyn_active), "a stick goes down on solid ground"
    for _ in range(30):
        _, s, _, _, _ = env.step(s, LEFT)
    for _ in range(c.dyn_fuse_playable + 8):
        _, s, _, _, _ = env.step(s, NOOP)
    assert int(s.score) == c.wall_points, "the pillar pays 75"
    s = _fall(env, _go(env, s, 78, air=True))
    assert int(s.room) == 1

    # room 1: shoot the bat, then walk out of the open LEFT edge
    s = _settle(env, s)
    for _ in range(400):
        # the bolt only reaches 23 px and LEFTFIRE walks him left as it fires,
        # so step back right whenever he drifts inside the bat's box
        _, s, _, _, _ = env.step(s, 8 if int(s.player_x) < 54 else 9)
        if not bool(s.spider_alive[0]):
            break
    assert not bool(s.spider_alive[0]), "the bat of room 1 can be shot"
    for _ in range(300):
        _, s, _, _, _ = env.step(s, LEFT)
        if int(s.room) != 1:
            break
    assert int(s.room) == 2, "room 1 is left through its left edge"

    # rooms 2-6: cross to the hole that lands him somewhere survivable
    #   2 -> x 78, so he drops through room 3's safe corridor (magma either
    #        side of x 48-111) and straight on through its hole at x 76-83
    #   4 -> x 130 (hole at x 128-135), 5 -> x 78, 6 -> x 114
    for room, target, air in ((2, 78, True), (4, 130, False),
                              (5, 78, False), (6, 114, False)):
        assert int(s.room) == room
        s = _fall(env, _go(env, s, target, air))
        if room == 2:
            assert int(s.room) == 3
            s = _fall(env, s)               # room 3 is fallen straight through
    assert int(s.room) == 7

    # room 7: walk to the miner at x 128
    s = _settle(env, s)
    for _ in range(400):
        _, s, _, _, _ = env.step(s, 8 if int(s.player_x) < 126 else NOOP)
        if int(s.level) != L - 1:
            break
    assert int(s.level) == L, "rescuing the miner advances to level 6"
    assert int(s.lives) == c.starting_lives, "and it costs no lives"
    assert int(s.score) > 1000 + c.wall_points


def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black."""
    from jaxatari.games.jax_hero import HeroRenderer
    r = HeroRenderer(env.consts)
    _, s = env.reset()
    s = s.replace(level=np.int32(L - 1), room=np.int32(0))
    img = np.asarray(r.render(s))
    assert img[189:210, :, :3].sum() == 0
