"""Level 6, against the corrected ROM reference.

The block in hero_levels.py is generated by tools/hero_gen/build_level.py,
which walks the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), then play the level.

Level 6 is the last of the levels CORRECTIONS.md calls complete, and the
first one whose CREATURES are not all animated on one clock. The geometry
came straight out of the walk - ten rooms, no room refused, no `?` cell, and
`hero_extract.py verify 6` reports 0 band mismatches - so the interesting
work was all in the cast:

  * THE BOBBING SPIDERS BOB ON 72 FRAMES, NOT 64. 64 is the BAT's vertical
    cycle. The capture votes over a short window and quantises the one onto
    the other; the census watches 420 frames and autocorrelates, and it puts
    the spider at 70/72 against the bat's 184/64 - which is what CHARACTERS.md
    and CORRECTIONS.md both say. Rooms 1, 5 and 7 have one each.
  * SIX OF THE ELEVEN CREATURES ARE STILL. "Whether a creature moves is a
    property of the room, not of the creature" (CHARACTERS.md): the census
    sees these six draw a single sprite for the whole scan, so they are drawn
    as a single sprite. Before CREATURE_SPRITES the pose clock ran for them
    too and a spider the ROM never redraws swapped its legs every 8 frames.
  * THE POSE HOLD IS STILL THE CAPTURE'S, deliberately. The census reports 1
    frame per sprite for every bobbing spider, and that is the artefact that
    made level 4's snakes "14 poses of 1 frame each" - the component pass
    splits the 1 px thread off the body and rejoins it, so the mask changes
    every frame while the ROM has redrawn nothing.

Magma is in the five EVEN rooms, and in each of them every solid corridor
cell is magma, because the corridor colour register is either the level hue
or magma red and nothing in between.

The route, room by room:

    room 0  magma corridor, blocked by the pillar at x 60-67 whose ceiling is
            the same pillar -> plant a stick, run, +75, then down the hole at
            x 72-87
    room 1  a lantern, a bobbing spider at x 96 and a bat patrolling the FLOOR
            band; a pillar at x 60-67 and holes at x 20-55 and x 104-139
    room 2  magma; the pillar at x 92-99 and the hole at x 72-87
    room 3  the widest corridor of the level, a patrolling bat at x 32-60 and
            a still spider on the floor; four two-cell holes
    room 4  magma down both sides and a magma pillar at x 76, holes at
            x 52-59 and x 100-107
    room 5  an eleven-cell slab in mid-corridor - too wide to blast, so it is
            flown around; a bobbing spider at x 112, a still one at x 60, and
            one wide hole from x 40 to x 115
    room 6  magma at the edges only, a still spider at x 24, holes at x 24-31
            and x 128-135
    room 7  a bobbing spider at x 64, a still one at x 104, the pillar at
            x 76-83 and holes at x 48-55 and x 104-111
    room 8  magma, the pillar at x 60-67, the hole at x 72-87
    room 9  the miner's room: sealed floor, a flooded trim, a still spider at
            x 53 and the miner at x 25
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

NOOP, FIRE, UP, RIGHT, LEFT, DOWN = 0, 1, 2, 3, 4, 5
L = 6

# What the ROM draws, cell for cell, in descent order. Generated by
# tools/hero_gen/build_level.py and verified by it against
# level_images/hero_rooms.py before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "%%...........%%...................%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "##...........##...................####",
     "C": "###.........############.........#####"},
    {"A": "###.........############.........#####",
     "B": "%%...................%%...........%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "####............................######",
     "C": "#####..#####..########..#####..#######"},
    {"A": "#####..#####..########..#####..#######",
     "B": "%%%%%%%%%%.......%%.......%%%%%%%%%%%%",
     "C": "###########..##########..#############"},
    {"A": "###########..##########..#############",
     "B": "##.........###########.........#######",
     "C": "########....................##########"},
    {"A": "########....................##########",
     "B": "%%................................%%%%",
     "C": "####..########################..######"},
    {"A": "####..########################..######",
     "B": "##...............##...............####",
     "C": "##########..############..############"},
    {"A": "##########..############..############",
     "B": "%%%%.........%%.................%%%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "####............................######",
     "C": "######################################"},
]

# CHARACTERS.md, "Level 6 (10 of 10 rooms scanned, 20 entities)", as
# (room, what, x, y). Room 0 has NO row: no entity was measured there, and
# none is invented here.
#
# The two bats are the one place this table and HL.SPIDERS do not print the
# same number, and they are not measuring the same thing. CHARACTERS.md gives
# the tight box of the ink the scan saw most of the time; HL.SPIDERS gives the
# CENTRE of the patrol, derived from the envelope the sprite is ever drawn in.
# Room 1's bat: tight box (26, 104), envelope x 24-52, so centre 24 + 11 = 35
# and the left edge sweeps 24..46. Both come from the same census row.
CHARACTERS_MD = [
    (1, "lantern", 83, 35),
    (1, "spider", 96, 65),
    (1, "bat", 26, 104),
    (2, "lantern", 135, 35),
    (2, "spider", 80, 109),
    (3, "lantern", 83, 35),
    (3, "bat", 34, 65),
    (3, "spider", 96, 109),
    (4, "lantern", 99, 35),
    (5, "lantern", 55, 35),
    (5, "spider", 112, 65),
    (5, "spider", 60, 109),
    (6, "lantern", 115, 35),
    (6, "spider", 24, 109),
    (7, "lantern", 27, 35),
    (7, "spider", 64, 65),
    (7, "spider", 104, 109),
    (8, "lantern", 107, 35),
    (9, "spider", 53, 70),
    (9, "miner", 25, 86),
]


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


# --- geometry ---------------------------------------------------------------
def test_level_6_is_ten_green_rooms():
    common.check_shape(L, "green", rooms=10)
    assert len(HL.BG_RLE_L6) == 10


def test_all_ten_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_across_all_ten_rooms():
    """Room N's ceiling is drawn identically to room N-1's floor. This is the
    invariant the corrected capture is checked against, and it is what the
    first pass broke."""
    for room in range(1, len(BANDS)):
        assert BANDS[room]["A"] == BANDS[room - 1]["C"]


def test_the_corridors_are_not_all_room_0s():
    """The superseded capture kept room 0's corridor for every room, which is
    exactly what was wrong with the level-6 block this one replaces.

    Only room 0 draws room 0's corridor. Two rooms DO share one - 3 and 9 are
    both `####...`+`######` - and that is the ROM keeping one copy of each
    distinct band pattern, not the capture bug: the bug made every room match
    room 0, and room 0 is unique here.
    """
    corridors = [b["B"] for b in BANDS]
    assert corridors.count(corridors[0]) == 1
    assert len(set(corridors)) == 9
    twins = [r for r, b in enumerate(BANDS) if b["B"] == BANDS[3]["B"]]
    assert twins == [3, 9], "rooms 3 and 9 are the only pair that share one"


def test_no_cell_was_left_uncalled():
    assert "?" not in "".join(b[k] for b in BANDS for k in "ABC")


def test_level_6_has_no_liquid_floor():
    """The `~` trap is real, but not on this level: the walk reached all ten
    rooms and not one floor cell is liquid. The DEADLY row for room 9 is the
    flooded TRIM at the bottom of the miner's room, rows 139-141, the same
    shape level 5 room 7 has - not a `~` band cell."""
    assert "~" not in "".join(b[k] for b in BANDS for k in "ABC")
    assert HL.DEADLY[L - 1] == [(9, 8, 139, 152, 3)]
    room, _x, y, _w, h = HL.DEADLY[L - 1][0]
    assert room == 9 and y + h - 1 == 141, "the trim sits on the last rows"
    assert "." not in BANDS[9]["C"], "the miner's floor is sealed"


# --- magma ------------------------------------------------------------------
def test_the_magma_is_in_the_five_even_rooms():
    """Magma is a property of the ROOM: the corridor colour register is either
    the level hue or magma red, so in a magma room every solid corridor cell
    is magma and in any other room none is."""
    magma_rooms = sorted({r for r, *_rest in HL.MAGMA[L - 1]})
    assert magma_rooms == [0, 2, 4, 6, 8]
    for room in magma_rooms:
        assert "#" not in BANDS[room]["B"], \
            "in a magma room every solid corridor cell is magma"
    for room in range(10):
        if room not in magma_rooms:
            assert "%" not in BANDS[room]["B"]


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


def test_magma_never_leaves_the_corridor_band():
    """Every magma rect is the corridor band's own rows. The ceiling and the
    floor of a magma room are ordinary rock."""
    for _room, _x, y, _w, h in HL.MAGMA[L - 1]:
        assert (y, h) == (60, 39)


# --- blastable walls --------------------------------------------------------
def test_the_six_blastable_pillars_are_the_six_two_cell_ones():
    """A stick takes a two-cell corridor pillar and nothing wider, and never
    one that reaches the side of the screen. Room 5's eleven-cell slab and
    room 3's open corridor are why those two rooms have none."""
    assert HL.DESTRUCTIBLE[L - 1] == [
        (0, 60, 16, 8, 83, 1),
        (1, 60, 60, 8, 39, 1),
        (2, 92, 60, 8, 39, 1),
        (4, 76, 60, 8, 39, 1),
        (7, 76, 60, 8, 39, 1),
        (8, 60, 60, 8, 39, 1),
    ]
    expect = []
    for room, band in enumerate(BANDS):
        for first, last in runs_of(band["B"], "#") + runs_of(band["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            expect.append((room, cells(first, last)[0]))
    assert [(z[0], z[1]) for z in HL.DESTRUCTIBLE[L - 1]] == sorted(expect)


def test_room_5s_eleven_cell_slab_is_not_blastable():
    """Dynamite breaks a two-cell pillar and wider runs are immune, so the
    slab at cells 11-21 has to be flown around, not blown up."""
    assert runs_of(BANDS[5]["B"], "#") == [(0, 1), (11, 21), (31, 37)]
    assert [z for z in HL.DESTRUCTIBLE[L - 1] if z[0] == 5] == []


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    """Room 0's ceiling IS that pillar, so both bands go. The rest carry
    theirs under a solid ceiling slab and only the corridor cells go."""
    for room, x, y, w, h, _ok in HL.DESTRUCTIBLE[L - 1]:
        cell = (x - 8) // 4
        ceiling_is_the_pillar = (cell, cell + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if ceiling_is_the_pillar else (60, 39))
    assert BANDS[0]["A"][13:15] == "##" and BANDS[0]["B"][13:15] == "%%"


def test_the_magma_pillars_are_blastable():
    """Magma is rock that glows: a stick takes a two-cell magma pillar for the
    same 75 points. Four of the six are magma."""
    magma_zones = [z for z in HL.DESTRUCTIBLE[L - 1] if z[0] in (0, 2, 4, 8)]
    assert len(magma_zones) == 4
    for room, x, *_rest in magma_zones:
        cell = (x - 8) // 4
        assert BANDS[room]["B"][cell:cell + 2] == "%%"
        assert any(m[0] == room and m[1] == x for m in HL.MAGMA[L - 1])


def test_the_shared_wall_table_is_empty():
    """Two rooms that draw the identical band are NOT one physical wall
    (measured on level 4 rooms 5 and 6: blast one pillar and the twin
    stands). Rooms 0 and 8 both carry a pillar at x 60 and they are two."""
    common.check_shared_walls(L)
    assert HL.SHARED_WALLS[L - 1] == []


# --- routes -----------------------------------------------------------------
def test_level_6_has_no_side_exits():
    """A side exit is an open corridor cell at the very edge of the screen.
    Every one of level 6's corridors is walled at both ends, so the whole
    level descends through its floors."""
    assert HL.SIDE_EXITS[L - 1] == []
    for room, band in enumerate(BANDS):
        assert band["B"][0] != ".", f"room {room} opens at the left edge"
        assert band["B"][37] != ".", f"room {room} opens at the right edge"


def test_every_room_but_the_last_has_a_hole():
    for room in range(9):
        assert "." in BANDS[room]["C"], f"room {room} has no way on"
    assert "." not in BANDS[9]["C"], "the miner's room has no hole"


def test_room_0_must_be_blasted_to_reach_its_hole():
    """Its pillar at x 60-67 is the same pillar in the ceiling, so it cannot
    be flown over, and the hole at x 72-87 is on its far side."""
    assert HL.DESTRUCTIBLE[L - 1][0] == (0, 60, 16, 8, 83, 1)
    assert runs_of(BANDS[0]["C"], ".") == [(16, 19)]
    assert cells(16, 19) == (72, 16)


# --- objects ----------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_miner(L, BANDS)
    common.check_destructibles(L, BANDS)
    common.check_creatures_are_sane(L)


def test_every_entity_in_characters_md_is_present():
    """The level's whole cast, room by room, against CHARACTERS.md.

    Lanterns, spiders and the miner are compared exactly. A BAT is compared
    against its patrol envelope instead of the centre the table prints - see
    the note on CHARACTERS_MD above - and the tolerance is the 2 px the tight
    box trims off the spread wing, never more.
    """
    got = [(r, "lantern", x, y) for r, x, y in HL.LANTERNS[L - 1]]
    got.append(("miner",) and (HL.MINER_POS[L - 1][0], "miner",
                               HL.MINER_POS[L - 1][1], HL.MINER_POS[L - 1][2]))
    # CHARACTERS.md calls both of the ROM's spiders a "Spider" in this level,
    # and it is right to: kind 0 is the one that hangs under a thread and
    # kind 4 the one that floats without one, and they are the same animal as
    # far as the table is concerned. (In level 7 the census loses track of
    # that and calls a still kind 4 a "Bat", which is what made this
    # distinction worth measuring - see test_level7.)
    kinds = {0: "spider", 1: "bat", 4: "spider"}
    for room, x, y, patrol, kind in HL.SPIDERS[L - 1]:
        got.append((room, kinds[kind], x - patrol, y))

    assert len(got) == len(CHARACTERS_MD) == 20
    for room, what, x, y in CHARACTERS_MD:
        near = [g for g in got
                if g[0] == room and g[1] == what
                and abs(g[2] - x) <= 2 and abs(g[3] - y) <= 1]
        assert near, f"CHARACTERS.md row ({room}, {what}, {x}, {y}) is missing"
        if what != "bat":
            assert (room, what, x, y) in got, \
                f"({room}, {what}) must match CHARACTERS.md exactly"


def test_room_0_has_no_creature_and_none_was_invented():
    """CHARACTERS.md has no row for room 0, so nothing is placed there."""
    assert [c for c in HL.SPIDERS[L - 1] if c[0] == 0] == []
    assert [g for g in HL.LANTERNS[L - 1] if g[0] == 0] == []


def test_the_lanterns_hang_in_the_ceiling_band_on_row_35():
    """"Always in the ceiling band, top left of its 5x8 box on row 35"
    (CHARACTERS.md). Eight of the ten rooms have one; rooms 0 and 9 do not."""
    assert len(HL.LANTERNS[L - 1]) == 8
    assert {r for r, _x, _y in HL.LANTERNS[L - 1]} == set(range(1, 9))
    for _room, _x, y in HL.LANTERNS[L - 1]:
        assert y == 35


def test_the_miner_is_at_the_bottom_left_of_room_9():
    """One per level, in the last room, sprite top left on row 86, at x 25 on
    the left of the screen or x 128 on the right (CHARACTERS.md)."""
    assert HL.MINER_POS[L - 1] == (9, 25, 86)


# --- the clocks that are not shared -----------------------------------------
def test_the_three_bobbing_spiders_are_the_untethered_kind_on_64_frames():
    """Rooms 1, 5 and 7 each hold one, and all three are kind 4 - the spider
    with no thread, seven rows of warm body flipping between two poses.

    THE CYCLE IS 64 FRAMES, not the 72 this used to assert on the census's
    word. Measured directly on level 6 room 1 with the hero parked out of the
    picture: over 400 consecutive frames the whole (pose, position) sequence
    repeats exactly every 64, as two 32-frame halves, and never at 72. The
    census's 70/72 comes from autocorrelating the centre of a
    frame-difference blob, and that blob's box wanders because the two poses
    are different heights and are drawn two rows apart.
    """
    bobbing = [(slot, HL.CREATURE_MOTION[(L, slot)])
               for slot, c in enumerate(HL.SPIDERS[L - 1])
               if c[4] == 4 and HL.CREATURE_MOTION[(L, slot)][0] > 0]
    assert [s for s, _m in bobbing] == [1, 6, 8]
    for _slot, (travel, half, hold) in bobbing:
        assert travel == 7, "it moves 7 px; its art carries the other two"
        assert 2 * half == 64, "over 64 frames, not the census's 72"
        assert hold == 8, "and holds each of its two poses for 8 frames"
    # and they are the spiders of rooms 1, 5 and 7
    assert [HL.SPIDERS[L - 1][s][0] for s, _m in bobbing] == [1, 5, 7]


def test_the_bats_patrol_22_px_on_184_frames_and_hold_a_wing_pose_4():
    """"A bat patrols 22 px with a 184-frame horizontal period and a 64-frame
    vertical one, and holds each wing pose for 4 frames" (CHARACTERS.md). The
    two clocks are different lengths, so the path is a slow Lissajous figure
    and not a straight line."""
    bats = [slot for slot, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 1]
    assert bats == [0, 3]
    for slot in bats:
        travel, half, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half) == (7, 64), "the bat bobs 7 px on 64 frames"
        assert hold == 4, "and holds each wing pose for 4 frames"
        assert 2 * HL.CREATURE_PATROL[(L, slot)] == 184
        assert 2 * HL.SPIDERS[L - 1][slot][3] == 22, "22 px of patrol"
    assert HL.CREATURE_PATROL[(L, 0)] != HL.CREATURE_MOTION[(L, 0)][1], \
        "the bob and the patrol must not share a clock"


def test_a_creature_that_does_not_travel_may_still_animate():
    """Six of the eleven never move a pixel. Only TWO of those six are drawn
    as a single bitmap.

    This is the distinction the census cannot make and this test used to get
    wrong. "Still" was taken from the census's `distinct_sprites`, which
    reports 1 for creatures that plainly alternate two bitmaps every seven or
    eight frames, so four spiders that swap their legs on the spot were pinned
    to one pose. Counted over the capture's own 480 frames, rooms 2 and 6 draw
    ONE bitmap for the whole window and rooms 3, 5, 7 and 9 draw two.
    """
    still = [slot for slot, c in enumerate(HL.SPIDERS[L - 1])
             if HL.CREATURE_MOTION[(L, slot)][0] == 0]
    assert still == [2, 4, 5, 7, 9, 10]
    for slot in still:
        travel, half, _hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, half) == (0, 0), "a still creature does not travel"
        assert (L, slot) not in HL.CREATURE_PATROL, "and does not sweep"
    frozen = [s for s in still if HL.CREATURE_SPRITES.get((L, s)) == 1]
    assert frozen == [2, 7], "rooms 2 and 6 draw one bitmap all window"
    assert [HL.SPIDERS[L - 1][s][0] for s in frozen] == [2, 6]
    for slot in set(still) - set(frozen):
        assert (L, slot) not in HL.CREATURE_SPRITES, \
            "the other four keep both of their poses"


def test_the_moving_creatures_keep_their_kinds_full_cycle():
    """A creature that does move must NOT be pinned to one sprite: the three
    spiders keep both poses and the two bats keep all four wings."""
    for slot, c in enumerate(HL.SPIDERS[L - 1]):
        if HL.CREATURE_MOTION[(L, slot)][0] > 0:
            assert (L, slot) not in HL.CREATURE_SPRITES


def test_the_renderer_holds_a_still_creature_on_one_sprite(env):
    """The table is only half of it - the engine has to read it. Slot 2 is a
    still spider; its drawn pose must be the same on every frame, while the
    bat in slot 0 must cycle."""
    c = env.consts
    lvl = L - 1
    assert int(c.SPIDER_POSES[lvl, 2]) == 1, "the still spider is pinned"
    assert int(c.SPIDER_POSES[lvl, 0]) == 0, "the bat keeps its kind's cycle"
    hold = int(c.SPIDER_HOLD[lvl, 2])
    frames = {(step // hold) % max(1, int(c.SPIDER_POSES[lvl, 2]))
              for step in range(600)}
    assert frames == {0}, "a still creature never changes sprite"


def test_a_still_creature_never_moves_and_a_bobbing_one_does(env):
    """Position, not just artwork: over a full 184-frame sweep the still
    spider of room 2 must not shift by a pixel, and the bat must."""
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    lvl = L - 1
    seen_still, seen_bat, seen_spider = set(), set(), set()
    for step in range(400):
        x, y = _creature_pos(c, lvl, step)
        seen_still.add((int(x[2]), int(y[2])))
        seen_bat.add((int(x[0]), int(y[0])))
        seen_spider.add((int(x[1]), int(y[1])))
    assert seen_still == {(80, 109)}, "the still spider of room 2 never moves"
    assert len({p[0] for p in seen_bat}) > 1, "the bat patrols sideways"
    assert len({p[1] for p in seen_bat}) > 1, "and bobs"
    assert {p[0] for p in seen_spider} == {96}, "a spider does not translate"
    assert len({p[1] for p in seen_spider}) > 1, "but it does bob"


# --- the screen -------------------------------------------------------------
def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black. The HUD panel above them does not."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import HeroRenderer
    renderer = HeroRenderer(env.consts)
    _, s = env.reset()
    s = s.replace(level=jnp.int32(L - 1), room=jnp.int32(0))
    frame = np.asarray(renderer.render(s))[:, :, :3]
    assert frame.shape[0] >= 210
    assert frame[189:210].max() == 0, "rows 189-209 must stay black"
    assert frame[142:189].max() > 0, "the grey HUD panel is still drawn"
