"""Level 20, against the corrected ROM reference.

The block in hero_levels.py was generated by walking the level through the
game's own room-transition code, capturing each room off the real ROM and
refusing to emit anything unless the capture agreed with the reference cell
for cell. These tests re-check that agreement from the committed data alone
(no ale-py), and check the engine draws it.

What came out of level 20, the last level of the game:

  * THE WALK REACHES ALL SIXTEEN ROOMS. The reference had eleven (all read
    off the ROM, all confirmed); rooms 11-15 were appended from the walk.
  * THE OLD BLOCK WAS A PLACEHOLDER copy of level 16, the last one. Every
    table is new, and hero_levels.py no longer has a placeholder at all.
  * ITS CREATURES RUN AT LEVEL 18'S SPEED: fourteen bats sweep 22 px on 46
    frames and bob 7 px on 16; the five untethered spiders bob 7 px on 16,
    their pose locked to the direction. The seven hanging spiders are still.
  * ONE WALL SNAKE, room 3, in the CORRIDOR, grows out of the magma wall on
    its left a pixel every frame (the 16-frame cycle).
  * TWO WATER TENTACLES (kind 5), rooms 12 and 14, each pursuing between
    x 29 and 121. Room 14's was watched with every pose drawn two rows low;
    the capture re-reads a tentacle with the hero parked in the corridor
    (the same five poses as room 12's and level 17's, measured).
  * ROOM 5 BREATHES MAGMA (HL.MAGMA_MOUTHS), the eight air cells 14-21.
  * ONE RAFT (HL.RAFTS), room 11, at the LEFT end (x 28): the level
    descends RIGHT, so the hero comes in from the left.
  * THE LIQUID IS GREEN, #328432, as the reference says.
  * NINE CREATURES WERE 1-2 ROWS LOW in the capture and were re-read with the
    hero in the room - three of them (rooms 3, 5, 9) from parks the tool had
    never used: an 8-px gap off the 4-px grid, a gap beside the creature, and
    the first 16 frames in room 5's mouth before it shuts.
  * The old census had 17 entities in 10 rooms; the capture has 39
    (29 creatures, 9 lanterns, the miner) and the AtariAge map of the level
    agrees in every room, lamp for lamp. The census's room 10 corridor
    "spider" at (56, 66) is inside the rock.

The shape of the level, room by room:

    rooms 0-9   GREY; magma in every corridor but room 2's, which is rock.
    room 5      the breathing mouth over the way down.
    room 9      the only one of rooms 1-10 with no lamp.
    room 10     water under the whole floor; left through its open RIGHT edge.
    rooms 11-15 water from here to the end; the level descends RIGHT, every
                left edge leading back up. Rooms 11-13's way on is a two-cell
                magma pillar in front of the right edge, which a stick takes.
    room 11     a twenty-cell magma wall over the water, crossed on the raft.
    rooms 12,14 the tentacles.
    room 15     the miner's room, the miner at x 128.
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

L = 20

# What the ROM draws, cell for cell, in descent order, verified against the
# reference before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "%%...........%%...................%%%%",
     "C": "#################..###################"},
    {"A": "#################..###################",
     "B": "%%...................%%...........%%%%",
     "C": "####......################......######"},
    {"A": "####......################......######",
     "B": "######..####################..########",
     "C": "##................................####"},
    {"A": "##................................####",
     "B": "%%%%%%..%%%%%%%%%%%%%%%%%%%%..%%%%%%%%",
     "C": "##................................####"},
    {"A": "##................................####",
     "B": "%%%%%%%%%%%%............%%%%%%%%%%%%%%",
     "C": "##................................####"},
    {"A": "##................................####",
     "B": "%%%%%%%%%%%%%%........%%%%%%%%%%%%%%%%",
     "C": "####............................######"},
    {"A": "####............................######",
     "B": "%%........%%%%%%%%%%%%%%%%........%%%%",
     "C": "########....................##########"},
    {"A": "########....................##########",
     "B": "%%%%%%%%%%..%%%%%%%%%%%%..%%%%%%%%%%%%",
     "C": "####..........########..........######"},
    {"A": "####..........########..........######",
     "B": "%%..........%%%%%%%%%%%%..........%%%%",
     "C": "######........########........########"},
    {"A": "######........########........########",
     "B": "%%%%%%%%%%..%%%%%%%%%%%%..%%%%%%%%%%%%",
     "C": "###...........########...........#####"},
    {"A": "###...........########...........#####",
     "B": "##....########################........",
     "C": "###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#####"},
    {"A": "######################################",
     "B": "........%%%%%%%%%%%%%%%%%%%%.....%%...",
     "C": "####~~~~~~~~~~~~~~~~~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": "................%%%%............%%....",
     "C": "#####~~~~~~~~~~~~~~~~~~~~~~~~~~#######"},
    {"A": "######################################",
     "B": "..............%%%%%%%%..........%%....",
     "C": "######~~~~~~~~~~~~~~~~~~~~~~~~########"},
    {"A": "######################################",
     "B": "................%%%%..................",
     "C": "#####~~~~~~~~~~~~~~~~~~~~~~~~~~#######"},
    {"A": "######################################",
     "B": "................%%%%................%%",
     "C": "##########~~~~~~~~~~~~~~~~############"},
]

# The live-hero ROM capture (the data hero_levels.py ships), as
# (room, what, x, y) with x the LEFT edge of the drawn box - for a bat, of
# its sweep; for the tentacle, of its pursuit range. Every row.
# The AtariAge map of the level states the same.
CHARACTERS_MD = [
    (1, "lantern", 79, 35), (1, "bat", 52, 64), (1, "spider", 128, 109),
    (2, "lantern", 131, 35), (2, "spider_free", 32, 65), (2, "bat", 96, 103),
    (3, "lantern", 139, 35), (3, "spider", 40, 109), (3, "snake", 120, 72),
    (4, "lantern", 139, 35), (4, "bat", 56, 64), (4, "bat", 56, 103),
    (5, "lantern", 139, 35), (5, "bat", 44, 103),
    (6, "lantern", 131, 35), (6, "bat", 16, 64), (6, "spider", 112, 109),
    (7, "lantern", 115, 35), (7, "spider_free", 48, 65), (7, "bat", 104, 103),
    (8, "lantern", 131, 35), (8, "spider_free", 48, 66), (8, "bat", 96, 103),
    (9, "spider", 112, 109),
    (10, "lantern", 135, 35), (10, "bat", 76, 103), (10, "spider", 136, 70),
    (11, "spider_free", 32, 65), (11, "spider", 76, 109),
    (12, "bat", 28, 64), (12, "tentacle", 29, 126), (12, "spider", 112, 109),
    (13, "spider_free", 36, 65), (13, "bat", 100, 103),
    (14, "tentacle", 29, 126), (14, "bat", 44, 64), (14, "bat", 104, 103),
    (15, "bat", 24, 64), (15, "miner", 128, 86),
]

KIND_NAME = {0: "spider", 1: "bat", 3: "snake", 4: "spider_free", 5: "tentacle"}
WATER_ROOMS = set(range(10, 16))
ROCK_CORRIDORS = {2, 10}
LIQUID = "#328432"
TENTACLE_BLUE = (101, 183, 217)
TENTACLE_ROOMS = (12, 14)

# The mouth, measured on the ROM frame by frame from arrival: cells of the
# 8-cell gap OPEN, e frames after the room was entered (e = 0 is the
# transition frame). The same sequence as every other mouth in the game.
ROM_OPEN = "4" * 8 + "2" * 8 + "0" * 8 + "2" * 8 + "4" * 8 + "6" * 8 + "8" * 8 + "6" * 8
# A snake at the 16-frame cycle, px out of the rock per frame on the ROM.
ROM_SNAKE = [0, 1, 2, 3, 4, 5, 6, 7, 7, 6, 5, 4, 3, 2, 1, 0]


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


def shipped():
    """{(room, what, left x, top y)} for every creature SPIDERS carries."""
    return {(r, KIND_NAME[k], x - half, y)
            for r, x, y, half, k in HL.SPIDERS[L - 1]}


def of_kind(k):
    return [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == k]


def _state(env, room, **kw):
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    fields = dict(level=jnp.int32(L - 1), room=jnp.int32(room),
                  room_timer=jnp.int32(0), has_moved=jnp.bool_(True),
                  banner_timer=jnp.int32(0),
                  spider_alive=env.consts.SPIDER_VALID[L - 1])
    fields.update(kw)
    return state.replace(**fields)


def _tentacle_slot(room):
    (slot, _row), = [(i, c) for i, c in of_kind(5) if c[0] == room]
    return slot


# --- geometry ---------------------------------------------------------------
def test_level_20_is_sixteen_grey_rooms():
    common.check_shape(L, "grey", rooms=16)
    assert len(HL.BG_RLE_L20) == 16


def test_all_sixteen_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_the_level_is_complete_and_nothing_is_missing():
    """The old reference listed level 20 as 11 of 16 rooms. The walk reached
    all sixteen on 2026-09-27."""
    assert len(BANDS) == 16
    assert len({(b["A"], b["B"], b["C"]) for b in BANDS}) == 16, \
        "no ROOM is a copy of another"


def test_it_is_no_longer_a_copy_of_level_16():
    assert HL.BG_RLE_L20 != HL.BG_RLE_L16
    assert HL.SPIDERS[19] != HL.SPIDERS[15]
    assert not hasattr(HL, "_PLACEHOLDER_SRC"), "no level is a placeholder any more"


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_every_ceiling_is_the_floor_above_it():
    """Rooms 1-10 are entered through a hole; rooms 11-15 sideways, under a
    ceiling that is solid across the screen - and the room before each of
    those has a floor solid (rock or liquid) across the screen too, so the
    chain holds for every room."""
    for i in range(1, 16):
        assert BANDS[i]["A"] == BANDS[i - 1]["C"].replace("~", "#"), \
            f"chain breaks between rooms {i - 1} and {i}"
    for i in range(11, 16):
        assert BANDS[i]["A"] == "#" * 38, f"room {i}"


def test_no_cell_was_left_uncalled():
    for i, room in enumerate(BANDS):
        for band, s in room.items():
            assert "?" not in s, f"room {i} band {band} has an uncalled cell"
            assert set(s) <= set("#%.~"), f"room {i} band {band} has a stray value"


# --- the water --------------------------------------------------------------
def test_the_liquid_cells_are_in_the_water_rooms_only():
    with_liquid = {i for i, r in enumerate(BANDS) if "~" in r["C"]}
    assert with_liquid == WATER_ROOMS


def test_no_room_from_10_on_has_a_hole_to_fall_through():
    for room in range(10, 16):
        assert "." not in BANDS[room]["C"], f"room {room} floor has a real hole"


def test_a_liquid_cell_is_solid_only_on_the_rows_it_is_drawn_on():
    y0, y1 = common.LIQUID_ROWS
    for room in WATER_ROOMS:
        liquid_x = {8 + 4 * i for i, c in enumerate(BANDS[room]["C"]) if c == "~"}
        for x, y, w, h in HL.WALL_RECTS_L20[room]:
            if x in liquid_x and y >= 99:
                assert (y, h) == (y0, y1 - y0 + 1), (
                    f"room {room}: the liquid rect at x {x} is {h} px tall "
                    f"from row {y}; it must be rows {y0}-{y1}")


def test_the_deadly_rects_are_the_water_line():
    assert HL.DEADLY[L - 1] == [(room, 8, 136, 152, 6) for room in sorted(WATER_ROOMS)]


def test_the_liquid_is_the_jsons_green():
    """The reference says #328432 and the ROM paints (50, 132, 50) on the
    water rows of rooms 10-15 and nowhere else; the AtariAge map draws it
    green too."""
    palette, rooms = common.level_data(L)
    assert common.rgb(LIQUID) in palette
    for i, img in enumerate(rooms):
        ys, _xs = np.nonzero((img == np.array(common.rgb(LIQUID))).all(axis=-1))
        if i >= 10:
            assert ys.size and ys.min() >= 136, f"room {i}"
        else:
            assert not ys.size, f"room {i} paints the liquid colour"


def test_no_creature_is_painted_into_the_cave():
    """The raft's yellow and the tentacles' blue are drawn by the engine; the
    generator takes the tentacles out of rooms 12 and 14's water - room 14's
    head too, which stood in the air of its '~' cells at row 134."""
    palette, rooms = common.level_data(L)
    assert TENTACLE_BLUE not in [tuple(p) for p in palette]
    rotor = np.array(common.rgb("#e8e84a"))
    for i, img in enumerate(rooms):
        for colour in (rotor, np.array(TENTACLE_BLUE)):
            ys, xs = np.nonzero((img == colour).all(axis=-1))
            assert not ys.size, f"room {i} paints {colour} at {xs[0]},{ys[0]}"


# --- the raft ---------------------------------------------------------------
def test_room_11_is_crossed_on_a_raft_from_the_left():
    assert HL.RAFTS[L - 1] == [(11, 28)]
    assert (8, 27) in runs_of(BANDS[11]["B"], "%")
    assert BANDS[11]["A"] == "#" * 38
    assert BANDS[11]["C"][4:32] == "~" * 28


def test_the_engine_floats_the_raft_in_room_11_only(env):
    rafts = np.asarray(env.consts.RAFT_IN[L - 1])
    assert set(np.nonzero(rafts)[0]) == {11}


# --- magma ------------------------------------------------------------------
def test_magma_is_a_property_of_the_room():
    """In a magma room every solid corridor cell is magma; in the others
    every one is rock."""
    for i, room in enumerate(BANDS):
        if i in ROCK_CORRIDORS:
            assert "%" not in room["B"] and "#" in room["B"], f"room {i}"
        else:
            assert "%" in room["B"] and "#" not in room["B"], f"room {i}"


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


def test_magma_never_leaves_the_corridor_band():
    for _room, _x, y, _w, h in HL.MAGMA[L - 1]:
        assert (y, h) == (60, 39), "magma is a corridor register, not a band"


def test_no_magma_is_carried_as_a_creature():
    assert not any(row[4] == 2 for row in HL.SPIDERS[L - 1])


def test_nothing_flares():
    assert HL.FLARES[L - 1] == []


# --- the magma mouth --------------------------------------------------------
def test_room_5_is_the_levels_mouth():
    assert HL.MAGMA_MOUTHS[L - 1] == [(5, 64, 32, 8, 16)]
    band = BANDS[5]["B"]
    assert runs_of(band, ".") == [(14, 21)]
    assert band[13] == band[22] == "%"
    assert cells(14, 21) == (64, 32)
    assert "." in BANDS[5]["C"][14:22], "the way down is under it"
    assert "." in BANDS[5]["A"][14:22], "and the way in is over it"


def test_the_mouth_cycle_is_the_roms():
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _mouth_closed
    c = JaxHero().consts
    got = ""
    for e in range(128):
        closed = int(_mouth_closed(c, jnp.int32(L - 1), jnp.int32(e))[0])
        got += str(8 - 2 * closed)
    assert got == ROM_OPEN * 2


# --- the water tentacles ----------------------------------------------------
def test_rooms_12_and_14_hold_the_two_tentacles():
    slots = [_tentacle_slot(r) for r in TENTACLE_ROOMS]
    for room, slot in zip(TENTACLE_ROOMS, slots):
        assert HL.SPIDERS[L - 1][slot] == (room, 29, 126, 0, 5)
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 8)
        assert (L, slot) not in HL.CREATURE_PATROL
        floor = BANDS[room]["C"]
        assert set(floor[6:30]) == {"~"}, "it swims over liquid"
    assert {k: v for k, v in HL.CREATURE_TRACK.items() if k[0] == L} == {
        (L, s): (29, 121) for s in slots}


def test_the_tentacle_starts_at_the_heros_entry_x_clamped(env):
    """The level descends RIGHT: in by room 11's open right edge he appears
    on the LEFT of room 12 and the tentacle at its left clamp, 29; back up by
    room 13's left edge he appears on the right and it waits at 121."""
    import jax.numpy as jnp
    slot = _tentacle_slot(12)
    c = env.consts
    none = jnp.zeros_like(c.SPIDER_VALID[L - 1])
    s = _state(env, 11, player_x=jnp.int32(c.screen_width - 8 - c.player_width),
               player_y=jnp.int32(70), spider_alive=none)
    _obs, s, *_ = env.step(s, 3)                       # RIGHT, off the edge
    assert int(s.room) == 12 and int(s.tentacle_x[slot]) == 29
    s = _state(env, 13, player_x=jnp.int32(8), player_y=jnp.int32(70),
               spider_alive=none)
    _obs, s, *_ = env.step(s, 4)                       # LEFT, off the edge
    assert int(s.room) == 12 and int(s.tentacle_x[slot]) == 121


def test_the_engine_draws_the_tentacle_where_it_has_followed_him(env):
    import jax.numpy as jnp
    for room in TENTACLE_ROOMS:
        slot = _tentacle_slot(room)
        for x in (29, 77, 121):
            s = _state(env, room, player_x=jnp.int32(128),
                       player_y=jnp.int32(70), room_timer=jnp.int32(36),
                       tentacle_x=jnp.zeros_like(env.consts.SPIDER_VALID[L - 1],
                                                 dtype=jnp.int32).at[slot].set(x))
            frame = np.asarray(env.render(s))
            ys, xs = np.nonzero((frame == np.array(TENTACLE_BLUE)).all(axis=-1))
            assert xs.min() == x and ys.max() == 137, (room, x)


def test_the_tentacle_is_twelve_rows_tall_at_its_tallest(env):
    """Room 14's watch drew every pose two rows low; with the hero in the
    room both tentacles rise to row 126 at their tallest (measured)."""
    import jax.numpy as jnp
    for room in TENTACLE_ROOMS:
        slot = _tentacle_slot(room)
        tops = set()
        for t in range(64):
            s = _state(env, room, player_x=jnp.int32(128), player_y=jnp.int32(70),
                       room_timer=jnp.int32(t),
                       tentacle_x=jnp.zeros_like(env.consts.SPIDER_VALID[L - 1],
                                                 dtype=jnp.int32).at[slot].set(60))
            frame = np.asarray(env.render(s))
            ys, _xs = np.nonzero((frame == np.array(TENTACLE_BLUE)).all(axis=-1))
            if ys.size:
                tops.add(int(ys.min()))
        assert min(tops) == 126, room


# --- dynamite ---------------------------------------------------------------
def test_the_blastable_pillars_are_the_two_cell_ones():
    want = []
    for i, room in enumerate(BANDS):
        for first, last in runs_of(room["B"], "#") + runs_of(room["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            want.append((i, first, last))
    got = {(r, (x - 8) // 4, (x - 8) // 4 + w // 4 - 1)
           for r, x, _y, w, _h, _n in HL.DESTRUCTIBLE[L - 1]}
    assert got == set(want)
    assert len(want) == 5


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    for room, x, y, _w, h, _n in HL.DESTRUCTIBLE[L - 1]:
        first = (x - 8) // 4
        same = (first, first + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if same else (60, 39)), f"room {room} at x {x}"
        assert same == (room == 0)


def test_rooms_11_to_13s_way_on_is_a_magma_pillar_before_the_right_edge():
    """Each of them is left by its open RIGHT edge, behind a two-cell magma
    pillar that dynamite takes; room 14's right edge is open outright."""
    for room, x in ((11, 140), (12, 136), (13, 136)):
        c = (x - 8) // 4
        band = BANDS[room]["B"]
        assert band[c:c + 2] == "%%" and set(band[c + 2:]) == {"."}, f"room {room}"
        assert (room, x, 60, 8, 39, 1) in HL.DESTRUCTIBLE[L - 1]
        assert (room, 1, 1) in HL.SIDE_EXITS[L - 1]
    assert BANDS[14]["B"][20:] == "." * 18


def test_the_shared_wall_table_is_empty():
    common.check_shared_walls(L)


# --- the way down -----------------------------------------------------------
def test_the_side_exits_are_the_open_corridor_edges():
    want = set()
    for i, room in enumerate(BANDS):
        if room["B"][0] == ".":
            want.add((i, -1))
        if room["B"][37] == ".":
            want.add((i, 1))
    assert {(r, s) for r, s, _d in HL.SIDE_EXITS[L - 1]} == want


def test_level_20_descends_right_from_room_10():
    by_room = {}
    for room, side, delta in HL.SIDE_EXITS[L - 1]:
        by_room.setdefault(room, {})[side] = delta
    assert set(by_room) == set(range(10, 16))
    assert by_room[10] == {1: 1}
    for room in range(11, 15):
        assert by_room[room] == {-1: -1, 1: 1}, f"room {room}"
    assert by_room[15] == {-1: -1}, "the last room leads nowhere but back"


def test_every_room_but_the_last_has_a_way_on():
    for i, room in enumerate(BANDS[:-1]):
        down = "." in room["C"]
        side = any(r == i and d == 1 for r, _s, d in HL.SIDE_EXITS[L - 1])
        assert down or side, f"room {i} has no way on"


# --- entities ---------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)


def test_every_entity_in_the_live_capture_is_present():
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    want_lanterns = {(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "lantern"}
    assert lanterns == want_lanterns
    want = {(r, w, x, y) for r, w, x, y in CHARACTERS_MD if w not in ("lantern", "miner")}
    assert shipped() == want
    assert len(HL.SPIDERS[L - 1]) == 29
    (miner,) = [(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "miner"]
    assert HL.MINER_POS[L - 1] == miner


def test_the_census_lanterns_are_where_it_said():
    """The old census had five lanterns for level 20, in rooms
    1, 2, 6, 7 and 8; all five are where it put them."""
    for row in [(1, 79, 35), (2, 131, 35), (6, 131, 35), (7, 115, 35), (8, 131, 35)]:
        assert row in HL.LANTERNS[L - 1]


def test_the_census_still_bats_are_patrolling_bats_seen_frozen():
    """The census parked at x = 0, which dies in these magma rooms and
    freezes them: its still 7x11 floor "bats" in rooms 4, 5, 7 and 8 at
    y 109 are patrolling bats seen at one end of the sweep, and its still
    floor spider at (80, 109) in room 10 is room 10's bat."""
    bats = {(c[0], c[1] - c[3], c[1] + c[3] + 7, c[2]) for _i, c in of_kind(1)}
    for room, x in ((4, 57), (5, 45), (7, 105), (8, 97), (10, 80)):
        assert any(r == room and lo <= x <= hi and y == 103
                   for r, lo, hi, y in bats), f"room {room}"


def test_the_census_room_10_corridor_spider_is_not_on_the_rom():
    """The census put a moving spider at (56, 66) in room 10, where the
    corridor is rock (cells 6-29). Neither the capture nor the AtariAge map
    has it: room 10's creatures are the floor bat and the corridor spider in
    the open right-hand end."""
    assert BANDS[10]["B"][(56 - 8) // 4] == "#"
    assert sorted((c[1], c[2], c[4]) for c in HL.SPIDERS[L - 1] if c[0] == 10) == [
        (87, 103, 1), (136, 70, 0)]


def test_nothing_was_invented_in_room_0():
    assert not any(r == 0 for r, *_ in HL.SPIDERS[L - 1])
    assert not any(r == 0 for r, *_ in HL.LANTERNS[L - 1])


def test_the_lanterns_hang_in_the_ceiling_band_on_row_35():
    """Nine lamps, rooms 1-8 and 10: room 9 has none (the AtariAge map agrees
    lamp for lamp), and rooms 11-15 have none."""
    assert len(HL.LANTERNS[L - 1]) == 9
    assert {r for r, *_ in HL.LANTERNS[L - 1]} == set(range(1, 11)) - {9}
    for room, x, y in HL.LANTERNS[L - 1]:
        assert y == 35, "every lantern in the game hangs on row 35"
        assert BANDS[room]["A"][(x - 8) // 4] == ".", f"room {room}: in air"


def test_the_miner_is_in_the_last_room():
    common.check_miner(L, BANDS)
    assert HL.MINER_POS[L - 1] == (15, 128, 86)


def test_the_fourteen_bats_patrol_22_px_on_46_frames_and_hold_a_pose_4():
    bats = of_kind(1)
    assert [c[0] for _i, c in bats] == [1, 2, 4, 4, 5, 6, 7, 8, 10, 12, 13, 14, 14, 15]
    for slot, (_room, _x, _y, half, _k) in bats:
        assert 2 * half == 22
        assert 2 * HL.CREATURE_PATROL[(L, slot)] == 46
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 16, 4)


def test_the_untethered_spiders_bob_7_px_on_16_frames():
    free = of_kind(4)
    assert [c[0] for _i, c in free] == [2, 7, 8, 11, 13]
    for slot, (_room, _x, _y, half, _k) in free:
        assert half == 0, "it bobs; it does not patrol"
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 16, 8)


def test_the_engine_locks_the_untethered_spiders_pose_to_its_bob(env):
    """Pose 1 (legs gathered) exactly while it goes down, pose 0 while it
    comes back up, over a 16-frame cycle - as on the ROM (level 18's
    measurement; this level runs the same clock)."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((2, 32, 65, 0, 4))
    got = []
    for t in range(32):
        _x, y = _creature_pos(c, jnp.int32(L - 1), jnp.int32(t))
        pose = (t // int(c.SPIDER_HOLD[L - 1][slot])) % 2   # 1 = _ART2
        got.append((int(y[slot]), pose))
    down = [p for (y0, p), (y1, _q) in zip(got, got[1:]) if y1 > y0]
    up = [p for (y0, p), (y1, _q) in zip(got, got[1:]) if y1 < y0]
    assert set(down) == {1} and set(up) == {0}
    assert {y for y, _p in got} == set(range(65, 73))
    assert got[:16] == got[16:], "a 16-frame cycle"


def test_the_hanging_spiders_are_still():
    hanging = of_kind(0)
    assert [(c[0], c[1], c[2]) for _i, c in hanging] == [
        (1, 128, 109), (3, 40, 109), (6, 112, 109), (9, 112, 109), (10, 136, 70),
        (11, 76, 109), (12, 112, 109)]
    for slot, (_room, _x, _y, half, _k) in hanging:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 8)
        assert (L, slot) not in HL.CREATURE_SPRITES, "both poses are drawn"


def test_the_corridor_snake_grows_out_of_the_magma_a_pixel_every_frame():
    """Room 3's snake comes out of the magma wall on its left into the
    two-cell gap at cells 28-29, and stretches a pixel EVERY frame: hold 1,
    a 16-frame cycle."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _snake_length
    snakes = of_kind(3)
    assert [(c[0], c[1], c[2]) for _i, c in snakes] == [(3, 120, 72)]
    for slot, (room, x, y, half, _k) in snakes:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 1), "a pixel every frame"
        band = BANDS[room]["B"]
        assert band[(x - 8) // 4 - 1] == "%" and band[(x - 8) // 4] == "."
    got = [int(_snake_length(jnp.int32(t), jnp.int32(1))) for t in range(32)]
    assert got[:16] == got[16:]
    assert any(got[k:16] + got[:k] == ROM_SNAKE for k in range(16)), \
        "the ROM's 16-frame shape, at some phase"


def test_exactly_the_bats_and_the_untethered_spiders_bob_or_patrol():
    movers = {i for i, c in enumerate(HL.SPIDERS[L - 1])
              if c[3] or HL.CREATURE_MOTION[(L, i)][0]}
    assert movers == {i for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] in (1, 4)}
    assert len(movers) == 19


def test_the_engine_draws_the_bats_on_the_rom_clock(env):
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((1, 63, 64, 11, 1))
    xs, ys = [], []
    for t in range(0, 92):
        x, y = _creature_pos(c, jnp.int32(L - 1), jnp.int32(t))
        xs.append(int(x[slot])); ys.append(int(y[slot]))
    assert max(xs) - min(xs) == 22 and max(ys) - min(ys) == 7
    assert xs[:46] == xs[46:92], "the sweep is a 46-frame cycle"
    assert ys[:16] == ys[16:32] == ys[32:48], "the bob is a 16-frame cycle"


def test_the_rows_are_the_ones_the_rom_draws_with_the_hero_in_the_room():
    """Re-read on the ROM with the hero parked in the room: the capture had
    these 1-2 rows low. Room 3's spider was read past the hero from the 8-px
    gap beside it, room 5's bat in the first 16 frames of the mouth."""
    rows = sorted((r, x, y) for r, x, y, _h, k in HL.SPIDERS[L - 1] if k != 5)
    for row in [(3, 40, 109), (3, 120, 72), (4, 67, 64), (4, 67, 103), (5, 55, 103),
                (6, 27, 64), (6, 112, 109), (8, 107, 103), (9, 112, 109),
                (14, 55, 64), (14, 115, 103)]:
        assert row in rows
    assert {y for r, x, y, h, k in HL.SPIDERS[L - 1] if k == 1} == {64, 103}
    assert {y for r, x, y, h, k in HL.SPIDERS[L - 1] if k == 0 and y > 99} == {109}


# --- rendering --------------------------------------------------------------
def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black."""
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    state = state.replace(level=jnp.int32(L - 1), room=jnp.int32(11))
    frame = np.asarray(env.render(state))
    assert frame[189:210].max() == 0, "something is drawn where the logo was"


def test_room_0_paints_the_levels_own_grey():
    _palette, rooms = common.level_data(L)
    for role in ("dark", "mid", "light"):
        r, g, b = common.rgb(HL.SHADES[L][role])
        assert (rooms[0] == np.array([r, g, b])).all(axis=-1).any(), (
            f"room 0 never paints its {role}")


# --- play -------------------------------------------------------------------
def test_the_floor_spider_can_be_shot_from_the_raft(env):
    import jax.numpy as jnp
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((11, 76, 109, 0, 0))
    s = _state(env, 11, raft_x=jnp.int32(50), raft_dir=jnp.int32(1),
               player_x=jnp.int32(51), player_y=jnp.int32(c.raft_y - c.player_height),
               facing=jnp.int32(1))
    score = int(s.score)
    for _ in range(12):
        _obs, s, *_ = env.step(s, 1)                     # FIRE
    assert not bool(s.spider_alive[slot])
    assert int(s.score) - score == c.creature_points


def test_the_laser_takes_a_hanging_spider_through_its_thread(env):
    """Room 10's corridor spider (rows 70-81, thread from 70), shot from the
    right-hand end of the corridor facing left: a bolt on its thread kills
    it, one above it does not."""
    import jax.numpy as jnp
    c = env.consts
    slot = HL.SPIDERS[L - 1].index((10, 136, 70, 0, 0))
    for bolt_row, dies in ((72, True), (68, False)):
        y = bolt_row - c.laser_eye_offset
        s = _state(env, 10, player_x=jnp.int32(150), player_y=jnp.int32(y),
                   facing=jnp.int32(-1))
        for _ in range(12):
            # pin the rotor in its hover band too, or the ROM hero's thrust
            # drops him a row or two inside the step and the bolt with him
            s = s.replace(player_y=jnp.int32(y), player_vy=jnp.float32(0),
                          thrust_timer=jnp.int32(c.thrust_kick))
            _obs, s, *_ = env.step(s, 1)                 # FIRE
        assert bool(s.spider_alive[slot]) != dies, f"bolt on row {bolt_row}"


def test_a_death_on_the_raft_leaves_it_and_brings_him_back_onto_it(env):
    """Carried from x 28 rightwards into room 11's floor spider, he dies; the
    raft waits where it stopped, he comes back in his own column under the
    magma wall, lands on it and it carries him on to the right."""
    import jax.numpy as jnp
    c = env.consts
    s = _state(env, 11, raft_x=jnp.int32(28), raft_dir=jnp.int32(1),
               player_x=jnp.int32(29), player_y=jnp.int32(c.raft_y - c.player_height))
    lives = int(s.lives)
    died_at = landed_at = None
    for f in range(200):
        prev = s
        # a new life hovers where it comes back until the first input (the
        # ROM); one tap of DOWN - a NOOP in the air - starts his rotor
        first = died_at is not None and not bool(s.has_moved)
        _obs, s, *_ = env.step(s, 5 if first else 0)
        if died_at is None and int(s.lives) < lives:
            died_at = f
            assert int(s.player_y) == c.respawn_low_y, "under the magma wall"
            assert abs(int(s.player_x) - int(prev.player_x)) <= 1, "in his own column"
            raft_at_death = int(s.raft_x)
        elif died_at is not None and int(s.player_y) < c.raft_y - c.player_height:
            assert int(s.raft_x) == raft_at_death, "the raft waits where it stopped"
        elif died_at is not None:
            # back on it: watch a few frames of the ride, not its whole run
            # to the far end, where it turns round
            landed_at = f if landed_at is None else landed_at
            if f >= landed_at + 10:
                break
    assert died_at is not None
    assert int(s.player_y) == c.raft_y - c.player_height, "back on the raft"
    assert int(s.raft_x) > raft_at_death, "and it carries him on"


@pytest.mark.parametrize("room, x, y, low", [(10, 136, 72, False), (1, 128, 104, True),
                                             (1, 63, 64, False), (2, 107, 104, True)])
def test_he_comes_back_at_the_height_of_the_band_he_died_in(env, room, x, y, low):
    """Pinned where a creature kills him, the hero comes back in his own
    column at corridor height (y 62) when the creature is in the corridor
    band and at y 101 when it is in the floor band."""
    import jax.numpy as jnp
    c = env.consts
    s = _state(env, room, player_x=jnp.int32(x), player_y=jnp.int32(y),
               room_timer=jnp.int32(0), step_counter=jnp.int32(0))
    lives = int(s.lives)
    for _ in range(200):
        s = s.replace(player_x=jnp.int32(x), player_y=jnp.int32(y),
                      player_vy=jnp.float32(0))
        _obs, s, *_ = env.step(s, 0)
        if int(s.lives) < lives:
            break
    assert int(s.lives) == lives - 1, "a creature killed him"
    assert int(s.player_y) == (c.respawn_low_y if low else c.respawn_y)
    assert abs(int(s.player_x) - x) <= 4, "in his own column"


def test_he_can_fly_off_the_raft_and_hover_under_the_magma(env):
    import jax.numpy as jnp
    c = env.consts
    s = _state(env, 11, raft_x=jnp.int32(80), raft_dir=jnp.int32(1),
               player_x=jnp.int32(81), player_y=jnp.int32(c.raft_y - c.player_height),
               spider_alive=jnp.zeros_like(c.SPIDER_VALID[L - 1]),
               # UP already held long enough to spin the rotor up: from rest
               # the ROM hero needs ~48 frames to lift off, and the raft would
               # carry him out from under the magma meanwhile
               thrust_timer=jnp.int32(c.thrust_up_slow - 1))
    lives = int(s.lives)
    ys = []
    for _ in range(90):
        _obs, s, *_ = env.step(s, 2)                     # UP
        ys.append(int(s.player_y))
    assert int(s.lives) == lives, "the magma over him does not burn"
    assert min(ys) < c.raft_y - c.player_height, "he lifted off the raft"
    assert ys[-1] == ys[-10] and 60 + 39 - 2 <= ys[-1] <= 99, "and hovers under the wall"
    assert int(s.room) == 11
