"""Level 10, against the corrected ROM reference.

The block in hero_levels.py is generated by a level builder that walks
the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), then play the level.

Three things came out of level 10:

  * THE WALK REACHES ALL SIXTEEN ROOMS. The old reference had it at 11. Room 10
    is left through its open LEFT edge, and so is every room after it: level
    10 descends LEFT from room 10 to room 15, the mirror of level 9.
  * ITS CREATURES RUN AT TWICE LEVEL 9'S SPEED. Every bat sweeps the same
    22 px, but on a 92-frame cycle instead of 184, and every bobbing creature
    bobs the same 7 px on 32 frames instead of 64. Measured straight off the
    ROM on 2026-09-24 (level 10 room 8's bat against level 9 room 5's, the
    hero pinned above the picture, with and without the level register
    pinned: 92/32 against 184/64 both ways). The pose holds do NOT change -
    a bat still holds each wing pose 4 frames, a spider each pose 8.
  * The census is the lethal-park kind for rooms 0-10 (every one
    a magma room): it calls four moving creatures still bats, and has no row
    for seventeen of the twenty-four creatures.

The shape of the level, room by room:

    rooms 0-10  GREEN, and magma in every one of them.
    room 10     the corridor is open at the left end, the floor is liquid
                from cell 6 to cell 29, and the way on is the open LEFT edge.
    room 11     sealed ceiling, liquid floor, an open corridor, two bats.
    room 12     a two-cell pillar at cells 17-18 standing on the rock between
                two stretches of water: a stick. A snake grows out of that
                rock.
    room 13     a four-cell MAGMA wall at cells 16-19 over the water - flown
                UNDER, through the air above the liquid (level_10 frames
                173-185: the wall is intact throughout and the hero is drawn
                at y ~127 below it on frame 183).
    room 14     another two-cell pillar on rock at 17-18: a second stick.
    room 15     the miner's room: solid floor, solid ceiling, a bat and the
                miner at x 25.
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

L = 10

# What the ROM draws, cell for cell, in descent order, verified against
# the reference before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "%%...........%%...................%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%.......................%%.......%%%%",
     "C": "####..########################..######"},
    {"A": "####..########################..######",
     "B": "%%...........%%...................%%%%",
     "C": "#################..###################"},
    {"A": "#################..###################",
     "B": "%%.......................%%.......%%%%",
     "C": "#####..##########..##########..#######"},
    {"A": "#####..##########..##########..#######",
     "B": "%%%%%%%%....%%%%%%%%%%%%%%%%....%%%%%%",
     "C": "#####..######################..#######"},
    {"A": "#####..######################..#######",
     "B": "%%.......%%%%%%%%%%%%%%%%%%.......%%%%",
     "C": "#######...################...#########"},
    {"A": "#######...################...#########",
     "B": "%%...................%%...........%%%%",
     "C": "###....#########....#########....#####"},
    {"A": "###....#########....#########....#####",
     "B": "%%%%..%%%%%%%%%%%..%%%%%%%%%%%..%%%%%%",
     "C": "##................................####"},
    {"A": "##................................####",
     "B": "%%%%%%%%%%%%%%%%....%%%%%%%%%%%%%%%%%%",
     "C": "##................................####"},
    {"A": "##................................####",
     "B": "%%%%%%%%%%%%%%........%%%%%%%%%%%%%%%%",
     "C": "####............................######"},
    {"A": "####............................######",
     "B": "..........%%%%%%%%%%%%%%%%..........%%",
     "C": "######~~~~~~~~~~~~~~~~~~~~~~~~########"},
    {"A": "######################################",
     "B": "......................................",
     "C": "#####~~~~~~~~~~~~~~~~~~~~~~~~~~#######"},
    {"A": "######################################",
     "B": ".................##...................",
     "C": "####~~~~~~~~~~~~####~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": "................%%%%..................",
     "C": "####~~~~~~~~~~~~~~~~~~~~~~~~~~~~######"},
    {"A": "######################################",
     "B": ".................##...................",
     "C": "########~~~~~~~~####~~~~~~~~##########"},
    {"A": "######################################",
     "B": "##....................................",
     "C": "######################################"},
]

# The live-hero ROM capture (the data hero_levels.py ships), as
# (room, what, x, y) with x the LEFT edge of the drawn box - for a bat, of
# its sweep. Every row. Rows re-read with the hero IN the room on 2026-09-30:
# the above park had drawn room 2's bat a row low, at 65.
CHARACTERS_MD = [
    (1, "lantern", 83, 35), (1, "spider_free", 24, 104), (1, "bat", 44, 64),
    (2, "lantern", 131, 35), (2, "bat", 104, 64),
    (3, "lantern", 79, 35), (3, "spider_free", 28, 104), (3, "bat", 44, 64),
    (4, "lantern", 79, 35), (4, "snake", 120, 72),
    (5, "lantern", 31, 35), (5, "spider", 40, 109), (5, "snake", 116, 72),
    (6, "lantern", 43, 35), (6, "bat", 64, 64), (6, "spider_free", 128, 104),
    (7, "lantern", 135, 35), (7, "spider", 24, 71), (7, "bat", 44, 104),
    (8, "lantern", 139, 35), (8, "bat", 44, 104),
    (9, "lantern", 139, 35), (9, "bat", 44, 104), (9, "spider_free", 88, 66),
    (10, "lantern", 131, 35), (10, "spider_free", 16, 65), (10, "bat", 36, 103),
    (11, "bat", 44, 64), (11, "bat", 60, 103),
    (12, "spider_free", 60, 65), (12, "snake", 88, 111),
    (14, "bat", 40, 103), (14, "bat", 44, 64),
    (15, "bat", 61, 64), (15, "miner", 25, 86),
]

# The CENSUS table carried for this level before 2026-09-24,
# kept as the record of what the lethal reading park did to it. Every row of
# it is still honoured: the same room and x, with the kind and the row the
# ROM draws with a live hero (SHIPPED_AS).
OLD_CENSUS = [
    (1, "lantern", 83, 35),
    (1, "bat", 24, 111),
    (2, "lantern", 131, 35),
    (3, "lantern", 79, 35),
    (3, "bat", 28, 111),
    (4, "lantern", 79, 35),
    (5, "lantern", 31, 35),
    (5, "spider", 40, 109),
    (6, "lantern", 43, 35),
    (6, "bat", 128, 111),
    (7, "lantern", 135, 35),
    (7, "bat", 44, 110),
    (8, "bat", 44, 110),
    (9, "bat", 44, 110),
]

# The census rows the ROM does not draw that way with a LIVE hero, and what
# is shipped instead. Every x is the census's; only the kind or the row moves.
#
#   rooms 1, 3, 6  the census's test for a bat is "no thread"; this creature
#                  has none because it is the UNTETHERED spider (kind 4):
#                  warm ramp, no grey. It bobs 7 px, so its box starts at 104
#                  and the census's frozen 111 is inside it.
#   rooms 7, 8, 9  a bat that PATROLS 22 px and bobs 7; the box starts at 104.
SHIPPED_AS = {
    (1, "bat", 24, 111): ("spider_free", 24, 104),
    (3, "bat", 28, 111): ("spider_free", 28, 104),
    (6, "bat", 128, 111): ("spider_free", 128, 104),
    (7, "bat", 44, 110): ("bat", 44, 104),
    (8, "bat", 44, 110): ("bat", 44, 104),
    (9, "bat", 44, 110): ("bat", 44, 104),
}

# What the ROM draws that the old census has no row for, as (what, x, y).
# Rooms 1-10: hidden from it by its lethal park. Rooms 11-15: never reached.
NOT_IN_CENSUS = {
    1: [("bat", 44, 64)],
    2: [("bat", 104, 64)],
    3: [("bat", 44, 64)],
    4: [("snake", 120, 72)],
    5: [("snake", 116, 72)],
    6: [("bat", 64, 64)],
    7: [("spider", 24, 71)],
    8: [("lantern", 139, 35)],
    9: [("lantern", 139, 35), ("spider_free", 88, 66)],
    10: [("lantern", 131, 35), ("spider_free", 16, 65), ("bat", 36, 103)],
    11: [("bat", 44, 64), ("bat", 60, 103)],
    12: [("spider_free", 60, 65), ("snake", 88, 111)],
    14: [("bat", 40, 103), ("bat", 44, 64)],
    15: [("bat", 61, 64), ("miner", 25, 86)],
}

KIND_NAME = {0: "spider", 1: "bat", 3: "snake", 4: "spider_free"}


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


def shipped():
    """{(room, what, left x, top y)} for every creature SPIDERS carries."""
    return {(r, KIND_NAME[k], x - half, y)
            for r, x, y, half, k in HL.SPIDERS[L - 1]}


# --- geometry ---------------------------------------------------------------
def test_level_10_is_sixteen_green_rooms():
    common.check_shape(L, "green", rooms=16)
    assert len(HL.BG_RLE_L10) == 16


def test_all_sixteen_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_the_level_is_complete_and_nothing_is_missing():
    """The old reference listed level 10 as 11 of 16 rooms. The other five were
    reached on 2026-09-24 by walking off the LEFT edge of rooms 10-14."""
    assert len(BANDS) == 16
    assert len({(b["A"], b["B"], b["C"]) for b in BANDS}) == 16, \
        "no ROOM is a copy of another"


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_down_to_room_10():
    """Room N's ceiling is drawn identically to room N-1's floor while the
    level goes down through holes. Rooms 11-15 are entered SIDEWAYS, under a
    ceiling that is solid across the whole screen."""
    for i in range(1, 11):
        assert BANDS[i]["A"] == BANDS[i - 1]["C"].replace("~", "#"), \
            f"chain breaks between rooms {i - 1} and {i}"
    for i in range(11, 16):
        assert BANDS[i]["A"] == "#" * 38


def test_no_cell_was_left_uncalled():
    for i, room in enumerate(BANDS):
        for band, s in room.items():
            assert "?" not in s, f"room {i} band {band} has an uncalled cell"
            assert set(s) <= set("#%.~"), f"room {i} band {band} has a stray value"


# --- the water --------------------------------------------------------------
def test_the_five_water_rooms_are_the_only_liquid():
    with_liquid = {i for i, r in enumerate(BANDS) if "~" in r["C"]}
    assert with_liquid == {10, 11, 12, 13, 14}
    assert BANDS[15]["C"] == "#" * 38


def test_the_water_rooms_have_no_hole_to_fall_through():
    for room in range(10, 15):
        assert "." not in BANDS[room]["C"], f"room {room} floor has a real hole"


def test_a_liquid_cell_is_solid_only_on_the_rows_it_is_drawn_on():
    y0, y1 = common.LIQUID_ROWS
    for room in range(10, 15):
        liquid_x = {8 + 4 * i for i, c in enumerate(BANDS[room]["C"]) if c == "~"}
        for x, y, w, h in HL.WALL_RECTS_L10[room]:
            if x in liquid_x and y >= 99:
                assert (y, h) == (y0, y1 - y0 + 1), (
                    f"room {room}: the liquid rect at x {x} is {h} px tall "
                    f"from row {y}; it must be rows {y0}-{y1}")


def test_the_deadly_rects_are_the_water_line():
    """DEADLY is the lethal surface: level 10's liquid is #a8308f
    in a green cave. Room 15 carries a three-row strip under its solid floor,
    as levels 8 and 9 do - it is drawn, and nothing can reach it."""
    rooms = {r for r, _x, _y, _w, _h in HL.DEADLY[L - 1]}
    assert rooms == {10, 11, 12, 13, 14, 15}
    for room, x, y, w, h in HL.DEADLY[L - 1]:
        if room != 15:
            assert (y, h) == (136, 6), f"room {room} water is not the 136-141 line"
    assert (15, 8, 139, 152, 3) in HL.DEADLY[L - 1]
    assert common.rgb("#a8308f") in HL.PALETTE_L10


def test_room_13s_magma_wall_stands_over_water_and_is_flown_under():
    """Four cells of magma are twice what a stick takes, and the ceiling is
    solid - but every cell under the wall is '~', AIR from row 99 to 135."""
    (first, last), = runs_of(BANDS[13]["B"], "%")
    assert (first, last) == (16, 19)
    assert set(BANDS[13]["C"][first:last + 1]) == {"~"}
    x, _w = cells(first, last)
    assert not any(r == 13 for r, *_ in HL.DESTRUCTIBLE[L - 1])


# --- magma ------------------------------------------------------------------
def test_magma_is_in_rooms_0_to_10_and_room_13():
    """Magma is a property of the ROOM: the corridor colour register is either
    the level hue or magma red. In a magma room every solid corridor cell is
    magma - room 13's single wall included."""
    with_magma = {i for i, r in enumerate(BANDS) if "%" in "".join(r.values())}
    assert with_magma == set(range(11)) | {13}
    for room in with_magma:
        assert "#" not in BANDS[room]["B"], \
            f"room {room}: in a magma room every solid corridor cell is magma"


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


def test_magma_never_leaves_the_corridor_band():
    for _room, _x, y, _w, h in HL.MAGMA[L - 1]:
        assert (y, h) == (60, 39), "magma is a corridor register, not a band"


# --- dynamite ---------------------------------------------------------------
def test_the_blastable_pillars_are_the_two_cell_ones():
    """Only a run of exactly two cells breaks, never one that reaches the side
    of the screen - magma the same as rock."""
    want = []
    for i, room in enumerate(BANDS):
        for first, last in runs_of(room["B"], "#") + runs_of(room["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            want.append((i, first, last))
    got = {(r, (x - 8) // 4, (x - 8) // 4 + w // 4 - 1)
           for r, x, _y, w, _h, _n in HL.DESTRUCTIBLE[L - 1]}
    assert got == set(want)
    assert len(want) == 7


def test_rooms_12_and_14_each_take_a_stick():
    """A two-cell pillar with solid rock ABOVE it (the ceiling) and BELOW it
    (the rock between the two waters), so it can be neither flown over nor
    under, between the hero - who arrives at the right edge - and the left
    edge that leads on."""
    for room in (12, 14):
        assert BANDS[room]["B"][17:19] == "##"
        assert BANDS[room]["A"] == "#" * 38, "nothing to fly over"
        assert set(BANDS[room]["C"][17:19]) == {"#"}, "nothing to fly under"
        x, w = cells(17, 18)
        assert (room, x, 60, w, 39, 1) in HL.DESTRUCTIBLE[L - 1]


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    for room, x, y, _w, h, _n in HL.DESTRUCTIBLE[L - 1]:
        first = (x - 8) // 4
        same = (first, first + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if same else (60, 39)), f"room {room} at x {x}"
        assert same == (room == 0)


def test_the_shared_wall_table_is_empty():
    common.check_shared_walls(L)


def test_nothing_flares():
    """FLARES is not derivable from a still capture. The rows this level
    carried were authored on the superseded reference."""
    assert HL.FLARES[L - 1] == []


# --- the way down -----------------------------------------------------------
def test_the_side_exits_are_the_open_corridor_edges():
    want = set()
    for i, room in enumerate(BANDS):
        if room["B"][0] == ".":
            want.add((i, -1))
        if room["B"][37] == ".":
            want.add((i, 1))
    assert {(r, s) for r, s, _d in HL.SIDE_EXITS[L - 1]} == want


def test_level_10_descends_through_left_edges():
    """A side exit's direction is DATA. Level 9 went RIGHT from room 10;
    level 10 goes LEFT, and every right edge from room 11 on leads back up."""
    by_room = {}
    for room, side, delta in HL.SIDE_EXITS[L - 1]:
        by_room.setdefault(room, {})[side] = delta
    assert by_room[10] == {-1: 1}
    for room in range(11, 15):
        assert by_room[room] == {-1: 1, 1: -1}, f"room {room}"
    assert by_room[15] == {1: -1}, "the last room leads nowhere but back"


def test_every_room_but_the_last_has_a_way_on():
    for i, room in enumerate(BANDS[:-1]):
        down = "." in room["C"]
        side = any(r == i and d == 1 for r, _s, d in HL.SIDE_EXITS[L - 1])
        assert down or side, f"room {i} has no way on"


# --- entities ---------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)


def test_every_entity_in_the_live_capture_is_present():
    """Every lantern, every creature at its kind, x and y, and the miner -
    and not one creature more."""
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    want_lanterns = {(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "lantern"}
    assert lanterns == want_lanterns
    want = {(r, w, x, y) for r, w, x, y in CHARACTERS_MD if w not in ("lantern", "miner")}
    assert shipped() == want
    (miner,) = [(r, x, y) for r, w, x, y in CHARACTERS_MD if w == "miner"]
    assert HL.MINER_POS[L - 1] == miner


def test_every_old_census_row_is_still_honoured():
    """The superseded census, row for row: each is shipped at its own x, with
    the kind and row the live ROM draws (SHIPPED_AS) - and for the movers the
    census's row is one frame of the bob, inside the shipped box."""
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    got = shipped()
    for row in OLD_CENSUS:
        room, what, x, y = row
        if what == "lantern":
            assert (room, x, y) in lanterns
            continue
        what, sx, sy = SHIPPED_AS.get(row, (what, x, y))
        assert sx == x
        assert (room, what, sx, sy) in got, f"{what} {room} {sx},{sy} missing"
        if what in ("bat", "spider_free"):
            assert sy <= y <= sy + 7 + 11


def test_the_entities_the_old_census_never_saw():
    got = shipped()
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    n = sum(1 for _r, w, _x, _y in OLD_CENSUS if w != "lantern")
    for room, entities in NOT_IN_CENSUS.items():
        for what, x, y in entities:
            if what == "miner":
                assert HL.MINER_POS[L - 1] == (room, x, y)
            elif what == "lantern":
                assert (room, x, y) in lanterns
            else:
                assert (room, what, x, y) in got, f"room {room} {what} missing"
                n += 1
    assert n == len(HL.SPIDERS[L - 1]) == 24, "a creature is in neither table"


def test_nothing_was_invented_in_room_0_or_room_13():
    """Neither the census nor the ROM draws a creature in rooms 0 and 13."""
    assert not any(r in (0, 13) for r, *_ in HL.SPIDERS[L - 1])
    assert not any(r == 0 for r, *_ in HL.LANTERNS[L - 1])


def test_the_lanterns_hang_in_the_ceiling_band_on_row_35():
    assert len(HL.LANTERNS[L - 1]) == 10
    assert {r for r, *_ in HL.LANTERNS[L - 1]} == set(range(1, 11))
    for _room, _x, y in HL.LANTERNS[L - 1]:
        assert y == 35, "every lantern in the game hangs on row 35"


def test_the_miner_is_in_the_last_room():
    """At x 25 - two pixels right of the 23 the old RAM-teleport scan gave,
    the same correction as level 8's."""
    common.check_miner(L, BANDS)
    assert HL.MINER_POS[L - 1] == (15, 25, 86)


def test_the_snakes_are_anchored_in_the_wall_on_their_left():
    """Two grow out of a magma wall's right face in the corridor, one out of
    the rock between room 12's two waters. On this level they stretch a
    pixel every 2 frames (a 32-frame cycle), twice as fast as level 4's and
    level 9's 4 - measured on the ROM; the 4 shipped before was the old
    default."""
    snakes = [(r, x, y) for r, x, y, _h, k in HL.SPIDERS[L - 1] if k == 3]
    assert snakes == [(4, 120, 72), (5, 116, 72), (12, 88, 111)]
    for room, x, y in snakes:
        band = "B" if y < 99 else "C"
        assert BANDS[room][band][(x - 8) // 4 - 1] in "#%", f"room {room}"
        assert BANDS[room][band][(x - 8) // 4] in ".~", f"room {room}"
        slot = HL.SPIDERS[L - 1].index((room, x, y, 0, 3))
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 2)
        assert (L, slot) not in HL.CREATURE_PATROL


def test_the_thirteen_bats_patrol_22_px_on_92_frames_and_hold_a_pose_4():
    """Twice level 9's speed, the same distances and the same pose hold."""
    bats = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 1]
    assert [c[0] for _i, c in bats] == [1, 2, 3, 6, 7, 8, 9, 10, 11, 11, 14, 14, 15]
    for slot, (_room, _x, _y, half, _k) in bats:
        assert 2 * half == 22
        assert 2 * HL.CREATURE_PATROL[(L, slot)] == 92
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 32, 4)


def test_the_untethered_spiders_bob_7_px_on_32_frames():
    free = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 4]
    assert [c[0] for _i, c in free] == [1, 3, 6, 9, 10, 12]
    for slot, (_room, _x, _y, half, _k) in free:
        assert half == 0, "it bobs; it does not patrol"
        travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
        assert (travel, 2 * half_bob, hold) == (7, 32, 8)


def test_the_hanging_spiders_are_still():
    """Whether a creature moves is a property of the room. Level 10's two
    hanging spiders - one in the floor band, one in the corridor - are still:
    no patrol, no bob, and two poses on an 8-frame hold."""
    hanging = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 0]
    assert [(c[0], c[1], c[2]) for _i, c in hanging] == [(5, 40, 109), (7, 24, 71)]
    for slot, (_room, _x, _y, half, _k) in hanging:
        assert half == 0
        assert HL.CREATURE_MOTION[(L, slot)] == (0, 0, 8)
        assert (L, slot) not in HL.CREATURE_SPRITES, "both poses are drawn"


def test_exactly_the_bats_and_the_untethered_spiders_move():
    movers = {i for i, c in enumerate(HL.SPIDERS[L - 1])
              if c[3] or HL.CREATURE_MOTION[(L, i)][0]}
    assert movers == {i for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] in (1, 4)}
    assert len(movers) == 19


def test_the_engine_draws_the_bats_on_the_rom_clock(env):
    """Not just the tables: the engine's creature positions over 400 frames
    sweep 23 columns (22 px of travel) and repeat every 92 frames, and the
    bob repeats every 32 - level 10 room 8's bat, the one timed on the ROM."""
    import jax.numpy as jnp
    from jaxatari.games.jax_hero import _creature_pos
    c = env.consts
    slot = next(i for i, s in enumerate(HL.SPIDERS[L - 1]) if s[0] == 8 and s[4] == 1)
    xs, ys = [], []
    for t in range(0, 184):
        x, y = _creature_pos(c, jnp.int32(L - 1), jnp.int32(t))
        xs.append(int(x[slot])); ys.append(int(y[slot]))
    assert max(xs) - min(xs) == 22 and max(ys) - min(ys) == 7
    assert xs[:92] == xs[92:184], "the sweep is a 92-frame cycle"
    assert ys[:32] == ys[32:64] == ys[64:96], "the bob is a 32-frame cycle"


# --- rendering --------------------------------------------------------------
def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black."""
    import jax
    import jax.numpy as jnp
    _obs, state = env.reset(jax.random.PRNGKey(0))
    state = state.replace(level=jnp.int32(L - 1), room=jnp.int32(10))
    frame = np.asarray(env.render(state))
    assert frame[189:210].max() == 0, "something is drawn where the logo was"


def test_room_0_paints_the_levels_own_green():
    """The ROM leaves level 1's brown palette in place on room 0 until the
    first transition; the capture recolours it onto level 10's green ramp,
    so room 0 must paint the green shades and none of the brown."""
    _palette, rooms = common.level_data(L)
    for role in ("dark", "mid", "light"):
        r, g, b = common.rgb(HL.SHADES[L][role])
        assert (rooms[0] == np.array([r, g, b])).all(axis=-1).any(), (
            f"room 0 never paints its {role}")
        r, g, b = common.rgb(HL.SHADES[1][role])
        assert not (rooms[0] == np.array([r, g, b])).all(axis=-1).any(), (
            f"room 0 still paints level 1's brown {role}")
