"""Level 8, against the corrected ROM reference.

The block in hero_levels.py is generated by a level builder that walks
the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), then play the level.

Level 8 is the first level that needed DYNAMITE to be captured at all, and
three things came out of it:

  * THE WALK NOW REACHES ALL FOURTEEN ROOMS. The old reference had it at 11.
    Room 10 is left through its open LEFT edge, but only from near that edge:
    dropped mid-corridor the hero is over the water and drowns, and holding
    the rotor flies him out of the TOP of the screen and back up to room 9.
  * A ROOM CAN OPEN ON BOTH SIDES, AND ONE SIDE LEADS BACK UP. Room 11's
    cell 37 returns to room 10. The walker used to accept that as "an exit"
    and stop, three rooms short, so a way out now only counts if it lands
    further DOWN the chain.
  * ROOM 11 IS SEALED BEHIND A PILLAR. Its corridor is open at cell 0, but
    cells 2-3 are a two-cell pillar under a ceiling that is solid across the
    whole room, so the hero can neither walk past it nor fly over it. Every
    action from every drop point failed to leave in 1500 frames. A stick
    takes it - stock 6 -> 5 - and LEFT then reaches room 12 in 17 frames.
    Rooms 12 and 13 exist only on the far side of that blast.

The shape of the level, room by room:

    rooms 0-10  GREY, and magma in every one of them - level 8 is the first
                level whose corridor register is magma red all the way down.
    room 10     the water room: the corridor is open end to end but for two
                magma cells at the right, and the floor is liquid from cell 8
                to cell 27. The way on is the open LEFT edge.
    room 11     sealed ceiling, liquid floor, a patrolling BAT over the water
                and a SNAKE out of the middle slab's right face. Blast the
                cells 2-3 pillar to leave.
    room 12     liquid floor in two stretches, a hanging spider and a second
                snake. Its left edge leads on, and needs no stick.
    room 13     the miner's room: solid floor, solid ceiling, one hanging
                creature and the miner at x 25.

Rooms 0 and 10-13 have NO row in the census - it was taken when
the walker still stopped at room 10 - so their entities come from the capture
and are checked against it, not against a table that never saw them.
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

NOOP, FIRE, UP, RIGHT, LEFT, DOWN = 0, 1, 2, 3, 4, 5
L = 8

# What the ROM draws, cell for cell, in descent order, verified against
# the reference before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "%%%..........%%..................%%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%................................%%%%",
     "C": "##########................############"},
    {"A": "##########................############",
     "B": "%%%%%%%%%%%%%%%......%%%%%%%%%%%%%%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%...........%%...................%%%%",
     "C": "##########..############..############"},
    {"A": "##########..############..############",
     "B": "%%%%%%%......%%%%%%%%%%......%%%%%%%%%",
     "C": "######.....##############.....########"},
    {"A": "######.....##############.....########",
     "B": "%%%%%%%......%%..............%%%%%%%%%",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "%%...........%%...................%%%%",
     "C": "####..########################..######"},
    {"A": "####..########################..######",
     "B": "%%............%%%%%%%%.....%%.....%%%%",
     "C": "##########..############..############"},
    {"A": "##########..############..############",
     "B": "%%%%%...........%%%%...........%%%%%%%",
     "C": "##..........############..........####"},
    {"A": "##..........############..........####",
     "B": "%%%%%%....%%%%%%%%%%%%%%%%....%%%%%%%%",
     "C": "####..........########..........######"},
    {"A": "####..........########..........######",
     "B": "....................................%%",
     "C": "########~~~~~~~~~~~~~~~~~~~~##########"},
    {"A": "######################################",
     "B": "..##........############..............",
     "C": "#########~~~~~~~~~~~~~~~~~~###########"},
    {"A": "######################################",
     "B": ".................##...................",
     "C": "######~~~~~~~~~~####~~~~~~~~~~########"},
    {"A": "######################################",
     "B": "##....................................",
     "C": "######################################"},
]

# The census, level 8 (11 of 14 rooms scanned, 12 entities), as
# (room, what, x, y). Rooms 0 and 10 have NO row: no entity was measured in
# them, and none is invented here. Rooms 11-13 were reached for the first
# time in this session and have never been censused - see
# test_the_deep_rooms_were_never_censused.
CHARACTERS_MD = [
    (1, "lantern", 83, 35),
    (1, "spider", 80, 109),
    (2, "lantern", 107, 35),
    (2, "spider", 80, 109),
    (3, "lantern", 83, 35),
    (3, "spider", 104, 109),
    (4, "lantern", 107, 35),
    (5, "lantern", 123, 35),
    (6, "lantern", 83, 35),
    (7, "lantern", 27, 35),
    (8, "lantern", 107, 35),
    (9, "lantern", 51, 35),
]

# The rooms the census never reached, and what the CAPTURE found in them.
# Recorded here so the numbers are stated somewhere rather than only living
# in the generated tables.
CAPTURED_ONLY = {
    10: [("lantern", 59, 35), ("spider", 76, 70)],
    11: [("bat", 52, 103), ("snake", 104, 72)],
    12: [("spider", 40, 70), ("snake", 88, 111)],
    13: [("spider", 77, 70), ("miner", 25, 86)],
}

KIND_NAME = {0: "spider", 1: "bat", 3: "snake", 4: "spider_free"}


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


def runs_of(band, ch="#"):
    out, start = [], None
    for i, c in enumerate(band + "."):
        if c == ch and start is None:
            start = i
        elif c != ch and start is not None:
            out.append((start, i - 1))
            start = None
    return out


# --- geometry ---------------------------------------------------------------
def test_level_8_is_fourteen_grey_rooms():
    common.check_shape(L, "grey", rooms=14)
    assert len(HL.BG_RLE_L8) == 14


def test_all_fourteen_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_the_level_is_complete_and_nothing_is_missing():
    """The old reference listed level 8 as 11 of 14 rooms. The other three were
    reached on 2026-09-23: room 11 by walking off room 10's LEFT edge from
    near that edge, and rooms 12 and 13 by blowing the pillar that seals
    room 11."""
    assert len(BANDS) == 14
    # Rooms 3 and 6 draw the IDENTICAL corridor, and that is not a capture
    # that copied a band: the ROM stores each distinct pattern once and draws
    # it in both rooms. They are still two separate walls - see
    # test_the_shared_wall_table_is_empty.
    assert BANDS[3]["B"] == BANDS[6]["B"]
    assert len({(b["A"], b["B"], b["C"]) for b in BANDS}) == 14,         "no ROOM is a copy of another"


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_across_all_fourteen_rooms():
    """Room N's ceiling is drawn identically to room N-1's floor. A '~' cell
    is liquid on the floor it belongs to and plain rock seen from below, so
    the two are compared with '~' folded onto '#'."""
    for i in range(1, len(BANDS)):
        below = BANDS[i]["A"].replace("~", "#")
        above = BANDS[i - 1]["C"].replace("~", "#")
        assert below == above, f"chain breaks between rooms {i - 1} and {i}"


def test_no_cell_was_left_uncalled():
    for i, room in enumerate(BANDS):
        for band, s in room.items():
            assert "?" not in s, f"room {i} band {band} has an uncalled cell"
            assert set(s) <= set("#%.~"), f"room {i} band {band} has a stray value"


# --- the water --------------------------------------------------------------
def test_the_three_water_rooms_are_the_only_liquid():
    """Rooms 10, 11 and 12 carry '~'; every other room's floor is rock or a
    hole. Room 13's floor is solid from end to end - it is the miner's."""
    with_liquid = {i for i, r in enumerate(BANDS) if "~" in r["C"]}
    assert with_liquid == {10, 11, 12}
    assert BANDS[13]["C"] == "#" * 38


def test_the_water_rooms_have_no_hole_to_fall_through():
    """Liquid LOOKS like a hole and is not. None of the three water rooms has
    a single '.' in its floor, which is why rooms 11-13 need a side exit and
    a stick rather than a drop."""
    for room in (10, 11, 12):
        assert "." not in BANDS[room]["C"], f"room {room} floor has a real hole"


def test_a_liquid_cell_is_solid_only_on_the_rows_it_is_drawn_on():
    """'~' is air from row 99 to 135 and filled on 136-141, so its wall rect
    is those six rows and not the whole 43 px band. A rect over the whole
    band is an invisible ledge the hero stands on 37 px above the water."""
    y0, y1 = common.LIQUID_ROWS
    for room in (10, 11, 12):
        liquid_x = {8 + 4 * i for i, c in enumerate(BANDS[room]["C"]) if c == "~"}
        for x, y, w, h in HL.WALL_RECTS_L8[room]:
            if x in liquid_x and y >= 99:
                assert (y, h) == (y0, y1 - y0 + 1), (
                    f"room {room}: the liquid rect at x {x} is {h} px tall "
                    f"from row {y}; it must be rows {y0}-{y1}")


def test_the_deadly_rects_are_the_water_line():
    """DEADLY is the lethal surface, taken from the pixels the ROM draws off
    the level's rock ramp. Level 8's water is GREEN (#328432) in a grey cave,
    which is what makes it findable at all.

    Room 13 carries a three-row strip although its floor is solid rock. That
    is what the ROM draws - the same green along rows 139-141 - and it sits
    UNDER 40 px of rock, so nothing can reach it. It is recorded because it
    is drawn, not because it was measured to kill."""
    rooms = {r for r, _x, _y, _w, _h in HL.DEADLY[L - 1]}
    assert rooms == {10, 11, 12, 13}
    for room, x, y, w, h in HL.DEADLY[L - 1]:
        assert y + h - 1 <= 141, "the surface cannot reach past the floor band"
        if room != 13:
            assert (y, h) == (136, 6), f"room {room} water is not the 136-141 line"
    assert (13, 8, 139, 152, 3) in HL.DEADLY[L - 1]


# --- magma ------------------------------------------------------------------
def test_magma_is_in_every_room_down_to_ten_and_none_below():
    """Magma is a property of the ROOM: the corridor colour register is either
    the level hue or magma red. Level 8 is the first level that is magma all
    the way down - rooms 0 to 10 - and the three rooms past the water have
    none at all."""
    with_magma = {i for i, r in enumerate(BANDS) if "%" in r["B"]}
    assert with_magma == set(range(11))
    for room in (11, 12, 13):
        assert "%" not in "".join(BANDS[room].values())


def test_magma_rects_are_exactly_the_percent_cells():
    common.check_magma_is_cave(L, BANDS)


def test_magma_never_leaves_the_corridor_band():
    for _room, _x, y, _w, h in HL.MAGMA[L - 1]:
        assert (y, h) == (60, 39), "magma is a corridor register, not a band"
    for i, room in enumerate(BANDS):
        assert "%" not in room["A"] and "%" not in room["C"], f"room {i}"


# --- dynamite ---------------------------------------------------------------
def test_the_blastable_pillars_are_the_two_cell_ones():
    """Only a run of exactly two cells breaks, and never one that reaches the
    side of the screen."""
    want = []
    for i, room in enumerate(BANDS):
        for first, last in runs_of(room["B"], "#") + runs_of(room["B"], "%"):
            if first == 0 or last == 37 or last - first + 1 != 2:
                continue
            want.append((i, first, last))
    got = {(r, (x - 8) // 4, (x - 8) // 4 + w // 4 - 1)
           for r, x, _y, w, _h, _n in HL.DESTRUCTIBLE[L - 1]}
    assert got == set(want)


def test_room_11s_pillar_is_the_one_that_seals_the_level():
    """Room 11's corridor is open at cell 0, but cells 2-3 stand between the
    hero and that edge, and the ceiling above is solid across the whole room
    so he cannot fly over. Rooms 12 and 13 exist only past this stick."""
    assert BANDS[11]["B"][:4] == "..##"
    assert BANDS[11]["A"] == "#" * 38, "nothing to fly through"
    x, w = cells(2, 3)
    assert (11, x, 60, w, 39, 1) in HL.DESTRUCTIBLE[L - 1]


def test_the_ceiling_comes_down_only_with_room_0s_pillar():
    """The ceiling goes with the pillar only when the ceiling IS that same
    two-cell pillar. Room 0's is; every other one stands under a slab."""
    for room, x, y, _w, h, _n in HL.DESTRUCTIBLE[L - 1]:
        first = (x - 8) // 4
        same = (first, first + 1) in runs_of(BANDS[room]["A"], "#")
        assert (y, h) == ((16, 83) if same else (60, 39)), f"room {room} at x {x}"
        assert same == (room == 0)


def test_the_wide_magma_slabs_are_not_blastable():
    """Room 2's corridor is a fifteen-cell magma slab and a seventeen-cell
    one. Neither is two cells, so neither breaks."""
    wide = [(f, l) for f, l in runs_of(BANDS[2]["B"], "%") if l - f + 1 > 2]
    assert wide, "room 2 should have wide runs to be immune"
    for first, last in wide:
        x, w = cells(first, last)
        assert not any(r == 2 and rx == x for r, rx, *_ in HL.DESTRUCTIBLE[L - 1])


def test_the_shared_wall_table_is_empty():
    common.check_shared_walls(L)


def test_nothing_flares():
    """FLARES is not derivable from a still capture and nothing was measured,
    so it stays empty rather than being authored."""
    assert HL.FLARES[L - 1] == []


# --- the way down -----------------------------------------------------------
def test_the_side_exits_are_the_open_corridor_edges():
    want = set()
    for i, room in enumerate(BANDS):
        if room["B"][0] == ".":
            want.add((i, -1))
        if room["B"][37] == ".":
            want.add((i, 1))
    assert {(r, s) for r, s, _d in HL.SIDE_EXITS[L - 1]} == want


def test_the_direction_of_every_side_exit_is_recorded_not_derived():
    """A side exit's direction is DATA. Level 5 descends through a LEFT edge,
    level 7 through a RIGHT one, and level 8 through LEFT edges again - while
    room 11's and room 12's RIGHT edges lead back UP. Taking the right edge
    of room 11 as 'an exit' is what stopped the walk three rooms early."""
    by_room = {}
    for room, side, delta in HL.SIDE_EXITS[L - 1]:
        by_room.setdefault(room, {})[side] = delta
    assert by_room[10] == {-1: 1}
    assert by_room[11] == {-1: 1, 1: -1}
    assert by_room[12] == {-1: 1, 1: -1}
    assert by_room[13] == {1: -1}, "the last room leads nowhere but back"


def test_every_room_but_the_last_has_a_way_on():
    for i, room in enumerate(BANDS[:-1]):
        down = "." in room["C"]
        side = any(r == i and d == 1 for r, _s, d in HL.SIDE_EXITS[L - 1])
        assert down or side, f"room {i} has no way on"


# --- entities ---------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)


def test_every_entity_in_characters_md_is_present():
    """Every row of the level 8 census table, at that x and y."""
    lanterns = {(r, x, y) for r, x, y in HL.LANTERNS[L - 1]}
    creatures = {(r, x - half, y, KIND_NAME[k])
                 for r, x, y, half, k in HL.SPIDERS[L - 1]}
    for room, what, x, y in CHARACTERS_MD:
        if what == "lantern":
            assert (room, x, y) in lanterns, f"lantern {room} {x},{y} missing"
        else:
            assert (room, x, y, what) in creatures, f"{what} {room} {x},{y} missing"


def test_nothing_was_invented_in_the_rooms_that_have_no_row():
    """Rooms 0 has no entity in the census and none in the capture."""
    assert not any(r == 0 for r, *_ in HL.SPIDERS[L - 1])
    assert not any(r == 0 for r, *_ in HL.LANTERNS[L - 1])


def test_the_deep_rooms_were_never_censused():
    """Rooms 10-13 have no row in the census - it was taken when
    the walker still stopped at room 10 - so what is shipped for them comes
    from the capture. Stated here so it is not mistaken for census data."""
    censused = {r for r, *_ in CHARACTERS_MD}
    assert censused == set(range(1, 10))
    for room, entities in CAPTURED_ONLY.items():
        for what, x, y in entities:
            if what == "miner":
                assert HL.MINER_POS[L - 1] == (room, x, y)
            elif what == "lantern":
                assert (room, x, y) in HL.LANTERNS[L - 1]
            else:
                got = {(r, cx - half, cy, KIND_NAME[k])
                       for r, cx, cy, half, k in HL.SPIDERS[L - 1]}
                assert (room, x, y, what) in got, f"room {room} {what} missing"


def test_the_lanterns_hang_in_the_ceiling_band_on_row_35():
    assert len(HL.LANTERNS[L - 1]) == 10
    assert {r for r, *_ in HL.LANTERNS[L - 1]} == set(range(1, 11))
    for _room, _x, y in HL.LANTERNS[L - 1]:
        assert y == 35, "every lantern in the game hangs on row 35"


def test_the_miner_is_in_the_last_room():
    common.check_miner(L, BANDS)
    room, x, y = HL.MINER_POS[L - 1]
    assert room == 13
    assert (x, y) == (25, 86)


def test_the_two_snakes_are_anchored_in_rock_on_their_left():
    """A snake grows RIGHTWARDS out of a wall's right face, so the x it is
    recorded at is the face, and the cell to its left has to be solid."""
    snakes = [(r, x, y) for r, x, y, _h, k in HL.SPIDERS[L - 1] if k == 3]
    assert len(snakes) == 2
    for room, x, y in snakes:
        # A snake is anchored in the band it is DRAWN in: room 11's grows out
        # of a corridor slab, room 12's out of the rock between its two
        # stretches of water, in the floor band.
        band = "A" if y < 60 else ("B" if y < 99 else "C")
        left_cell = (x - 8) // 4 - 1
        assert BANDS[room][band][left_cell] in "#%~", (
            f"the snake of room {room} has no rock on its left in band {band}")


def test_the_one_bat_patrols_22_px_on_184_frames_and_holds_a_pose_4():
    """The bat's two clocks are different numbers and neither is the
    spider's: it sweeps 22 px on 184 frames and bobs on 64, holding each wing
    pose for 4 frames."""
    bats = [(i, c) for i, c in enumerate(HL.SPIDERS[L - 1]) if c[4] == 1]
    assert len(bats) == 1
    slot, (room, _x, _y, half, _k) = bats[0]
    assert room == 11
    assert 2 * half == 22
    assert 2 * HL.CREATURE_PATROL[(L, slot)] == 184
    travel, half_bob, hold = HL.CREATURE_MOTION[(L, slot)]
    assert (travel, 2 * half_bob, hold) == (7, 64, 4)


def test_the_still_creatures_are_still():
    """Most creatures do not move. The three spiders of rooms 1-3 that
    the census calls still travel nothing and are drawn as ONE sprite."""
    for slot, (room, _x, _y, half, _k) in enumerate(HL.SPIDERS[L - 1]):
        if room in (1, 2, 3):
            assert half == 0, f"slot {slot} should not patrol"
            assert HL.CREATURE_MOTION[(L, slot)][0] == 0, "and should not bob"
            assert HL.CREATURE_SPRITES[(L, slot)] == 1, "and not animate"


def test_only_the_bat_moves_at_all():
    """Whether a creature moves is a property of the ROOM. On level 8 exactly
    one of the nine does."""
    movers = [i for i, c in enumerate(HL.SPIDERS[L - 1])
              if c[3] or HL.CREATURE_MOTION[(L, i)][0]]
    assert movers == [4]


# --- rendering --------------------------------------------------------------
def test_no_activision_logo_is_drawn(env):
    """Rows 189-209 stay black."""
    import jax
    obs, state = env.reset(jax.random.PRNGKey(0))
    frame = np.asarray(env.render(state))
    assert frame[189:210].max() == 0, "something is drawn where the logo was"


def test_room_0_is_grey_and_not_the_boot_palette_brown():
    """The ROM leaves level 1's brown palette in place until the first room
    transition, so room 0 came back brown and is recoloured onto the level's
    own ramp. Level 8's ramp is grey, and a grey ramp has r == g == b."""
    _palette, rooms = common.level_data(L)
    room0 = rooms[0]
    for role in ("dark", "mid", "light"):
        r, g, b = common.rgb(HL.SHADES[L][role])
        assert r == g == b, f"{role} is not a grey"
        assert (room0 == np.array([r, g, b])).all(axis=-1).any(), (
            f"room 0 never paints its {role}")
