"""Level 3, against the corrected ROM reference.

The block in hero_levels.py is generated by tools/hero_gen/build_level.py,
which walks the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), then play the level.

Before the regeneration `level_images/tools/check_level.py 3` matched 1 of
the 6 rooms: the first capture pass kept ROOM 0's corridor band for every
room, so rooms 1-5 all carried room 0's pillar at x 60-67 and none of their
own. Room 3's real pillar is at x 76-83 and room 4's at x 92-99, and rooms
1, 2 and 5 have no interior pillar at all.

Level 3 is the first level with things levels 1 and 2 never had, and each of
them caught a bug in the generator or the engine:

  * two ceiling LANTERNS. A lantern's lamp is painted in exactly the miner's
    lamp-spark yellow, so classifying by that colour called both of them the
    miner and tripped "the miner is on the last screen".
  * three PATROLLING bats. SPIDERS holds the centre of a sweep, not its left
    end, and a sweep runs on its own clock: these bob on 64 frames and
    patrol on 184, where everything measured before held still sideways.

The route, room by room:

    room 0  spawn in the left corridor, blocked by the pillar at x 60-67
            whose ceiling is the same pillar, so it cannot be flown over
            -> plant a stick, run, +75, then down the hole at x 72-87
    room 1  open corridor and a 28-cell floor hole: nothing to do
    room 2  open corridor, holes at x 48-55 and x 104-111
    room 3  pillar at x 76-83 with a hole either side of it, so whichever
            side room 2 drops him on has its own way down
    room 4  pillar at x 92-99 and one hole at x 72-87, on the pillar's left
            - free from room 3's left hole, a blast from its right one
    room 5  the miner's room: solid floor, a bat, and the miner at x 25
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

NOOP, FIRE, UP, RIGHT, LEFT, DOWN = 0, 1, 2, 3, 4, 5
L = 3

# What the ROM draws, cell for cell, in descent order. Generated by
# tools/hero_gen/build_level.py and verified by it against
# level_images/hero_rooms.py before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "##...........##...................####",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "##................................####",
     "C": "####............................######"},
    {"A": "####............................######",
     "B": "##................................####",
     "C": "##########..############..############"},
    {"A": "##########..############..############",
     "B": "##...............##...............####",
     "C": "########..################..##########"},
    {"A": "########..################..##########",
     "B": "##...................##...........####",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "####............................######",
     "C": "######################################"},
]


@pytest.fixture(scope="module")
def env():
    return JaxHero()


def cells(first, last=None):
    """(x, width) of a run of band-string cells, on the 4 px grid from x 8."""
    last = first if last is None else last
    return 8 + 4 * first, 4 * (last - first + 1)


# --- geometry ---------------------------------------------------------------
def test_level_3_is_six_blue_rooms():
    common.check_shape(L, "blue", rooms=6)
    assert len(HL.BG_RLE_L3) == 6


def test_all_six_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_across_all_six_rooms():
    """Room N's ceiling is drawn identically to room N-1's floor. This is the
    invariant the corrected capture is checked against, and it is what the
    first pass broke."""
    for room in range(1, len(BANDS)):
        assert BANDS[room]["A"] == BANDS[room - 1]["C"]


def test_the_corridors_are_not_all_room_0s():
    """The correction, for this level. The superseded capture gave all six
    rooms room 0's corridor band; the ROM draws five different ones, and the
    pillars they carry are the whole shape of the level.

    Rooms 1 and 2 really do draw the same corridor - both are open from cell
    2 to cell 33 - so the ROM keeps one copy of it. Neither of them has an
    interior pillar, so nothing of theirs can be shared and SHARED_WALLS
    stays empty all the same.
    """
    corridors = [b["B"] for b in BANDS]
    assert len(set(corridors)) == 5
    assert corridors[1] == corridors[2] == "##................................####"
    assert corridors[0] == "##...........##...................####"
    assert len({c for r, c in enumerate(corridors) if r != 2}) == 5


def test_the_pillars_are_where_the_rom_puts_them_not_where_room_0_has_one():
    """Room 0's pillar is at cells 13-14; rooms 3 and 4 have their own at
    cells 17-18 and 21-22, and rooms 1, 2 and 5 have none."""
    want = {0: (13, 14), 3: (17, 18), 4: (21, 22)}
    for room, band in enumerate(BANDS):
        b = band["B"]
        runs, start = [], None
        for i, ch in enumerate(b + "."):
            if ch == "#" and start is None:
                start = i
            elif ch != "#" and start is not None:
                runs.append((start, i - 1))
                start = None
        # a run that reaches the side of the screen is the cave wall, not a
        # pillar, and it never breaks
        interior = [r for r in runs if r[0] > 0 and r[1] < 37]
        assert interior == ([want[room]] if room in want else []), \
            f"room {room}: interior pillars {interior}"


def test_room_0_is_the_only_room_that_must_be_blasted():
    """Its hole at x 72-87 is past the pillar at x 60-67, and the ceiling
    above the pillar is that same two-cell pillar, so it cannot be flown
    over. Every other room has a hole reachable without a stick."""
    a, b, c = (BANDS[0][k] for k in "ABC")
    hole = [i for i, ch in enumerate(c) if ch == "."]
    assert cells(hole[0], hole[-1]) == (72, 16)
    assert b[13] == b[14] == "#" and a[13] == a[14] == "#"
    assert a[12] == a[15] == ".", "an isolated ceiling pillar, so it goes too"
    assert all(ch == "." for ch in b[2:13]), "the spawn side is open"
    assert all(ch == "#" for ch in c[:13]), "and its floor is solid"


def test_rooms_3_and_4_have_a_hole_on_the_side_they_are_entered_from():
    """Neither pillar has to be blasted on the route the level is played on.

    Room 2 drops him at x 48-55 or x 104-111; room 3's pillar is at x 76-83
    with a hole at x 40-47 on its left and x 112-119 on its right, so either
    entry has its own way down. Room 4's single hole at x 72-87 is left of
    its pillar at x 92-99, which is where room 3's left hole puts him.
    """
    for room, pillar in ((3, (17, 18)), (4, (21, 22))):
        b, c = BANDS[room]["B"], BANDS[room]["C"]
        entries = [i for i, ch in enumerate(BANDS[room]["A"]) if ch == "."]
        holes = [i for i, ch in enumerate(c) if ch == "."]
        pairs = {(e < pillar[0]) for e in entries} & {(h < pillar[0])
                                                      for h in holes}
        assert pairs, f"room {room}: no hole on the side it is entered from"
        assert all(ch == "#" for ch in b[pillar[0]:pillar[1] + 1])
        assert b[pillar[0] - 1] == b[pillar[1] + 1] == "."


def test_room_5_has_no_hole_and_nothing_interior_to_blast():
    assert BANDS[5]["C"] == "#" * 38
    assert [z for z in HL.DESTRUCTIBLE[2] if z[0] == 5] == []


# --- objects ----------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)
    common.check_miner(L, BANDS)
    common.check_destructibles(L, BANDS)
    common.check_shared_walls(L)
    common.check_magma_is_cave(L, BANDS)


def test_the_level_has_no_magma_and_no_flare():
    assert HL.MAGMA[2] == []
    assert HL.FLARES[2] == []


def test_no_wall_of_this_level_is_shared_with_another():
    """Identical band patterns are one wall in the ROM, so a shared wall pays
    its 75 once. The three rooms that carry a pillar - 0, 3 and 4 - each draw
    a corridor of their own, so none of the three is shared. The superseded
    reference claimed the opposite: one wall, drawn in all six rooms."""
    assert HL.SHARED_WALLS[2] == []
    assert len(HL.DESTRUCTIBLE[2]) == 3
    with_a_pillar = [BANDS[room]["B"] for room, *_r in HL.DESTRUCTIBLE[2]]
    assert len(set(with_a_pillar)) == 3


def test_the_three_blastable_pillars_are_the_three_two_cell_ones():
    """A stick breaks a two-cell corridor pillar and nothing wider, and takes
    the ceiling with it only when the ceiling is that same pillar. Room 0's
    is isolated in the ceiling too, so it goes 83 px; rooms 3 and 4 stand
    under ceiling slabs, so only their 39 px of corridor goes."""
    assert HL.DESTRUCTIBLE[2] == [(0, 60, 16, 8, 83, 1),
                                  (3, 76, 60, 8, 39, 1),
                                  (4, 92, 60, 8, 39, 1)]
    assert BANDS[0]["A"][12] == BANDS[0]["A"][15] == "."
    assert BANDS[3]["A"][17] == BANDS[3]["A"][18] == "#"
    assert BANDS[4]["A"][21] == BANDS[4]["A"][22] == "#"
    for (_room, _x, y, _w, h, _ok) in HL.DESTRUCTIBLE[2]:
        assert y + h <= 99, "a stick never touches the floor band"


def test_the_miner_stands_where_the_rom_puts_him(env):
    assert HL.MINER_POS[2] == (5, 25, 86)
    assert list(np.asarray(env.consts.LEVEL_MINER[2])) == [5, 25, 86]


def test_the_two_lanterns_hang_in_the_ceiling_of_rooms_1_and_3():
    """CHARACTERS.md level 3 puts a 5x8 lamp at (83, 35) in room 1 and
    (107, 35) in room 3. The superseded table had them at y 33.

    Their lamp is painted in the miner's own lamp-spark yellow, which is why
    the generator now settles the kind by band before it looks at colour.
    """
    assert HL.LANTERNS[2] == [(1, 83, 35), (3, 107, 35)]
    for _room, _x, y in HL.LANTERNS[2]:
        assert 16 <= y <= 59, "the ceiling band"


def test_the_seven_creatures_are_where_the_census_put_them():
    """CHARACTERS.md level 3: four spiders and three bats, no snake. The
    superseded table had four kind-3 snakes in it and not one bat.

    A bat's x here is the CENTRE of its sweep, so it is the measured left
    column plus the half-travel: room 1's bat is drawn over x 68-90.

    The untethered spider (kind 4) is the ROM's OTHER spider: no thread, seven
    rows of warm body on their own, flipping between two poses. It was drawn
    with a hanging spider's thread until its sprite was read off the ROM
    (level_images/tools/creature_atlas.py, 2026-09-23). Its second pose is
    drawn two rows below its first, so its measured BOX is 9 px taller than
    the sprite while the creature itself travels 7 - the art carries the
    other two.
    """
    assert HL.SPIDERS[2] == [(1, 44, 70, 0, 0), (1, 79, 103, 11, 1),
                             (2, 48, 70, 0, 0), (3, 40, 109, 0, 0),
                             (3, 104, 65, 0, 4), (4, 75, 64, 11, 1),
                             (5, 52, 64, 11, 1)]
    kinds = [k for *_r, k in HL.SPIDERS[2]]
    assert (kinds.count(0), kinds.count(4), kinds.count(1)) == (3, 1, 3), \
        "three hanging spiders, one untethered and three bats"
    assert 3 not in kinds, "the census found no snake in this level"


def test_still_creatures_are_still_and_the_three_bats_patrol(env):
    """Measured off the ROM with the hero parked out of the picture, 480
    frames of each room.

    Four of the seven never move sideways and three of those never move at
    all; the fourth (room 3, x 104) is an untethered spider that moves 7 px
    and comes back over exactly 64 frames, the same bob level 2's two have.
    The three bats sweep 22 px
    and bob 7, and the two cycles are NOT the same length: 184 frames
    sideways against 64 up and down. A creature driven by one period for
    both would trace a diagonal the ROM never draws.
    """
    c = env.consts
    assert HL.CREATURE_MOTION[(3, 0)] == (0, 0, 8)
    assert HL.CREATURE_MOTION[(3, 1)] == (7, 32, 4)
    assert HL.CREATURE_MOTION[(3, 4)] == (7, 32, 8)
    # this level's rows only: every level that is rebuilt adds its own, and
    # a whole-dict equality here would fail on somebody else's measurement
    assert {k: v for k, v in HL.CREATURE_PATROL.items()
            if k[0] == L} == {(3, 1): 92, (3, 5): 92, (3, 6): 92}

    _, s = env.reset()
    s = s.replace(level=np.int32(L - 1))   # reset() starts on level 1's roster
    seen = [(set(), set()) for _ in HL.SPIDERS[2]]
    for step in range(480):
        x, y = env._spider_pos(s.replace(step_counter=np.int32(step)))
        for i in range(len(seen)):
            seen[i][0].add(int(x[i]))
            seen[i][1].add(int(y[i]))

    for i in (0, 2, 3):
        room, sx, sy, _p, _k = HL.SPIDERS[2][i]
        assert seen[i] == ({sx}, {sy}), f"creature {i} hangs dead still"
    assert seen[4][0] == {104}, "the bobbing spider never moves sideways"
    assert (min(seen[4][1]), max(seen[4][1])) == (65, 72), "7 px of bob"

    for i in (1, 5, 6):
        xs, ys = seen[i]
        centre, patrol = HL.SPIDERS[2][i][1], HL.SPIDERS[2][i][3]
        assert (min(xs), max(xs)) == (centre - patrol, centre + patrol)
        assert max(xs) - min(xs) == 22, "22 px of patrol"
        assert max(ys) - min(ys) == 7, "and 7 of bob"
        assert int(c.SPIDER_PATROL_HALF[L - 1, i]) == 92, "a 184-frame sweep"
        assert int(c.SPIDER_BOB_HALF[L - 1, i]) == 32, "on a 64-frame bob"


def test_a_bat_holds_each_wing_pose_four_frames_and_a_spider_eight(env):
    """CHARACTERS.md: the animation rates are not shared. A bat holds a wing
    pose for four frames, and the spiders of this level hold theirs for
    eight - measured, over 480 frames each, off the sprite the ROM draws."""
    c = env.consts
    for i in (1, 5, 6):
        assert int(c.SPIDER_HOLD[L - 1, i]) == 4, "bat"
    for i in (0, 2, 3, 4):
        assert int(c.SPIDER_HOLD[L - 1, i]) == 8, "spider"


def test_the_bats_do_not_borrow_the_default_patrol_period(env):
    """The engine used to sweep every patrolling creature on one 80-frame
    period. Level 3 is the first regenerated level with a patrol, so this is
    where that would have shown; the unmeasured levels keep the default."""
    c = env.consts
    assert c.spider_patrol_half_period == 40
    assert int(c.SPIDER_PATROL_HALF[L - 1, 1]) == 92
    # level 4's first creature is a spider that hangs dead still, so it
    # sweeps not at all and keeps the default half-period it was never
    # measured to need
    assert int(c.SPIDER_PATROL_HALF[3, 0]) == 40
    assert HL.SPIDERS[3][0][3] == 0


def test_the_flooded_floor_is_the_bottom_three_rows_of_room_5():
    """The last room is flooded exactly the way levels 1 and 2 are, over the
    wavy floor trim on rows 139-141. The floor band above it is solid rock,
    so it is a hazard and not a hole - there is no `~` cell in this level."""
    assert HL.DEADLY[2] == [(5, 8, 139, 152, 3)]
    assert "~" not in "".join(b[k] for b in BANDS for k in "ABC")
    ramp = {common.rgb(HL.SHADES[3][role]) for role in common.ROLES}
    img = HL.decode_bg(HL.BG_RLE_L3[5], HL.PALETTE_L3)
    wet = ~np.isin(img.reshape(-1, 3) @ np.array([1 << 16, 1 << 8, 1]),
                   np.array([r[0] << 16 | r[1] << 8 | r[2] for r in ramp] + [0]))
    rows = sorted(set(np.nonzero(wet.reshape(142, 160))[0].tolist()))
    assert rows == [139, 140, 141]


def test_room_0_is_blue_and_not_level_1s_brown():
    """The fifth correction: the ROM only latches the cave palette on its
    first room transition, so a capture of room 0 comes back in level 1's
    brown. The generator maps the brown ramp onto the level's own."""
    shades = {common.rgb(HL.SHADES[3][role]) for role in common.ROLES}
    brown = {common.rgb(HL.SHADES[1][role]) for role in common.ROLES}
    room0 = HL.decode_bg(HL.BG_RLE_L3[0], HL.PALETTE_L3)
    painted = {tuple(int(v) for v in px) for px in room0.reshape(-1, 3)} - {(0, 0, 0)}
    assert painted <= shades, f"room 0 paints off the blue ramp: {painted - shades}"
    assert not painted & brown


# --- the walls --------------------------------------------------------------
# Where to start for each wall, which way to walk into it and which way to
# run afterwards. None of it is a free choice: walk at a wall across a floor
# hole and the hero drops through the hole instead, so each start has to be
# on the wall's own stretch of solid floor.
#
#   room 0  pillar x 60-67, floor solid from x 8 to 71   -> walk right from 16
#   room 3  pillar x 76-83, floor solid from x 48 to 111 -> walk right from 52
#   room 4  pillar x 92-99, floor solid from x 88 to 159, but the cave wall
#           starts at x 144, so the last column he fits in is 136
APPROACH = {
    (0, 60): (16, RIGHT, LEFT),
    (3, 76): (52, RIGHT, LEFT),
    (4, 92): (132, LEFT, RIGHT),
}


def _wall_w(room, x):
    return next(z[3] for z in HL.DESTRUCTIBLE[2] if z[0] == room and z[1] == x)


def _plant_against(env, room, x):
    """Walk up to the wall at `x`, plant a stick, run, and wait out the fuse."""
    c = env.consts
    from_x, towards, away = APPROACH[(room, x)]
    _, s = env.reset()
    s = s.replace(level=np.int32(L - 1), room=np.int32(room),
                  spider_alive=np.zeros_like(s.spider_alive),
                  player_x=np.int32(from_x), player_y=np.int32(75))
    for _ in range(80):
        _, s, _, _, _ = env.step(s, towards)
    flush = x - c.player_width if towards == RIGHT else x + _wall_w(room, x)
    assert int(s.player_x) == flush, \
        f"room {room}: he should stop flush against the wall at x {x}"
    _, s, _, _, _ = env.step(s, DOWN)
    assert bool(s.dyn_active), f"room {room}: a stick goes down on solid ground"
    for _ in range(30):
        _, s, _, _, _ = env.step(s, away)
    for _ in range(c.dyn_fuse_playable + 6):
        _, s, _, _, _ = env.step(s, NOOP)
    return s


def test_each_of_the_three_walls_pays_its_own_seventy_five(env):
    """Three walls, three separate blasts, 75 each. Under the superseded data
    these were one shared wall drawn in six rooms that paid once."""
    c = env.consts
    for slot, (room, x, *_rest) in enumerate(HL.DESTRUCTIBLE[2]):
        s = _plant_against(env, room, x)
        assert int(s.wall_stage[slot]) == 2, f"room {room}'s wall at x {x} must go"
        assert int(s.score) == c.wall_points == 75, \
            "one wall, one payment - none of them is shared"
        assert int(s.lives) == c.starting_lives, f"room {room}: fled in time"
        others = [i for i in range(len(HL.DESTRUCTIBLE[2])) if i != slot]
        assert all(int(s.wall_stage[i]) == 0 for i in others), \
            "blasting one of them must not clear the others"


def test_room_0s_pillar_blocks_the_way_down_until_it_is_blasted(env):
    _, s = env.reset()
    s = s.replace(level=np.int32(L - 1), room=np.int32(0))
    for _ in range(120):                              # keep pushing right
        _, s, _, _, _ = env.step(s, RIGHT)
    assert int(s.room) == 0, "no way past the pillar without dynamite"

    s = _plant_against(env, 0, 60)
    for _ in range(60):
        _, s, _, _, _ = env.step(s, RIGHT)
        if int(s.player_x) >= 76:
            break
    for _ in range(90):
        _, s, _, _, _ = env.step(s, NOOP)
        if int(s.room) == 1:
            break
    assert int(s.room) == 1, "the floor hole at x 72-87 leads to room 2"
