"""Level 2, against the corrected ROM reference.

The block in hero_levels.py is generated by tools/hero_gen/build_level.py,
which walks the level through the game's own room-transition code, captures
each room off the real ROM and refuses to emit anything unless the capture
agrees with the reference cell for cell. These tests re-check that agreement
from the committed data alone (no ale-py), then play the level.

The bands below are the ROM's own, re-read after the game loaded each room
through its own transition code. The first capture pass kept room 0's
corridor band for every room of the level, which put room 1's pillar at
x 60-67 instead of x 52-59 and made rooms 0, 1 and 3 look like one wall
drawn three times; see level_images/CORRECTIONS.md, which uses this very
room as its worked example. Re-check them against the ROM with
`python tools/check_level.py 2` in level_images.

The route, as the beam search over this engine walks it:

    room 0  spawn at x 33 in the left corridor
            -> walk right, blocked by the pillar at x 60-67, whose ceiling is
               solid too, so it cannot be flown over
            -> plant a stick, run, +75
            -> walk right over the floor hole at x 72-87 and drop
    room 1  land at x ~76 in the right-hand corridor
            -> the floor hole at x 112-119 is on this side of the pillar at
               x 52-59, so nothing has to be blasted here
    room 2  land at x ~116, right of the 11-cell slab at x 64-107
            -> a stick opens the slab, then the wide hole at x 56-103
    room 3  the miner's room: no hole in the floor, a spider bobbing at
            x 108 and the miner at x 128
"""
import numpy as np
import pytest

from jaxatari.games import hero_levels as HL
from jaxatari.games.jax_hero import JaxHero

import level_common as common

NOOP, FIRE, UP, RIGHT, LEFT, DOWN = 0, 1, 2, 3, 4, 5
L = 2

# What the ROM draws, cell for cell, in descent order. Generated by
# tools/hero_gen/build_level.py and verified by it against
# level_images/hero_rooms.py before the level block was emitted.
BANDS = [
    {"A": "####.........##.................######",
     "B": "##...........##...................####",
     "C": "################....##################"},
    {"A": "################....##################",
     "B": "##.........##.....................####",
     "C": "########..################..##########"},
    {"A": "########..################..##########",
     "B": "#####.........###########.........####",
     "C": "############............##############"},
    {"A": "############............##############",
     "B": "####............................######",
     "C": "######################################"},
]


@pytest.fixture(scope="module")
def env():
    return JaxHero()


# --- geometry ---------------------------------------------------------------
def test_level_2_is_four_green_rooms():
    common.check_shape(L, "green", rooms=4)
    assert len(HL.BG_RLE_L2) == 4
    assert (168, 48, 143) in HL.PALETTE_L2, "the magenta surface in room 3"


def test_all_four_rooms_match_the_rom_reference_cell_for_cell():
    common.check_bands(L, BANDS)


def test_walls_sit_on_the_band_grid():
    common.check_walls_on_the_grid(L)


def test_the_rects_cover_exactly_the_rock_that_is_drawn():
    common.check_rects_cover_the_rock(L)


def test_the_chain_holds_across_all_four_rooms():
    """Room N's ceiling is drawn identically to room N-1's floor. This is the
    invariant the corrected capture is checked against, and it is what the
    first pass broke."""
    for room in range(1, len(BANDS)):
        assert BANDS[room]["A"] == BANDS[room - 1]["C"]


def test_room_0_is_the_only_room_whose_hole_is_behind_a_pillar():
    a, b, c = (BANDS[0][k] for k in "ABC")
    assert c.index(".") * 4 + 8 == 72                 # the hole starts at x 72
    assert c.count(".") * 4 == 16                     # and is 16 px wide
    # the pillar at x 60-67 sits between the spawn and the hole, and the
    # ceiling above it is rock, so it has to be blasted
    assert b[13] == b[14] == "#" and a[13] == a[14] == "#"
    assert all(ch == "." for ch in b[15:33]), "open corridor beyond it"


def test_room_1_pillar_is_at_x_52_not_x_60():
    """The correction, in the room CORRECTIONS.md uses as its example.

    The first capture kept room 0's corridor for room 1, which put the pillar
    two cells (8 px) to the right of where the ROM draws it.
    """
    b = BANDS[1]["B"]
    assert b == "##.........##.....................####"
    assert b[11] == b[12] == "#", "the pillar is cells 11-12, x 52-59"
    assert b[13] == b[14] == ".", "and NOT cells 13-14, x 60-67"
    img = HL.decode_bg(HL.BG_RLE_L2[1], HL.PALETTE_L2)
    assert common.bands_of(img)["B"] == b
    assert [z for z in HL.DESTRUCTIBLE[1] if z[0] == 1] == [(1, 52, 60, 8, 39, 1)]
    assert not [r for r in HL.WALL_RECTS_L2[1] if r[0] == 60 and r[1] == 60]


def test_room_1_can_be_left_without_a_blast():
    """Both of room 1's floor holes are at x 40-47 and x 112-119. The hero
    drops in through room 0's hole at x 72-87, which is on the right of the
    pillar at x 52-59 - and so is the hole at x 112-119."""
    b, c = BANDS[1]["B"], BANDS[1]["C"]
    holes = [i for i, ch in enumerate(c) if ch == "."]
    assert [8 + 4 * i for i in holes] == [40, 44, 112, 116]
    entry = (76 - 8) // 4                              # where room 0 drops him
    assert all(ch == "." for ch in b[13:34]), "the right corridor is open"
    assert 13 <= entry <= 33 and 28 in range(13, 34)   # 28 -> x 120


def test_room_2s_eleven_cell_slab_cannot_be_blasted_at_all():
    """Measured on the ROM: five sticks planted along room 2's corridor slab
    (x 64-107, eleven cells), every one confirmed to have gone off because the
    stock in RAM 50 dropped, and not one cell of it was ever removed - while a
    two-cell pillar broke on the first try in the same session. A run wider
    than two cells is immune, so it is not a blastable zone at all.

    The room is still passable: the floor hole at x 56-103 is reached from the
    LEFT corridor (cells 5-13, x 28-63), which overlaps it at cells 12-13.
    """
    assert [z for z in HL.DESTRUCTIBLE[1] if z[0] == 2] == []
    b, c = BANDS[2]["B"], BANDS[2]["C"]
    assert all(ch == "#" for ch in b[14:25]), "eleven solid corridor cells"
    first_gap = b.index(".")
    left_corridor = set(range(first_gap, b.index("#", first_gap)))
    hole = {i for i, ch in enumerate(c) if ch == "."}
    assert left_corridor & hole, "the way down is reachable without a blast"


def test_a_stick_takes_the_ceiling_only_when_the_ceiling_is_the_same_pillar():
    """The rule the old data got wrong, measured on the ROM twice over.

    Both of level 2's blastable walls are two-cell corridor pillars, but they
    do not blast the same way:

      room 0  ceiling A[13:15] is an ISOLATED two-cell pillar, air either
              side - one stick removes the ceiling AND the corridor, 83 px
      room 1  ceiling A[11:13] is part of a SIXTEEN-cell slab - one stick
              removes the corridor only, 39 px, and the ceiling stays

    Measured by planting sticks in the ROM and diffing the bands, and
    corroborated frame by frame against the recorded playthrough, which
    blasts both of these rooms: frames 13->14 for room 0 (ceiling band loses
    cells 13-14) and 28->29 for room 1 (ceiling band unchanged across frames
    29-35, with no unreadable cells in it).

    The floor band is never touched by a stick in either case.
    """
    zones = {z[0]: z for z in HL.DESTRUCTIBLE[1]}

    room0 = zones[0]
    assert room0 == (0, 60, 16, 8, 83, 1)
    assert BANDS[0]["A"][12] == BANDS[0]["A"][15] == ".",         "room 0's ceiling pillar has air either side of it"

    room1 = zones[1]
    assert room1 == (1, 52, 60, 8, 39, 1)
    assert room1[2] == 60 and room1[3] + room1[4] == 8 + 39,         "corridor band only: y 60, 39 px tall"
    assert all(ch == "#" for ch in BANDS[1]["A"][0:16]),         "room 1's ceiling there is a sixteen-cell slab, so it survives"

    # and neither of them ever reaches into the floor band
    for (_room, _x, y, _w, h, _ok) in HL.DESTRUCTIBLE[1]:
        assert y + h <= 99, "a stick never touches the floor band"


def test_room_3_has_no_hole_and_nothing_interior_to_blast():
    assert BANDS[3]["C"] == "#" * 38
    assert [z for z in HL.DESTRUCTIBLE[1] if z[0] == 3] == []


# --- objects ----------------------------------------------------------------
def test_the_object_tables_hold_together():
    common.check_creatures_are_sane(L)
    common.check_miner(L, BANDS)
    common.check_destructibles(L, BANDS)
    common.check_shared_walls(L)
    common.check_magma_is_cave(L, BANDS)


def test_the_level_has_no_lamp_no_magma_and_no_flare():
    assert HL.LANTERNS[1] == [], "the census found no lantern in level 2"
    assert HL.MAGMA[1] == []
    assert HL.FLARES[1] == []


def test_no_wall_of_this_level_is_shared_with_another():
    """Identical band patterns are one wall in the ROM, so a shared wall pays
    its 75 once. All four of level 2's corridors differ, so there are none -
    the opposite of what the superseded reference implied."""
    assert HL.SHARED_WALLS[1] == []
    corridors = [b["B"] for b in BANDS]
    assert len(set(corridors)) == 4


def test_the_miner_stands_where_the_rom_puts_him(env):
    room, x, y = HL.MINER_POS[1]
    assert (room, x, y) == (3, 128, 86)
    assert list(np.asarray(env.consts.LEVEL_MINER[1])) == [3, 128, 86]


def test_all_four_creatures_are_spiders_where_the_census_put_them():
    """CHARACTERS.md level 2: four spiders and no bat. The superseded data
    called the two bobbing ones bats, and had every y a pixel or two out.

    They are not all the SAME spider, though. The ROM draws two forms and the
    difference is plain in the pixels: the two still ones hang under six rows
    of #aaaaaa thread (kind 0), and the two bobbing ones have no thread at all
    - seven rows of warm body on their own, flipping between two poses
    (kind 4). Measured with level_images/tools/creature_atlas.py, which
    records every bitmap of every sprite with the colour of every pixel.
    """
    assert HL.SPIDERS[1] == [(1, 60, 70, 0, 0), (2, 56, 65, 0, 4),
                             (2, 80, 109, 0, 0), (3, 108, 65, 0, 4)]
    assert [kind for *_rest, kind in HL.SPIDERS[1]] == [0, 4, 0, 4]
    assert all(patrol == 0 for *_r, patrol, _k in HL.SPIDERS[1]), \
        "measured over 400 frames: not one of them moves sideways"


def test_two_spiders_hang_still_and_two_bob_nine_pixels(env):
    """Measured off the ROM with the hero parked out of the picture, 400
    frames of each room: the two in rooms 2 and 3 that bob move over a 9 px
    span and come back over exactly 64 frames, and hold each of their two
    bitmaps for 8 frames. The other two never leave their row.

    SEVEN of those nine pixels are the creature moving and TWO are the art:
    the untethered spider's second pose is drawn two rows below its first, so
    the box it is ever inside is 17 rows tall for a sprite that is never more
    than 8. The engine carries the offset in the bitmap and the travel here,
    which is why this says 7 where the box says 9.

    Note this is NOT what CHARACTERS.md says for the bobbing pair - it
    reports 4.0 x 9.0 px at 70/72 frames over 17 sprites. That measurement
    tracks a frame-difference blob, whose box wanders as the body overlaps
    itself; measuring the sprite the ROM actually draws gives a box that is
    7 px wide in every frame and never moves sideways.
    """
    c = env.consts
    assert HL.CREATURE_MOTION[(2, 0)] == (0, 0, 8)
    assert HL.CREATURE_MOTION[(2, 1)] == (7, 32, 8)
    assert HL.CREATURE_MOTION[(2, 2)] == (0, 0, 8)
    assert HL.CREATURE_MOTION[(2, 3)] == (7, 32, 8)
    _, s = env.reset()
    s = s.replace(level=np.int32(1))      # reset() starts on level 1's roster
    seen = [(set(), set()) for _ in range(4)]
    for step in range(400):
        x, y = env._spider_pos(s.replace(step_counter=np.int32(step)))
        for i in range(4):
            seen[i][0].add(int(x[i]))
            seen[i][1].add(int(y[i]))
    assert seen[0] == ({60}, {70}), "room 1's spider hangs dead still"
    assert seen[2] == ({80}, {109}), "room 2's lower spider hangs dead still"
    for i in (1, 3):
        xs, ys = seen[i]
        assert len(xs) == 1, "it never moves sideways"
        assert (min(ys), max(ys)) == (65, 72), \
            "7 px of bob from its top row; the art carries the other two"
    assert int(c.SPIDER_BOB_HALF[1, 1]) == 32, "a 64-frame cycle"
    assert all(int(c.SPIDER_HOLD[1, i]) == 8 for i in range(4))


def test_the_magenta_surface_is_the_bottom_three_rows_of_room_3():
    """The last room is flooded exactly the way level 1's is, in magenta
    rather than blue, animated over the wavy floor trim on rows 139-141.
    The floor band above it is solid rock, so it is a hazard and not a
    hole - there is no `~` cell anywhere in this level.

    The rect is the union over the capture window, not one frame of it: the
    surface scrolls, so any given frame shows only part of the span it
    sweeps. It comes out the same rows and columns as level 1's water.
    """
    assert HL.DEADLY[1] == [(3, 8, 139, 152, 3)]
    liquid = np.array((168, 48, 143), np.uint8)
    img = HL.decode_bg(HL.BG_RLE_L2[3], HL.PALETTE_L2)
    wet = (img == liquid).all(-1)
    assert sorted(np.nonzero(wet.any(axis=1))[0].tolist()) == [139, 140, 141]
    # and no other room of the level has any of it
    for room in range(3):
        other = HL.decode_bg(HL.BG_RLE_L2[room], HL.PALETTE_L2)
        assert not (other == liquid).all(-1).any()


def test_room_0_is_green_and_not_level_1s_brown():
    """The fifth correction: the ROM only latches the cave palette on its
    first room transition, so a capture of room 0 comes back in level 1's
    brown. The generator maps the brown ramp onto the level's own, and this
    is what keeps room 0 the same green as the rest of the level."""
    shades = {common.rgb(HL.SHADES[2][role]) for role in common.ROLES}
    brown = {common.rgb(HL.SHADES[1][role]) for role in common.ROLES}
    room0 = HL.decode_bg(HL.BG_RLE_L2[0], HL.PALETTE_L2)
    painted = {tuple(int(v) for v in px) for px in room0.reshape(-1, 3)} - {(0, 0, 0)}
    assert painted <= shades, f"room 0 paints something off the green ramp: {painted - shades}"
    assert not painted & brown


# --- the walls --------------------------------------------------------------
# Where to start for each wall, which way to walk into it and which way to
# run afterwards. None of it is a free choice: walk at a wall across a floor
# hole and the hero drops through the hole instead, so each start has to be
# on the wall's own stretch of solid floor.
#
#   room 0  pillar x 60-67, floor solid from x 8 to 71 -> walk right from 16
#   room 1  pillar x 52-59, with holes at x 40-47 AND x 112-119 either side
#           of it, so the only approach is the solid strip x 48-111 between
#           them - which is exactly where room 0's hole drops him, x ~76
#
# Room 2's eleven-cell slab is absent because it is not blastable at all.
APPROACH = {
    (0, 60): (16, RIGHT, LEFT),
    (1, 52): (76, LEFT, RIGHT),
}


def _plant_against(env, room, x):
    """Walk up to the wall at `x`, plant a stick, run, and wait out the fuse."""
    c = env.consts
    from_x, towards, away = APPROACH[(room, x)]
    _, s = env.reset()
    s = s.replace(level=np.int32(1), room=np.int32(room),
                  spider_alive=np.zeros_like(s.spider_alive),
                  player_x=np.int32(from_x), player_y=np.int32(75))
    for _ in range(80):
        _, s, _, _, _ = env.step(s, towards)
    flush = x - c.player_width if towards == RIGHT else x + _wall_w(room, x)
    assert int(s.player_x) == flush,         f"room {room}: he should stop flush against the wall at x {x}"
    _, s, _, _, _ = env.step(s, DOWN)
    assert bool(s.dyn_active), f"room {room}: a stick goes down on solid ground"
    for _ in range(30):
        _, s, _, _, _ = env.step(s, away)
    for _ in range(c.dyn_fuse_playable + 6):
        _, s, _, _, _ = env.step(s, NOOP)
    return s


def _wall_w(room, x):
    return next(z[3] for z in HL.DESTRUCTIBLE[1] if z[0] == room and z[1] == x)


def test_each_of_the_two_walls_pays_its_own_seventy_five(env):
    """Two walls, two separate blasts, 75 each. Under the superseded data
    these were one shared wall that paid once."""
    c = env.consts
    assert len(HL.DESTRUCTIBLE[1]) == 2
    for slot, (room, x, *_rest) in enumerate(HL.DESTRUCTIBLE[1]):
        s = _plant_against(env, room, x)
        assert int(s.wall_stage[slot]) == 2, f"room {room}'s wall at x {x} must go"
        assert int(s.score) == c.wall_points == 75,             "one wall, one payment - none of them is shared"
        assert int(s.lives) == c.starting_lives, f"room {room}: fled in time"
        others = [i for i in range(len(HL.DESTRUCTIBLE[1])) if i != slot]
        assert all(int(s.wall_stage[i]) == 0 for i in others),             "blasting one of them must not clear the others"


def test_room_0s_pillar_blocks_the_way_down_until_it_is_blasted(env):
    _, s = env.reset()
    s = s.replace(level=np.int32(1), room=np.int32(0))
    for _ in range(120):                              # keep pushing right
        _, s, _, _, _ = env.step(s, RIGHT)
    assert int(s.room) == 0, "no way past the pillar without dynamite"
    assert int(s.player_x) == 54

    s = _plant_against(env, 0, 60)
    for _ in range(60):
        _, s, _, _, _ = env.step(s, RIGHT)
        if int(s.player_x) >= 76:
            break
    for _ in range(90):
        _, s, _, _, _ = env.step(s, NOOP)
        if int(s.room) == 1:
            break
    assert int(s.room) == 1, "the floor hole at x 72-87 leads to room 1"
