# .github/workflows/on-pull-request-fork.yml
name: Fork PR Tests

on:
  pull_request_target:

jobs:
  prepare-matrix:
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      pr_head_sha: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 0 # Needed for git diff

      - name: Generate matrix for fork
        id: set-matrix
        run: |
          echo "PR is from a fork. Calculating diff between base and head."
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr_head
          CHANGED_GAME_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...pr_head | grep 'src/jaxatari/games/jax_.*\.py' || true)
          if [[ -n "$CHANGED_GAME_FILES" ]]; then
            CHANGED_GAMES=$(echo "$CHANGED_GAME_FILES" | sed -e 's|src/jaxatari/games/jax_||' | sed -e 's|\.py||' | jq -R . | jq -cs .)
          else
            CHANGED_GAMES="[]"
          fi
          echo $CHANGED_GAMES # debug
          echo "matrix=$CHANGED_GAMES" >> $GITHUB_OUTPUT
        shell: bash

  trigger:
    needs: prepare-matrix
    uses: ./.github/workflows/reusable-run-tests.yml
    with:
      game_matrix: ${{ needs.prepare-matrix.outputs.matrix }}
      pr_head_sha: ${{ needs.prepare-matrix.outputs.pr_head_sha }}
