# .github/workflows/on-pull-request.yml
name: PR Tests

on:
  pull_request:
    branches-ignore:
      - master

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix-pr.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git diff

      - name: Generate matrix of changed game files for PR
        id: set-matrix-pr
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_GAMES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep 'src/jaxatari/games/jax_.*\.py' | sed -e 's|src/jaxatari/games/jax_||' -e 's|\.py$||' | jq -R . | jq -cs .)
          echo "matrix=$CHANGED_GAMES" >> $GITHUB_OUTPUT

  trigger:
    needs: prepare-matrix
    uses: ./.github/workflows/reusable-run-tests.yml
    with:
      game_matrix: ${{ needs.prepare-matrix.outputs.matrix }}
