# .github/workflows/pr-tests.yml
name: PR Tests

on:
  pull_request:
  pull_request_target:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      pr_head_sha: ${{ steps.set-matrix.outputs.pr_head_sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git diff

      - name: Generate matrix
        id: set-matrix
        run: |
          # Scenario 1: PR to the default branch in the same repo (run all tests)
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" && "${{ github.base_ref }}" == "${{ github.event.repository.default_branch }}" ]]; then
            echo "PR is to the default branch in the same repository. Testing all games."
            cd src/jaxatari/games/
            CHANGED_GAMES=$(find . -type f -name "jax_*.py" -printf "%f\n" | sed -e 's/^jax_//' -e 's/\.py$//' | jq -R . | jq -cs .)
            echo "pr_head_sha=" >> $GITHUB_OUTPUT

          # Scenario 2: PR to non-default branch in the same repo (run changed tests)
          elif [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" && "${{ github.base_ref }}" != "${{ github.event.repository.default_branch }}" ]]; then
            echo "PR is to a non-master branch in the same repository. Testing changed games."
            CHANGED_GAMES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep 'src/jaxatari/games/jax_.*\.py' | sed -e 's|src/jaxatari/games/jax_||' -e 's|\.py$||' | jq -R . | jq -cs .)
            echo "pr_head_sha=" >> $GITHUB_OUTPUT
          # Scenario 3: PR from a fork (run changed tests)

          elif [[ "${{ github.event_name }}" == "pull_request_target" && "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]]; then
            echo "PR is from a fork. Calculating diff between base and head."
            git fetch origin pull/${{ github.event.pull_request.number }}/head:pr_head
            CHANGED_GAMES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...pr_head | grep 'src/jaxatari/games/jax_.*\.py' | sed -e 's|src/jaxatari/games/jax_||' -e 's|\.py$||' | jq -R . | jq -cs .)
            echo "pr_head_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          fi
          echo "matrix=$CHANGED_GAMES" >> $GITHUB_OUTPUT
        shell: bash

  trigger:
    needs: prepare-matrix
    uses: ./.github/workflows/reusable-run-tests.yml
    with:
      game_matrix: ${{ needs.prepare-matrix.outputs.matrix }}
      pr_head_sha: ${{ needs.prepare-matrix.outputs.pr_head_sha }}
