# .github/workflows/reusable-run-tests.yml
name: Reusable Test Runner

on:
  workflow_call:
    inputs:
      game_matrix:
        description: 'A JSON string of the game matrix to test'
        required: true
        type: string

jobs:
  run-tests:
    if: ${{ inputs.game_matrix != '[]' && inputs.game_matrix != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game: ${{ fromJSON(inputs.game_matrix) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Create venv & install package
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e ".[gh_ci]"
        shell: bash

      - name: Run tests
        run: |
          echo "Running tests for game: ${{ matrix.game }}"

          . .venv/bin/activate
          pytest --game ${{ matrix.game }} --snapshot-warn-unused --tb=line -ra --color=yes
        shell: bash
